/* District backfill for trips 1–50 (trips 51+ carry district inline).
   Merged at runtime: t.district = t.district || TRIP_DISTRICTS[t.n]. */
window.TRIP_DISTRICTS={1:"Rangareddy",2:"Rangareddy",3:"Rangareddy",4:"Rangareddy",
5:"Medchal-Malkajgiri",6:"Rangareddy",7:"Rangareddy",8:"Vikarabad",9:"Vikarabad",
10:"Vikarabad",11:"Rangareddy",12:"Rangareddy",13:"Rangareddy",14:"Medchal-Malkajgiri",
15:"Medchal-Malkajgiri",16:"Yadadri Bhuvanagiri",17:"Yadadri Bhuvanagiri",
18:"Yadadri Bhuvanagiri",19:"Yadadri Bhuvanagiri",20:"Yadadri Bhuvanagiri",
21:"Nalgonda",22:"Jogulamba Gadwal",23:"Nagarkurnool",24:"Medak",25:"Medak",
26:"Siddipet",27:"Karimnagar",28:"Rajanna Sircilla",29:"Nirmal",30:"Nizamabad",
31:"Nirmal",32:"Hanamkonda",33:"Mulugu",34:"Mulugu",35:"Mulugu",36:"Khammam",
37:"Bhadradri Kothagudem",38:"Bhadradri Kothagudem",39:"Peddapalli",40:"Jagtial",
41:"Adilabad",42:"Sangareddy",43:"Sangareddy",44:"Sangareddy",45:"Sangareddy",
46:"Medak",47:"Siddipet",48:"Siddipet",49:"Mahabubnagar",50:"Hyderabad"};
/* Trips 51–100: Hyderabad city + south / central / east Telangana (second ring) */
window.TRIPS4 = [
{n:51,name:"Golconda Fort Dawn Ride",dest:"Golconda Fort, Hyderabad",lat:17.383,lon:78.404,zoom:12,
oneWay:15,total:32,ride:"~1 hr riding + fort",dur:"Half day",durKey:"half",
roads:"City arterials (Saroornagar–Malakpet–Mehdipatnam–Fort Rd); paved urban",
terrain:"Paved city road + fort climb on foot",diff:"Easy",cat:["easy","heritage","scenic"],
district:"Hyderabad",
depart:"06:00",season:"Oct–Mar (cool mornings); sound-and-light evenings",
warn:"Fort opens after sunrise — check timings; Fateh Darwaza traffic; weekends crowded; park only in lots.",
tolls:"None",
desc:"The shortest heritage ride in the book: Qutb Shahi ramparts at dawn, city views, back before traffic wakes.",
attract:"Golconda Fort Bala Hisar viewpoint; Fateh Darwaza; outer-wall photo bays.",
foodB:"City tiffin centres near Malakpet/Mehdipatnam (verify) — ₹100–250.",
foodL:"Old-city meals only if extending (verify) — else return breakfast base.",
fuel:[["Start FULL Saroornagar","0 km"],["No top-up needed; Mehdipatnam corridor pumps if required","~12 km"]],
support:"Dense city corridor — puncture/tyre + workshops everywhere. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel + odo reset","0","—","10"],["Mehdipatnam junction","Regroup; tea halt","10","25 min","15"],["Golconda Fort","Fort walk + viewpoint","5","15 min","90"]],
back:[["Golconda → Mehdipatnam","Cruise","5","15 min","10"],["Mehdipatnam → Saroornagar","Home","10","25 min","—"]],
budget:{food:400,toll:0,park:100,entry:100},
safety:"Fort steps uneven — solid footwear; city lanes: walking pace near monument crowds.",
src:["Telangana Tourism — Golconda","Google Maps routing"]},
{n:52,name:"Qutb Shahi Tombs Trail",dest:"Qutb Shahi Heritage Park (Tombs), Hyderabad",lat:17.394,lon:78.402,zoom:12,
oneWay:16,total:34,ride:"~1 hr riding + park",dur:"Half day",durKey:"half",
roads:"City arterials via Mehdipatnam; paved urban",
terrain:"Paved city road; park on foot",diff:"Easy",cat:["easy","heritage"],
district:"Hyderabad",
depart:"06:30",season:"Oct–Mar",
warn:"Separate complex from Golconda Fort (1 km apart) — different entry; check park timings.",
tolls:"None",
desc:"The royal necropolis: domed Qutb Shahi tombs in landscaped gardens — quieter than the fort, richer in detail.",
attract:"Seven Qutb Shahi tombs; restored stepwells + hamam (verify access); garden promenades.",
foodB:"Mehdipatnam/Tolichowki tiffins (verify) — ₹100–250.",
foodL:"Return-base meals; optional Banjara Hills cafes (verify).",
fuel:[["Start FULL Saroornagar","0 km"],["Mehdipatnam corridor pumps if required","~12 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Mehdipatnam","Tea + regroup","10","25 min","15"],["Qutb Shahi Tombs","Tombs + gardens","6","15 min","90"]],
back:[["Tombs → Mehdipatnam","Cruise","6","15 min","10"],["Mehdipatnam → Saroornagar","Home","10","25 min","—"]],
budget:{food:400,toll:0,park:100,entry:100},
safety:"Monument discipline — no climbing structures; garden paths only.",
src:["Telangana Tourism — Qutb Shahi Heritage Park","Google Maps routing"]},
{n:53,name:"Salar Jung Museum Run",dest:"Salar Jung Museum, Darulshifa (Hyderabad)",lat:17.371,lon:78.48,zoom:12,
oneWay:12,total:26,ride:"~45 min riding + museum",dur:"Half day",durKey:"half",
roads:"City arterials (Saroornagar–Malakpet–Afzal Bridge); paved urban",
terrain:"Paved city road",diff:"Easy",cat:["easy","heritage"],
district:"Hyderabad",
depart:"09:00",season:"Year-round (indoor); closed Fridays — verify",
warn:"Museum closed Friday; old-city parking tight — use paid lots; Friday/monsoon river-road waterlogging (verify).",
tolls:"None",
desc:"One of India's great museums: the Veiled Rebecca, jade daggers, and clocks — a monsoon-proof ride.",
attract:"Salar Jung galleries (Indian/European/Far-Eastern blocks); musical clock (verify timings).",
foodB:"Malakpet tiffins (verify) — ₹100–250.",
foodL:"Old-city meals / Nimrah tea extension (verify) — ₹200–400.",
fuel:[["Start FULL Saroornagar","0 km"],["No top-up needed","—"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Malakpet","Regroup","4","12 min","10"],["Salar Jung Museum","Galleries (2–3 hrs)","8","20 min","150"]],
back:[["Museum → Malakpet","Cruise","8","20 min","10"],["Malakpet → Saroornagar","Home","4","12 min","—"]],
budget:{food:500,toll:0,park:150,entry:200},
safety:"No photography zones inside — follow museum rules; helmets secured in paid parking.",
src:["Salar Jung Museum notices","Google Maps routing"]},
{n:54,name:"Chowmahalla Palace Ride",dest:"Chowmahalla Palace, Khilwat (Hyderabad)",lat:17.357,lon:78.471,zoom:12,
oneWay:10,total:22,ride:"~40 min riding + palace",dur:"Half day",durKey:"half",
roads:"City arterials via Malakpet–Old City; paved, congested lanes",
terrain:"Paved city road; palace on foot",diff:"Easy",cat:["easy","heritage"],
district:"Hyderabad",
depart:"09:30",season:"Oct–Mar",
warn:"Old-city lanes — walking-pace riding; palace check timings/holidays; parking in designated lots.",
tolls:"None",
desc:"Nizam-era courtyards, chandeliers and vintage cars in the heart of the old city.",
attract:"Khilwat Mubarak durbar hall; vintage car gallery (verify); palace courtyards.",
foodB:"Malakpet tiffins (verify) — ₹100–250.",
foodL:"Old-city meals/Shadab extension (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["No top-up needed","—"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Old City gate zone","Slow cruise","6","20 min","10"],["Chowmahalla Palace","Palace (1.5–2 hrs)","4","15 min","110"]],
back:[["Palace → Malakpet","Cruise","7","20 min","10"],["Malakpet → Saroornagar","Home","3","10 min","—"]],
budget:{food:500,toll:0,park:150,entry:200},
safety:"Congested lanes — pillion + luggage slow; no riding inside palace zone.",
src:["Telangana Tourism — Chowmahalla","Google Maps routing"]},
{n:55,name:"Hussain Sagar Tank Bund Cruise",dest:"Hussain Sagar Lake + Tank Bund, Hyderabad",lat:17.423,lon:78.473,zoom:12,
oneWay:18,total:38,ride:"~1.2 hrs riding + lakefront",dur:"Half day",durKey:"half",
roads:"City arterials (Saroornagar–Narayanguda–Tank Bund); paved urban",
terrain:"Paved city road + lakefront promenade",diff:"Easy",cat:["easy","scenic","lakes"],
district:"Hyderabad",
depart:"06:00 / 16:30",season:"Oct–Feb (evenings best)",
warn:"Tank Bund traffic + parked vehicles; no stopping on carriageway — use bays; night riding caution.",
tolls:"None",
desc:"The classic city-lake cruise: Buddha statue, necklace road breeze, and skyline photos.",
attract:"Tank Bund statues promenade; Buddha statue viewpoint; Necklace Rd extension (verify).",
foodB:"Narayanguda/Koti tiffins (verify) — ₹100–250.",
foodL:"Tank Bund snack carts / lakeside outlets (verify hygiene) — ₹150–350.",
fuel:[["Start FULL Saroornagar","0 km"],["Narayanguda corridor pumps if required","~10 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Narayanguda","Regroup","8","20 min","10"],["Tank Bund","Promenade + photos","10","25 min","60"]],
back:[["Tank Bund → Narayanguda","Cruise","10","25 min","10"],["Narayanguda → Saroornagar","Home","8","20 min","—"]],
budget:{food:400,toll:0,park:100,entry:0},
safety:"Lakefront: park only in bays; monsoon — slick promenade tiles.",
src:["Telangana Tourism — Hussain Sagar","Google Maps routing"]},
{n:56,name:"Birla Mandir Hill Climb",dest:"Birla Mandir (Naubat Pahad), Hyderabad",lat:17.406,lon:78.469,zoom:12,
oneWay:15,total:32,ride:"~1 hr riding + temple",dur:"Half day",durKey:"half",
roads:"City arterials via Lakdikapul hill Rd; paved urban",
terrain:"Paved city road + hill steps on foot",diff:"Easy",cat:["easy","temples","scenic"],
district:"Hyderabad",
depart:"06:00",season:"Year-round mornings",
warn:"Hill road one-way discipline; temple footwear/phone rules (verify); parking at base lots.",
tolls:"None",
desc:"White-marble Venkateswara temple on Naubat Pahad with a full city panorama.",
attract:"Birla Mandir sanctum + city viewpoint; Birla Planetarium extension (verify).",
foodB:"Lakdikapul tiffins (verify) — ₹100–250.",
foodL:"Return-base meals.",
fuel:[["Start FULL Saroornagar","0 km"],["No top-up needed","—"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Lakdikapul","Regroup","9","20 min","10"],["Birla Mandir","Darshan + viewpoint","6","15 min","60"]],
back:[["Mandir → Lakdikapul","Cruise","6","15 min","10"],["Lakdikapul → Saroornagar","Home","9","20 min","—"]],
budget:{food:400,toll:0,park:100,entry:0},
safety:"Hill steps — solid footwear; two-wheeler parking at base only.",
src:["Telangana Tourism — Birla Mandir","Google Maps routing"]},
{n:57,name:"KBR National Park Loop",dest:"Kasu Brahmananda Reddy National Park, Jubilee Hills",lat:17.423,lon:78.43,zoom:12,
oneWay:20,total:42,ride:"~1.3 hrs riding + park walk",dur:"Half day",durKey:"half",
roads:"City arterials (Saroornagar–Masab Tank–Jubilee Hills); paved urban",
terrain:"Paved city road + forest trails on foot",diff:"Easy",cat:["easy","wildlife","scenic"],
district:"Hyderabad",
depart:"06:00",season:"Oct–Mar (walking); closed Mondays — verify",
warn:"Park entry slots/timings — verify; Jubilee Hills traffic; no riding inside park.",
tolls:"None",
desc:"A real Deccan forest inside the city: peacocks, chital and 600+ plant species around Chiran Palace.",
attract:"KBR forest trails (verify open trails); Chiran Palace exterior; urban birding.",
foodB:"Masab Tank/Jubilee Hills tiffins (verify) — ₹150–300.",
foodL:"Return-base meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Masab Tank corridor pumps if required","~12 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Masab Tank","Regroup","12","25 min","10"],["KBR Park","Trails (1.5–2 hrs)","8","20 min","110"]],
back:[["KBR → Masab Tank","Cruise","8","20 min","10"],["Masab Tank → Saroornagar","Home","12","25 min","—"]],
budget:{food:400,toll:0,park:100,entry:100},
safety:"Forest: stay on marked trails; carry water; no feeding wildlife.",
src:["Telangana Forest Dept — KBR Park","Google Maps routing"]},
{n:58,name:"Nehru Zoo Expedition",dest:"Nehru Zoological Park, Bahadurpura (Hyderabad)",lat:17.35,lon:78.449,zoom:12,
oneWay:12,total:26,ride:"~45 min riding + zoo",dur:"Half day",durKey:"half",
roads:"City arterials via Chandrayangutta Rd; paved urban",
terrain:"Paved city road; zoo on foot/battery vehicle",diff:"Easy",cat:["easy","wildlife"],
district:"Hyderabad",
depart:"08:30",season:"Oct–Mar; closed Mondays — verify",
warn:"Zoo Monday closure — verify; Bahadurpura traffic; full-day on foot — carry water/caps.",
tolls:"None",
desc:"Big-cat country in the city: lions, tigers and the nocturnal house, plus Mir Alam Tank next door.",
attract:"Lion/tiger safari (verify); nocturnal house; Mir Alam Tank bund extension.",
foodB:"Chandrayangutta tiffins (verify) — ₹100–250.",
foodL:"Zoo canteen / return-base meals (verify) — ₹200–400.",
fuel:[["Start FULL Saroornagar","0 km"],["No top-up needed","—"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Chandrayangutta","Regroup","7","18 min","10"],["Nehru Zoo","Zoo circuit (3 hrs)","5","12 min","180"]],
back:[["Zoo → Chandrayangutta","Cruise","5","12 min","10"],["Chandrayangutta → Saroornagar","Home","7","18 min","—"]],
budget:{food:500,toll:0,park:150,entry:200},
safety:"Heat + walking — hydration discipline; safari queues on weekends.",
src:["Nehru Zoo notices","Google Maps routing"]},
{n:59,name:"Shilparamam Crafts Evening",dest:"Shilparamam Arts & Crafts Village, HITEC City",lat:17.45,lon:78.381,zoom:12,
oneWay:24,total:50,ride:"~1.5 hrs riding + crafts",dur:"Half day",durKey:"half",
roads:"City arterials (Saroornagar–Mehdipatnam–Gachibowli–HITEC); paved urban",
terrain:"Paved city road",diff:"Easy",cat:["easy","scenic","food"],
district:"Hyderabad",
depart:"15:30",season:"Oct–Mar evenings; festival calendars — verify",
warn:"HITEC City peak traffic — time the return; crafts pricing — bargain politely at fixed stalls.",
tolls:"None",
desc:"Crafts-bazaar evening: rural museum, handloom stalls and food courts after a cross-city cruise.",
attract:"Rural museum + rock garden (verify); artisan stalls; evening cultural events (verify).",
foodB:"Mehdipatnam tiffins (verify) — ₹150–300.",
foodL:"Shilparamam food courts (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Gachibowli corridor pumps if required","~18 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Mehdipatnam","Regroup","10","25 min","10"],["Gachibowli → Shilparamam","Crafts village (2 hrs)","14","35 min","120"]],
back:[["Shilparamam → Mehdipatnam","Cruise","14","35 min","10"],["Mehdipatnam → Saroornagar","Home","10","25 min","—"]],
budget:{food:600,toll:0,park:150,entry:100},
safety:"Night return through HITEC corridor — headlights on, lane discipline.",
src:["Shilparamam notices","Google Maps routing"]},
{n:60,name:"Nizam Museum (Purani Haveli) Ride",dest:"Nizam Museum, Purani Haveli (Hyderabad)",lat:17.359,lon:78.474,zoom:12,
oneWay:11,total:24,ride:"~45 min riding + museum",dur:"Half day",durKey:"half",
roads:"City arterials via Malakpet–Afzal Bridge; paved urban",
terrain:"Paved city road",diff:"Easy",cat:["easy","heritage"],
district:"Hyderabad",
depart:"09:30",season:"Year-round; check holidays",
warn:"Old-city congestion; museum photography rules (verify).",
tolls:"None",
desc:"Nizam-era gifts, armour and the famous wardrobe — a compact old-city museum run.",
attract:"Nizam silver jubilee gifts gallery; armoury (verify); Purani Haveli courtyards.",
foodB:"Malakpet tiffins (verify) — ₹100–250.",
foodL:"Old-city meals extension (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["No top-up needed","—"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Afzal Bridge zone","Slow cruise","7","18 min","10"],["Nizam Museum","Galleries (1.5 hrs)","4","12 min","90"]],
back:[["Museum → Malakpet","Cruise","7","18 min","10"],["Malakpet → Saroornagar","Home","4","12 min","—"]],
budget:{food:500,toll:0,park:150,entry:150},
safety:"Narrow old-city lanes — walking pace; secure helmets in parking.",
src:["Nizam Museum notices","Google Maps routing"]},
{n:61,name:"Sanghi Temple Hill",dest:"Sanghi Temple complex, Sanghi Nagar (Rangareddy)",lat:17.279,lon:78.684,zoom:11,
oneWay:35,total:74,ride:"~2 hrs riding + temple",dur:"Half day",durKey:"half",
roads:"Vijayawada Hwy (NH65) + Sanghi Nagar link; highway then hill approach",
terrain:"Good highway + paved hill climb",diff:"Easy",cat:["easy","temples","scenic"],
district:"Rangareddy",
depart:"06:00",season:"Oct–Mar",
warn:"Hill steps — footwear rules; weekend crowds; monkeys near prasad counters.",
tolls:"Possible NH toll (verify)",
desc:"Balaji + Raja Rajeshwari temples on Paramanand Giri with Ramoji-side views.",
attract:"Sanghi Balaji + Raja Rajeshwari shrines; hill viewpoint; Paramanand Giri steps.",
foodB:"Abdullapurmet highway tiffins (verify) — ₹100–250.",
foodL:"Return-base meals; Ramoji-side outlets (verify).",
fuel:[["Start FULL Saroornagar","0 km"],["Abdullapurmet (~25 km)","25 km"]],
support:"NH65 corridor dense. Hospitals: Abdullapurmet/LB Nagar; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Abdullapurmet","Breakfast + fuel check","25","35 min","20"],["Sanghi Hill","Temple + viewpoint","10","20 min","75"]],
back:[["Sanghi → Abdullapurmet","Cruise","10","20 min","10"],["Abdullapurmet → Saroornagar","Home","25","35 min","—"]],
budget:{food:400,toll:50,park:100,entry:0},
safety:"Hill descent — engine braking, no coasting in neutral.",
src:["Telangana Tourism — Sanghi","Google Maps routing"]},
{n:62,name:"Mrugavani National Park Safari",dest:"Mrugavani National Park, Chilkur (Rangareddy)",lat:17.36,lon:78.29,zoom:12,
oneWay:28,total:60,ride:"~1.7 hrs riding + safari",dur:"Half day",durKey:"half",
roads:"Gandipet/Chilkur Rd via Narsingi; paved, good forest-edge 2-lane",
terrain:"Paved road + safari track",diff:"Easy",cat:["easy","wildlife","scenic"],
district:"Rangareddy",
depart:"06:00",season:"Oct–Mar; safari slots — verify",
warn:"Safari/forest entry permissions + timings — verify at gate; Chilkur temple traffic on weekends.",
tolls:"None",
desc:"Deer, peafowl and 600 species of dry-deciduous forest 30 minutes from the city.",
attract:"Mrugavani safari/library point (verify); watchtower; Chilkur temple extension.",
foodB:"Narsingi/Gandipet X Rd tiffins (verify) — ₹100–250.",
foodL:"Return-base meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Gandipet X Rd outlets if required","~18 km"]],
support:"LB Nagar–Gandipet corridor dense. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Gandipet X Rd","Tea + regroup","18","30 min","15"],["Mrugavani","Safari + tower (2 hrs)","10","20 min","120"]],
back:[["Mrugavani → Gandipet X Rd","Cruise","10","20 min","10"],["Gandipet X Rd → Saroornagar","Home","18","30 min","—"]],
budget:{food:400,toll:0,park:100,entry:150},
safety:"Forest: stay in vehicle/zones, no feeding wildlife, carry water.",
src:["Telangana Forest Dept — Mrugavani","Google Maps routing"]},
{n:63,name:"Botanical Garden Spin",dest:"Sri Kotla Vijaya Bhaskar Reddy Botanical Garden, Kondapur",lat:17.452,lon:78.335,zoom:12,
oneWay:24,total:50,ride:"~1.5 hrs riding + garden",dur:"Half day",durKey:"half",
roads:"City arterials via Mehdipatnam–Gachibowli–Kondapur; paved urban",
terrain:"Paved city road + garden trails",diff:"Easy",cat:["easy","scenic"],
district:"Rangareddy",
depart:"06:30",season:"Jun–Feb (green); summer mornings only",
warn:"Garden timings/entry — verify; Gachibowli traffic on return.",
tolls:"None",
desc:"Bamboo groves, medicinal-plant sectors and palm courts — the city's green lung west-side.",
attract:"Bamboo + palm sectors (verify map); rock formations; birding corners.",
foodB:"Gachibowli tiffins (verify) — ₹150–300.",
foodL:"Return-base meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Gachibowli corridor pumps if required","~18 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Gachibowli","Regroup","18","35 min","10"],["Botanical Garden","Trails (1.5 hrs)","6","15 min","90"]],
back:[["Garden → Gachibowli","Cruise","6","15 min","10"],["Gachibowli → Saroornagar","Home","18","35 min","—"]],
budget:{food:400,toll:0,park:100,entry:100},
safety:"Summer heat — hydration; stay on marked trails.",
src:["Telangana Forest Dept — Botanical Garden","Google Maps routing"]},
{n:64,name:"Taramati Baradari Evening",dest:"Taramati Baradari + Ibrahim Bagh, Gandipet Rd",lat:17.372,lon:78.341,zoom:12,
oneWay:22,total:46,ride:"~1.4 hrs riding + venue",dur:"Half day",durKey:"half",
roads:"Inner Ring Rd + Gandipet Rd; paved urban arterial",
terrain:"Paved road",diff:"Easy",cat:["easy","heritage","scenic"],
district:"Rangareddy",
depart:"16:00",season:"Oct–Mar evenings; event calendar — verify",
warn:"Event-day crowds + parking controls — verify schedule; Golconda-view point railings only.",
tolls:"None",
desc:"Ibrahim Qutb Shah's serai reborn as a cultural stage — sunset over the Golconda ridge.",
attract:"Taramati Baradari pavilions; Ibrahim Bagh lawns; Golconda-view sunset point.",
foodB:"Gandipet X Rd tiffins (verify) — ₹100–250.",
foodL:"Venue food stalls on event days (verify) — ₹200–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Gandipet X Rd outlets if required","~15 km"]],
support:"Dense corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Gandipet X Rd","Tea + regroup","15","25 min","15"],["Taramati Baradari","Venue + sunset","7","15 min","90"]],
back:[["Baradari → Gandipet X Rd","Cruise","7","15 min","10"],["Gandipet X Rd → Saroornagar","Home","15","25 min","—"]],
budget:{food:450,toll:0,park:100,entry:100},
safety:"Evening return — headlights on; event parking discipline.",
src:["Telangana Tourism — Taramati Baradari","Google Maps routing"]},
{n:65,name:"Pochampally Handloom Village",dest:"Pochampally Ikkat weaving village, Yadadri Bhuvanagiri",lat:17.386,lon:78.807,zoom:11,
oneWay:55,total:115,ride:"~2.8 hrs riding + looms",dur:"Full day",durKey:"full",
roads:"Vijayawada Hwy (NH65) + Pochampally link; highway then rural paved",
terrain:"Good highway + village lanes",diff:"Easy",cat:["easy","scenic","food"],
district:"Yadadri Bhuvanagiri",
depart:"06:00",season:"Oct–Mar (UNWTO best-tourism-village craft season)",
warn:"Village lanes — slow; loom-house visits — ask before photos; carry cash for weaver outlets.",
tolls:"Possible NH toll (verify)",
desc:"UNWTO-recognised Ikkat village: dye pits, pit looms and Pochampally lake at golden hour.",
attract:"Weaver loom-house visits (verify); Ikkat outlets; Pochampally lake bund.",
foodB:"Choutuppal tiffins (verify) — ₹100–250.",
foodL:"Pochampally/Choutuppal meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Choutuppal (~45 km) top-up","45 km"]],
support:"NH65 corridor dense. Hospitals: Choutuppal/Bhongir; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Choutuppal","Breakfast + fuel","45","55 min","25"],["Pochampally village","Looms + lake","10","20 min","120"]],
back:[["Pochampally → Choutuppal","Tea + fuel check","10","20 min","15"],["Choutuppal → Saroornagar","Cruise","45","55 min","—"]],
budget:{food:650,toll:50,park:100,entry:0},
safety:"Rural lanes — livestock; lake bund soft shoulders.",
src:["Telangana Tourism — Pochampally","Google Maps routing"]},
{n:66,name:"Mothkur Ramalingeshwara Ride",dest:"Ramalingeshwara Temple, Mothkur (Yadadri Bhuvanagiri)",lat:17.45,lon:79.27,zoom:10,
oneWay:105,total:215,ride:"~4.5 hrs riding + temple",dur:"Full day",durKey:"full",
roads:"Vijayawada Hwy + Mothkur rural Rd; highway then paved 2-lane",
terrain:"Paved road",diff:"Moderate",cat:["temples","heritage","food"],
district:"Yadadri Bhuvanagiri",
depart:"05:30",season:"Oct–Mar",
warn:"Rural diversions — follow boards; temple tank steps slippery.",
tolls:"Possible NH toll (verify)",
desc:"Old Shiva kshetra town ride: Mothkur's Ramalingeshwara plus Atmakur-side countryside.",
attract:"Ramalingeshwara Temple complex; Mothkur lake bund; rural photo halts.",
foodB:"Choutuppal tiffins (verify) — ₹100–250.",
foodL:"Mothkur town meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Choutuppal (~45 km) MANDATORY","45 km"],["Mothkur top-up (verify)","~60 km further"]],
support:"Corridor to Choutuppal dense; Mothkur spur basic. Hospitals: Choutuppal/Bhongir; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Choutuppal","Breakfast + fuel","45","55 min","25"],["Mothkur","Temple + lake","60","1h20","75"]],
back:[["Mothkur → Choutuppal","Tea + fuel","60","1h20","20"],["Choutuppal → Saroornagar","Cruise","45","55 min","—"]],
budget:{food:650,toll:50,park:100,entry:50},
safety:"Tank bund — centre-stand footing; rural night riding avoided.",
src:["Telangana Tourism — Yadadri Bhuvanagiri","Google Maps routing"]},
{n:67,name:"Ghanpur Kota Gullu Temples",dest:"Kota Gullu temple group, Ghanpur (Jangaon)",lat:17.85,lon:79.38,zoom:10,
oneWay:130,total:265,ride:"~5.5 hrs riding + temples",dur:"Full day",durKey:"full",
roads:"Warangal Hwy (NH163) + Ghanpur link; highway then rural paved",
terrain:"Paved road",diff:"Moderate",cat:["heritage","temples","scenic"],
district:"Jangaon",
depart:"05:00",season:"Oct–Mar",
warn:"Kakatiya stonework — no climbing; rural last-mile boards only.",
tolls:"Possible NH toll (verify)",
desc:"The 'fort of temples': 22 Kakatiya shrines inside double stone walls.",
attract:"Kota Gullu Trikuta + subsidiary shrines (verify access); Ghanpur lake bund.",
foodB:"Jangaon town tiffins (verify) — ₹100–250.",
foodL:"Ghanpur/Jangaon meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Jangaon (~100 km) MANDATORY","100 km"]],
support:"NH163 corridor dense to Jangaon; Ghanpur spur basic. Hospitals: Jangaon area hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Jangaon","Breakfast + fuel","100","2h","25"],["Ghanpur Kota Gullu","Temples (1.5 hrs)","30","40 min","90"]],
back:[["Ghanpur → Jangaon","Tea + fuel","30","40 min","20"],["Jangaon → Saroornagar","Cruise","100","2h","—"]],
budget:{food:700,toll:100,park:100,entry:50},
safety:"Heritage stone floors — footwear discipline; old walls — keep distance.",
src:["Telangana Tourism — Ghanpur","Google Maps routing"]},
{n:68,name:"Palakurthy Someshwara Circuit",dest:"Someshwara Temple, Palakurthy (Jangaon)",lat:17.65,lon:79.43,zoom:10,
oneWay:120,total:245,ride:"~5 hrs riding + temple",dur:"Full day",durKey:"full",
roads:"Warangal Hwy (NH163) + Palakurthy link; highway then rural paved",
terrain:"Paved road",diff:"Moderate",cat:["temples","heritage","food"],
district:"Jangaon",
depart:"05:00",season:"Oct–Mar",
warn:"Someshwara hill steps — solid footwear; monkeys; rural fuel discipline.",
tolls:"Possible NH toll (verify)",
desc:"Poet Palkuriki Somanatha's town: hilltop Someshwara with valley views.",
attract:"Someshwara hill temple; Palakurthy tank bund; countryside halts.",
foodB:"Jangaon tiffins (verify) — ₹100–250.",
foodL:"Palakurthy town meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Jangaon (~100 km) MANDATORY","100 km"]],
support:"NH163 dense to Jangaon; Palakurthy spur basic. Hospitals: Jangaon; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Jangaon","Breakfast + fuel","100","2h","25"],["Palakurthy","Temple + tank","20","30 min","75"]],
back:[["Palakurthy → Jangaon","Tea + fuel","20","30 min","20"],["Jangaon → Saroornagar","Cruise","100","2h","—"]],
budget:{food:700,toll:100,park:100,entry:50},
safety:"Hill steps slippery when wet; tank bund soft edges.",
src:["Telangana Tourism — Palakurthy","Google Maps routing"]},
{n:69,name:"Zaffargarh Hill Temple",dest:"Lakshmi Narasimha hill temple, Zaffargarh (Jangaon)",lat:17.775,lon:79.485,zoom:10,
oneWay:135,total:275,ride:"~5.5 hrs riding + hill",dur:"Full day",durKey:"full",
roads:"Warangal Hwy + Zaffargarh ghat link; highway then winding hill Rd",
terrain:"Paved road + hill ghat",diff:"Moderate",cat:["temples","hills","scenic"],
district:"Jangaon",
depart:"05:00",season:"Oct–Mar",
warn:"Ghat curves + weekend pilgrim traffic; parking at base lots; steps climb.",
tolls:"Possible NH toll (verify)",
desc:"Fort-hill pilgrimage: Narasimha shrine above Zaffargarh with Deccan views.",
attract:"Zaffargarh hill temple; fort-wall remnants (verify); viewpoint bays.",
foodB:"Jangaon tiffins (verify) — ₹100–250.",
foodL:"Zaffargarh base meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Jangaon (~100 km) MANDATORY","100 km"],["Zaffargarh base top-up (verify)","~35 km further"]],
support:"NH163 dense; hill spur basic. Hospitals: Jangaon; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Jangaon","Breakfast + fuel","100","2h","25"],["Zaffargarh hill","Climb + darshan","35","50 min","90"]],
back:[["Zaffargarh → Jangaon","Tea + fuel","35","50 min","20"],["Jangaon → Saroornagar","Cruise","100","2h","—"]],
budget:{food:700,toll:100,park:100,entry:50},
safety:"Ghat descent — engine braking; hill monkeys — secure food.",
src:["Telangana Tourism — Zaffargarh","Google Maps routing"]},
{n:70,name:"Devarakonda Fort Ride",dest:"Devarakonda Fort, Devarakonda (Nalgonda)",lat:17.00,lon:78.93,zoom:10,
oneWay:110,total:225,ride:"~4.7 hrs riding + fort",dur:"Full day",durKey:"full",
roads:"Nagarjuna Sagar Rd (NH65) + Devarakonda link; highway then rural paved",
terrain:"Paved road + fort hill on foot",diff:"Moderate",cat:["forts","heritage","scenic"],
district:"Nalgonda",
depart:"05:30",season:"Oct–Mar",
warn:"Recherla fort ruins — authorised areas, daylight only; summer heat on rock.",
tolls:"Possible NH toll (verify)",
desc:"Recherla Velama stronghold above Devarakonda town — ramparts, gateways and lake views.",
attract:"Devarakonda Fort walls + gateways; town lake bund; countryside halts.",
foodB:"Choutuppal/Nakrekal-side tiffins (verify) — ₹100–250.",
foodL:"Devarakonda town meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Choutuppal (~45 km)","45 km"],["Devarakonda top-up (verify)","~65 km further"]],
support:"NH65 dense; Devarakonda spur basic. Hospitals: Devarakonda/ Nalgonda; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Choutuppal","Breakfast + fuel","45","55 min","25"],["Devarakonda Fort","Fort walk (1.5 hrs)","65","1h25","90"]],
back:[["Devarakonda → Choutuppal","Tea + fuel","65","1h25","20"],["Choutuppal → Saroornagar","Cruise","45","55 min","—"]],
budget:{food:700,toll:100,park:100,entry:50},
safety:"Ruins — no freestyle climbing; rock heat — morning fort, midday shade.",
src:["Telangana Tourism — Devarakonda","Google Maps routing"]},
{n:71,name:"Panagal Temple Cluster",dest:"Pachala + Chaya Someshwara temples, Panagal (Nalgonda)",lat:17.095,lon:79.285,zoom:10,
oneWay:110,total:225,ride:"~4.7 hrs riding + temples",dur:"Full day",durKey:"full",
roads:"Nagarjuna Sagar Rd + Panagal link; highway then town paved",
terrain:"Paved road",diff:"Easy",cat:["easy","temples","heritage"],
district:"Nalgonda",
depart:"05:30",season:"Oct–Mar",
warn:"Chaya (shadow) phenomenon viewpoint crowds on festival days; tank bund nearby.",
tolls:"Possible NH toll (verify)",
desc:"Kakatiya archaeology twin-pack: Pachala Someshwara plus the famous moving-shadow shrine.",
attract:"Chaya Someshwara Temple; Pachala Someshwara complex; Panagal museum (verify).",
foodB:"Nakrekal/Nalgonda-side tiffins (verify) — ₹100–250.",
foodL:"Panagal/Nalgonda town meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Nalgonda (~100 km) MANDATORY","100 km"]],
support:"NH65 dense; Panagal spur basic. Hospitals: Nalgonda; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Nalgonda","Breakfast + fuel","100","2h","25"],["Panagal temples","Twin temples (1.5 hrs)","10","20 min","90"]],
back:[["Panagal → Nalgonda","Tea + fuel","10","20 min","20"],["Nalgonda → Saroornagar","Cruise","100","2h","—"]],
budget:{food:700,toll:100,park:100,entry:50},
safety:"Temple floors — footwear discipline; festival crowds — park in lots.",
src:["Telangana Tourism — Panagal","Google Maps routing"]},
{n:72,name:"Cheruvugattu Hill Temple",dest:"Jadala Ramalingeshwara hill, Cheruvugattu (Nalgonda)",lat:17.19,lon:79.34,zoom:10,
oneWay:120,total:245,ride:"~5 hrs riding + hill",dur:"Full day",durKey:"full",
roads:"Nagarjuna Sagar Rd + Cheruvugattu ghat link; highway then hill Rd",
terrain:"Paved road + hill climb",diff:"Moderate",cat:["temples","hills","scenic"],
district:"Nalgonda",
depart:"05:00",season:"Oct–Mar; Maha Shivaratri crowds — plan",
warn:"Hill road + festival traffic (verify calendar); steps climb — water discipline.",
tolls:"Possible NH toll (verify)",
desc:"Hilltop Shiva kshetra with a famous jatara — ghat curves plus valley views.",
attract:"Cheruvugattu hill temple; viewpoint bays; Narketpally-side countryside.",
foodB:"Narketpally tiffins (verify) — ₹100–250.",
foodL:"Cheruvugattu base meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Narketpally (~90 km) MANDATORY","90 km"]],
support:"NH65 dense; hill spur basic. Hospitals: Narketpally/Nalgonda; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Narketpally","Breakfast + fuel","90","1h50","25"],["Cheruvugattu hill","Climb + darshan","30","45 min","90"]],
back:[["Cheruvugattu → Narketpally","Tea + fuel","30","45 min","20"],["Narketpally → Saroornagar","Home","90","1h50","—"]],
budget:{food:700,toll:100,park:100,entry:50},
safety:"Ghat + steps — daylight only; festival days — arrive early.",
src:["Telangana Tourism — Cheruvugattu","Google Maps routing"]},
{n:73,name:"Vadapally Sangamam Ride",dest:"Meenakshi–Agastyeshwara temples, Vadapally (Nalgonda)",lat:17.68,lon:79.42,zoom:10,
oneWay:160,total:325,ride:"~6.5 hrs riding + sangam",dur:"1 night / 2 days",durKey:"1n",
roads:"Nagarjuna Sagar Rd + Vadapally riverside link; highway then rural paved",
terrain:"Paved road + river ghat steps",diff:"Moderate",cat:["temples","scenic","long"],
district:"Nalgonda",
depart:"05:00 Day 1",back:"19:00 Day 2",season:"Oct–Feb",
warn:"Krishna–Musi confluence ghats — slippery steps, no swimming; riverside heat.",
tolls:"NH tolls (verify)",
desc:"Where Krishna meets Musi: twin temples on the sangam ghats with coracle views.",
attract:"Vadapally sangam ghats; Meenakshi + Agastyeshwara shrines; riverside sunset.",
foodB:"Day 1: Nalgonda/Miryalaguda tiffins — ₹150–300.",
foodL:"Vadapally/Miryalaguda meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Nalgonda (~100 km) MANDATORY","100 km"],["Miryalaguda top-up (verify)","~60 km further"]],
support:"NH65 dense; riverside spur basic. Hospitals: Miryalaguda/Nalgonda; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Nalgonda","Breakfast + fuel","100","2h","25"],["Miryalaguda → Vadapally","Sangam + temples","60","1h20","120"]],
back:[["Vadapally → Miryalaguda → Nalgonda","Fuel Nalgonda","100","2h10","30"],["Nalgonda → Saroornagar","Cruise","100","2h","—"]],
budget:{food:1200,toll:150,park:150,entry:50},
safety:"Ghat steps — no wading beyond steps; coracles — licensed operators only (verify).",
src:["Telangana Tourism — Vadapally","Google Maps routing"]},
{n:74,name:"Phanigiri Buddhist Excavations",dest:"Phanigiri Buddhist site + museum, Suryapet",lat:17.098,lon:79.479,zoom:10,
oneWay:150,total:305,ride:"~6 hrs riding + site",dur:"1 night / 2 days",durKey:"1n",
roads:"Vijayawada Hwy (NH65) + Phanigiri link; highway then rural paved",
terrain:"Paved road",diff:"Moderate",cat:["heritage","long","scenic"],
district:"Suryapet",
depart:"05:00 Day 1",back:"19:00 Day 2",season:"Oct–Mar",
warn:"Excavation mounds — stay on paths; museum timings — verify; summer heat on open site.",
tolls:"NH tolls (verify)",
desc:"Satavahana-era mahavihara on a hillock: stupas, viharas and a site museum.",
attract:"Phanigiri stupa + vihara ruins (verify access); site museum; hillock viewpoint.",
foodB:"Day 1: Suryapet tiffins — ₹150–300.",
foodL:"Phanigiri/Suryapet meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Suryapet (~135 km) MANDATORY","135 km"]],
support:"NH65 dense to Suryapet; site spur basic. Hospitals: Suryapet; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Suryapet","Breakfast + fuel","135","2h40","30"],["Phanigiri site","Ruins + museum","15","30 min","120"]],
back:[["Phanigiri → Suryapet","Tea + fuel","15","30 min","20"],["Suryapet → Saroornagar","Cruise","135","2h40","—"]],
budget:{food:1200,toll:150,park:150,entry:100},
safety:"Open mounds — hats + water; no climbing stupas.",
src:["Telangana Archaeology — Phanigiri","Google Maps routing"]},
{n:75,name:"Mattapalli Krishna Temple",dest:"Lakshmi Narasimha Temple, Mattapalli (Suryapet)",lat:17.65,lon:79.52,zoom:10,
oneWay:170,total:345,ride:"~7 hrs riding + temple",dur:"1 night / 2 days",durKey:"1n",
roads:"Vijayawada Hwy + Mattapalli riverside link; highway then rural paved",
terrain:"Paved road + riverbank",diff:"Moderate",cat:["temples","scenic","long"],
district:"Suryapet",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Oct–Feb",
warn:"Krishna bank — no swimming; Huzurnagar-side rural fuel discipline.",
tolls:"NH tolls (verify)",
desc:"Krishna-side Narasimha kshetra: temple town calm plus wide river views.",
attract:"Mattapalli temple street; Krishna bank viewpoint; Huzurnagar countryside.",
foodB:"Day 1: Suryapet tiffins — ₹150–300.",
foodL:"Mattapalli/Huzurnagar meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Suryapet (~135 km) MANDATORY","135 km"],["Huzurnagar top-up (verify)","~35 km further"]],
support:"NH65 dense; riverside spur basic. Hospitals: Huzurnagar/Suryapet; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Suryapet","Breakfast + fuel","135","2h40","30"],["Mattapalli","Temple + bank","35","50 min","120"]],
back:[["Mattapalli → Suryapet","Tea + fuel","35","50 min","20"],["Suryapet → Saroornagar","Cruise","135","2h40","—"]],
budget:{food:1200,toll:150,park:150,entry:50},
safety:"Riverbank — stay above steps; rural night riding avoided.",
src:["Telangana Tourism — Mattapalli","Google Maps routing"]},
{n:76,name:"Mellacheruvu Shambhu Temple",dest:"Shambhu Lingeshwara Temple, Mellacheruvu (Suryapet)",lat:17.77,lon:79.75,zoom:10,
oneWay:160,total:325,ride:"~6.5 hrs riding + temple",dur:"1 night / 2 days",durKey:"1n",
roads:"Vijayawada Hwy + Mellacheruvu link; highway then rural paved",
terrain:"Paved road",diff:"Moderate",cat:["temples","heritage","long"],
district:"Suryapet",
depart:"05:00 Day 1",back:"19:00 Day 2",season:"Oct–Mar",
warn:"Ancient stonework — monument discipline; rural last-mile boards.",
tolls:"NH tolls (verify)",
desc:"Chola–Kakatiya layers in one complex: Mellacheruvu's Shambhu temple.",
attract:"Shambhu Lingeshwara complex; temple tank; rural halts.",
foodB:"Day 1: Suryapet tiffins — ₹150–300.",
foodL:"Mellacheruvu/Suryapet meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Suryapet (~135 km) MANDATORY","135 km"]],
support:"NH65 dense; temple spur basic. Hospitals: Suryapet; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Suryapet","Breakfast + fuel","135","2h40","30"],["Mellacheruvu","Temple (1.5 hrs)","25","40 min","90"]],
back:[["Mellacheruvu → Suryapet","Tea + fuel","25","40 min","20"],["Suryapet → Saroornagar","Cruise","135","2h40","—"]],
budget:{food:1200,toll:150,park:150,entry:50},
safety:"Old stone floors — footwear discipline; festival crowds — lots only.",
src:["Telangana Tourism — Mellacheruvu","Google Maps routing"]},
{n:77,name:"Wyra Reservoir Ride",dest:"Wyra Reservoir + boating point, Khammam",lat:17.18,lon:79.38,zoom:9,
oneWay:210,total:425,ride:"~8 hrs riding + reservoir",dur:"1 night / 2 days",durKey:"1n",
roads:"Vijayawada Hwy (NH65) + Wyra link; fast highway then rural paved",
terrain:"Good highway + reservoir bund",diff:"Moderate",cat:["lakes","scenic","long"],
district:"Khammam",
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Feb (full reservoir)",
warn:"Bund roads — slow, no racing; boating timings — verify; highway heat.",
tolls:"NH tolls (verify)",
desc:"Big-water east ride: Wyra reservoir bund cruise plus Khammam food.",
attract:"Wyra bund + boating point (verify); sunset bays; Khammam town halt.",
foodB:"Day 1: Suryapet tiffins — ₹150–300.",
foodL:"Wyra/Khammam meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Suryapet (~135 km) MANDATORY","135 km"],["Khammam top-up","~75 km further"]],
support:"NH65 dense; reservoir spur basic. Hospitals: Khammam; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Suryapet","Breakfast + fuel","135","2h40","30"],["Khammam → Wyra","Reservoir bund","75","1h40","120"]],
back:[["Wyra → Khammam → Suryapet","Fuel Suryapet","150","3h","25"],["Suryapet → Saroornagar","Cruise","135","2h40","—"]],
budget:{food:1400,toll:200,park:200,entry:100},
safety:"Bund shoulders soft — centre-stand footing; boating — life jackets (verify).",
src:["Telangana Tourism — Wyra","Google Maps routing"]},
{n:78,name:"Palair Reservoir Getaway",dest:"Palair Reservoir + Jetties, Khammam",lat:17.23,lon:79.90,zoom:9,
oneWay:190,total:385,ride:"~7.5 hrs riding + lake",dur:"1 night / 2 days",durKey:"1n",
roads:"Vijayawada Hwy + Palair link; highway then rural paved",
terrain:"Good highway + lake bund",diff:"Moderate",cat:["lakes","scenic","long","food"],
district:"Khammam",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Aug–Feb",
warn:"Lake development-zone rules — verify boating; bund discipline.",
tolls:"NH tolls (verify)",
desc:"Weekend-lake energy: Palair's jetties, islands and fish-food stalls.",
attract:"Palair jetties + island views (verify); lake parks; Khammam food run.",
foodB:"Day 1: Suryapet tiffins — ₹150–300.",
foodL:"Palair lakeside + Khammam meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Suryapet (~135 km) MANDATORY","135 km"],["Palair top-up (verify)","~55 km further"]],
support:"NH65 dense; lake spur basic. Hospitals: Khammam; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Suryapet","Breakfast + fuel","135","2h40","30"],["Palair Lake","Jetties + sunset","55","1h15","120"]],
back:[["Palair → Suryapet","Tea + fuel","55","1h15","20"],["Suryapet → Saroornagar","Cruise","135","2h40","—"]],
budget:{food:1400,toll:200,park:200,entry:100},
safety:"Water edge — no wading; jetty queues on weekends.",
src:["Telangana Tourism — Palair","Google Maps routing"]},
{n:79,name:"Nelakondapalli Stupa Trail",dest:"Nelakondapalli Buddhist stupa + museum, Khammam",lat:17.10,lon:79.08,zoom:9,
oneWay:200,total:405,ride:"~8 hrs riding + site",dur:"1 night / 2 days",durKey:"1n",
roads:"Vijayawada Hwy + Nelakondapalli link; highway then rural paved",
terrain:"Paved road + site paths",diff:"Moderate",cat:["heritage","long","scenic"],
district:"Khammam",
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Mar",
warn:"Open excavation site — hats + water; museum timings — verify.",
tolls:"NH tolls (verify)",
desc:"Buddhist Khammam: stupas, viharas and terracotta at Nelakondapalli.",
attract:"Nelakondapalli stupa complex (verify access); site museum; rural halts.",
foodB:"Day 1: Suryapet tiffins — ₹150–300.",
foodL:"Nelakondapalli/Khammam meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Suryapet (~135 km) MANDATORY","135 km"],["Khammam top-up","~65 km further"]],
support:"NH65 dense; site spur basic. Hospitals: Khammam; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Suryapet","Breakfast + fuel","135","2h40","30"],["Nelakondapalli","Site + museum","65","1h30","120"]],
back:[["Nelakondapalli → Suryapet","Tea + fuel","65","1h30","20"],["Suryapet → Saroornagar","Cruise","135","2h40","—"]],
budget:{food:1400,toll:200,park:200,entry:100},
safety:"Mounds — stay on paths; no removal of artefacts, obviously.",
src:["Telangana Archaeology — Nelakondapalli","Google Maps routing"]},
{n:80,name:"Parnasala Godavari Retreat",dest:"Parnasala (Ramayana site) + Godavari bank, Bhadradri Kothagudem",lat:17.93,lon:79.89,zoom:9,
oneWay:260,total:530,ride:"~10 hrs riding over 2 days + river",dur:"2 nights / 3 days",durKey:"2n",
roads:"Warangal–Khammam–Bhadrachalam Hwy + Parnasala riverside link; long highway + rural tail",
terrain:"Good highway + riverbank",diff:"Challenging",cat:["long","scenic","heritage"],
district:"Bhadradri Kothagudem",
depart:"04:00 Day 1",back:"21:00 Day 3",season:"Oct–Feb",
warn:"Very long ride — overnight discipline; riverbank — no swimming; forest-edge caution.",
tolls:"NH tolls (verify)",
desc:"Grand Ramayana riverside: Parnasala's thatched vanavasa sets on the Godavari.",
attract:"Parnasala cultural complex (verify); Godavari bank sunset; Bhadrachalam extension.",
foodB:"Day 1: Warangal tiffins.",
foodL:"Parnasala/Bhadrachalam meals (verify) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Warangal (~148 km) MANDATORY","148 km"],["Bhadrachalam top-up MANDATORY","~110 km further"]],
support:"Dense to Bhadrachalam; riverside tail basic. Hospitals: Bhadrachalam; 108/112.",
route:[["Saroornagar start","Fuel + long-ride briefing","0","—","15"],["Warangal","Breakfast + MANDATORY fuel","148","3h","30"],["Bhadrachalam → Parnasala","Riverside + complex","112","2h30","150"]],
back:[["Parnasala → Bhadrachalam → Warangal","Fuel Warangal","150","3h20","25"],["Warangal → Saroornagar","Cruise","148","3h","30"]],
budget:{food:1800,toll:250,park:200,entry:200},
safety:"Multi-day fatigue plan — two nights; riverbank after dark avoided.",
src:["Telangana Tourism — Parnasala","Google Maps routing"]},
{n:81,name:"Pakhal Lake & Sanctuary",dest:"Pakhal Lake + Wildlife Sanctuary, Mahabubabad",lat:17.95,lon:79.99,zoom:9,
oneWay:150,total:305,ride:"~6 hrs riding + sanctuary",dur:"1 night / 2 days",durKey:"1n",
roads:"Warangal Hwy (NH163) + Narsampet–Pakhal forest Rd; highway then forest 2-lane",
terrain:"Paved road + forest edge",diff:"Moderate",cat:["lakes","wildlife","long","scenic"],
district:"Mahabubabad",
depart:"05:00 Day 1",back:"19:00 Day 2",season:"Oct–Feb",
warn:"Sanctuary entry rules + safari timings — verify at gate; forest — no halts except bays.",
tolls:"NH tolls (verify)",
desc:"Kakatiya-era lake inside teak forest: Pakhal's bund plus deer and bird calls.",
attract:"Pakhal bund + forest rest-house zone (verify); safari point; Narsampet halt.",
foodB:"Day 1: Warangal tiffins.",
foodL:"Pakhal/Narsampet meals (verify; carry backup) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Warangal (~148 km) MANDATORY","148 km"]],
support:"Dense to Warangal/Narsampet; forest tail sparse. Hospitals: Narsampet/Warangal; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Warangal","Breakfast + fuel","148","3h","30"],["Pakhal","Bund + forest","30","45 min","150"]],
back:[["Pakhal → Warangal","Tea + fuel","30","45 min","20"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:1300,toll:150,park:200,entry:200},
safety:"Forest: daylight only, no honking, tank-full discipline.",
src:["Telangana Forest Dept — Pakhal","Google Maps routing"]},
{n:82,name:"Kuravi Veerabhadra Temple",dest:"Veerabhadra Temple, Kuravi (Mahabubabad)",lat:17.66,lon:79.96,zoom:9,
oneWay:150,total:305,ride:"~6 hrs riding + temple",dur:"1 night / 2 days",durKey:"1n",
roads:"Warangal Hwy + Kuravi link; highway then rural paved",
terrain:"Paved road",diff:"Easy",cat:["easy","temples","long"],
district:"Mahabubabad",
depart:"05:00 Day 1",back:"19:00 Day 2",season:"Oct–Mar",
warn:"Shivaratri crowds — verify calendar; rural fuel discipline.",
tolls:"NH tolls (verify)",
desc:"Kakatiya-era Veerabhadra with famous Nandi mandapa — calm temple-town overnighter.",
attract:"Kuravi temple complex; temple tank; Mahabubabad town halt.",
foodB:"Day 1: Warangal tiffins.",
foodL:"Kuravi/Mahabubabad meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Warangal (~148 km) MANDATORY","148 km"]],
support:"Dense corridor; Kuravi spur basic. Hospitals: Mahabubabad; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Warangal","Breakfast + fuel","148","3h","30"],["Kuravi","Temple (1.5 hrs)","25","35 min","90"]],
back:[["Kuravi → Warangal","Tea + fuel","25","35 min","20"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:1300,toll:150,park:150,entry:50},
safety:"Temple-town lanes — slow; festival days — early arrival.",
src:["Telangana Tourism — Kuravi","Google Maps routing"]},
{n:83,name:"Inavolu Mallikarjuna Ride",dest:"Mallikarjuna Temple, Inavolu (Hanamkonda)",lat:17.99,lon:79.63,zoom:10,
oneWay:148,total:300,ride:"~6 hrs riding + temple",dur:"Full day",durKey:"full",
roads:"Warangal Hwy (NH163); fast divided highway + town link",
terrain:"Good highway + town lanes",diff:"Moderate",cat:["temples","food"],
district:"Hanamkonda",
depart:"05:00",back:"20:00",season:"Oct–Mar",
warn:"Long highway day — fatigue plan; Inavolu lanes on festival days.",
tolls:"NH tolls (verify)",
desc:"Kakatiya suburb temple: Inavolu's Mallikarjuna plus Warangal food on the way.",
attract:"Inavolu temple complex; Warangal city food halt; Hanamkonda corridors.",
foodB:"Warangal tiffins — ₹150–300.",
foodL:"Inavolu/Warangal meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Warangal (~148 km) MANDATORY top-up","148 km"]],
support:"NH163 dense. Hospitals: Warangal/MGM; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Warangal","Breakfast + MANDATORY fuel","148","3h","30"],["Inavolu","Temple (1 hr)","8","15 min","60"]],
back:[["Inavolu → Warangal","Tea","8","15 min","15"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:800,toll:150,park:150,entry:50},
safety:"300-km day — hydration + planned halts; night return avoided.",
src:["Telangana Tourism — Inavolu","Google Maps routing"]},
{n:84,name:"Dharmasagar Lake Loop",dest:"Dharmasagar Lake, Hanamkonda",lat:17.00,lon:79.47,zoom:10,
oneWay:155,total:315,ride:"~6.2 hrs riding + lake",dur:"1 night / 2 days",durKey:"1n",
roads:"Warangal Hwy (NH163) + Dharmasagar link; highway then bund Rd",
terrain:"Good highway + lake bund",diff:"Easy",cat:["easy","lakes","long","scenic"],
district:"Hanamkonda",
depart:"05:00 Day 1",back:"19:00 Day 2",season:"Aug–Feb",
warn:"Bund soft shoulders; boating (verify) — life jackets.",
tolls:"NH tolls (verify)",
desc:"Warangal's second lake: Dharmasagar bund cruise with fort-city food.",
attract:"Dharmasagar bund + parks (verify); sunset bays; Warangal fort extension.",
foodB:"Day 1: Warangal tiffins.",
foodL:"Dharmasagar/Warangal meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Warangal (~148 km) MANDATORY","148 km"]],
support:"NH163 dense. Hospitals: Warangal/MGM; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Warangal","Breakfast + fuel","148","3h","30"],["Dharmasagar","Bund + parks","15","25 min","120"]],
back:[["Dharmasagar → Warangal","Tea + fuel","15","25 min","20"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:1300,toll:150,park:200,entry:100},
safety:"Bund + water — no wading; weekend park crowds.",
src:["Telangana Tourism — Dharmasagar","Google Maps routing"]},
{n:85,name:"Pandavula Gutta Rock Art",dest:"Pandavula Gutta rock shelters, Regonda (Jayashankar Bhupalpally)",lat:18.235,lon:79.418,zoom:10,
oneWay:160,total:325,ride:"~6.5 hrs riding + rock art",dur:"1 night / 2 days",durKey:"1n",
roads:"Karimnagar Hwy + Regonda link; highway then rural paved + hill track",
terrain:"Paved road + rocky hill on foot",diff:"Moderate",cat:["heritage","hills","long","scenic"],
district:"Jayashankar Bhupalpally",
depart:"05:00 Day 1",back:"19:00 Day 2",season:"Oct–Mar",
warn:"Prehistoric shelters — no touching paintings; hill rocks slippery; guide (verify) recommended.",
tolls:"State tolls (verify)",
desc:"Telangana's Lascaux: Mesolithic rock paintings on Pandavula Gutta.",
attract:"Rock shelters + paintings (verify access); hill viewpoint; Regonda countryside.",
foodB:"Day 1: Karimnagar-side tiffins — ₹150–300.",
foodL:"Regonda/Parkal meals (verify; carry backup) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"]],
support:"Highway dense to Karimnagar; Regonda spur basic. Hospitals: Karimnagar/Parkal; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Karimnagar","Breakfast + fuel","165","3h20","30"],["Pandavula Gutta","Shelters (2 hrs)","25","40 min","120"]],
back:[["Gutta → Karimnagar","Tea + fuel","25","40 min","20"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1200,toll:150,park:150,entry:100},
safety:"Rocky hill — solid footwear, daylight only; no littering at site.",
src:["Telangana Archaeology — Pandavula Gutta","Google Maps routing"]},
{n:86,name:"Kaleshwaram Sangamam (Grand North)",dest:"Kaleshwaram Mukteshwara + Triveni Sangamam, Jayashankar Bhupalpally",lat:18.81,lon:79.90,zoom:9,
oneWay:250,total:505,ride:"~10 hrs riding over 2 days + sangam",dur:"1 night / 2 days",durKey:"1n",
roads:"Karimnagar–Manthani–Kaleshwaram Hwy; long highway + ghat tail",
terrain:"Good highway + river ghats",diff:"Challenging",cat:["long","temples","scenic"],
district:"Jayashankar Bhupalpally",
depart:"04:00 Day 1",back:"21:00 Day 2",season:"Oct–Feb",
warn:"One of the longest Telangana runs — two-day discipline; Godavari–Pranahita sangam ghats — no swimming.",
tolls:"State tolls (verify)",
desc:"The northern Triveni: Mukteshwara temple where Godavari meets Pranahita.",
attract:"Kaleshwaram temple complex; Triveni Sangamam ghats; Saraswati pushkar point (verify).",
foodB:"Day 1: Karimnagar tiffins.",
foodL:"Kaleshwaram/Manthani meals (verify; carry backup) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"],["Manthani top-up MANDATORY","~55 km further"]],
support:"Dense to Karimnagar/Manthani; tail basic. Hospitals: Manthani/Karimnagar; 108/112.",
route:[["Saroornagar start","Fuel + long-ride briefing","0","—","15"],["Karimnagar","Breakfast + fuel","165","3h20","30"],["Manthani → Kaleshwaram","Sangam + temples","85","2h","150"]],
back:[["Kaleshwaram → Manthani → Karimnagar","Fuel Karimnagar","140","3h","25"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1600,toll:200,park:200,entry:100},
safety:"505-km weekend — fatigue kills pace; ghat steps after dark avoided.",
src:["Telangana Tourism — Kaleshwaram","Google Maps routing"]},
{n:87,name:"Eturnagaram Sanctuary Run",dest:"Eturnagaram Wildlife Sanctuary gate, Mulugu",lat:18.33,lon:79.43,zoom:9,
oneWay:200,total:410,ride:"~8 hrs riding + forest",dur:"1 night / 2 days",durKey:"1n",
roads:"Warangal–Eturnagaram forest Hwy; highway then long forest 2-lane",
terrain:"Paved + patchy forest stretches",diff:"Challenging",cat:["wildlife","long","adventure"],
district:"Mulugu",
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Feb; Sammakka–Saralamma jatara season crowds (verify)",
warn:"Forest division rules — permits/timings at gate (verify); elephants/crossings signed; no night forest riding.",
tolls:"State tolls (verify)",
desc:"Oldest sanctuary in Telangana: teak forest, Dayyam Vagu and the jatara grounds.",
attract:"Sanctuary gate + interpretation (verify); Dayyam Vagu viewpoint; forest watch points.",
foodB:"Day 1: Warangal tiffins.",
foodL:"Eturnagaram meals (verify; thin — carry backup) — ₹250–450.",
fuel:[["Start FULL","0 km"],["Warangal (~148 km) MANDATORY","148 km"],["Eturnagaram top-up (verify) MANDATORY","~80 km further"]],
support:"Dense to Warangal; forest belt sparse. Hospitals: Eturnagaram PHC/Warangal; 108/112.",
route:[["Saroornagar start","Fuel + forest briefing","0","—","15"],["Warangal","Breakfast + MANDATORY fuel","148","3h","30"],["Eturnagaram","Gate + forest (2 hrs)","80","1h45","120"]],
back:[["Eturnagaram → Warangal","Early start; fuel","80","1h45","20"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:1400,toll:150,park:200,entry:200},
safety:"Forest: daylight only, headlights on, no halts except bays; gate rules absolute.",
src:["Telangana Forest Dept — Eturnagaram","Google Maps routing"]},
{n:88,name:"Mallur Hemachala Temple",dest:"Hemachala Lakshmi Narasimha Temple, Mallur (Mulugu)",lat:18.19,lon:79.55,zoom:9,
oneWay:215,total:440,ride:"~8.5 hrs riding + hill",dur:"1 night / 2 days",durKey:"1n",
roads:"Warangal–Eturnagaram Hwy + Mallur hill link; highway then forest hill Rd",
terrain:"Paved road + hill climb",diff:"Challenging",cat:["temples","hills","long"],
district:"Mulugu",
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Mar",
warn:"Forest hill road + Chintamani stream causeway (verify water); steps climb.",
tolls:"State tolls (verify)",
desc:"Hilltop Narasimha in the Eturnagaram forests with the Chintamani stream below.",
attract:"Mallur hill temple; Chintamani stream viewpoint (verify); forest halts.",
foodB:"Day 1: Warangal tiffins.",
foodL:"Mallur/Eturnagaram meals (verify; carry backup) — ₹250–450.",
fuel:[["Start FULL","0 km"],["Warangal (~148 km) MANDATORY","148 km"],["Eturnagaram top-up (verify)","~67 km further"]],
support:"Dense to Warangal; forest tail sparse. Hospitals: Eturnagaram/Warangal; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Warangal","Breakfast + MANDATORY fuel","148","3h","30"],["Eturnagaram → Mallur","Hill + temple","67","1h30","120"]],
back:[["Mallur → Eturnagaram → Warangal","Fuel Warangal","115","2h30","20"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:1400,toll:150,park:200,entry:100},
safety:"Hill + stream — monsoon causeway check; forest daylight discipline.",
src:["Telangana Tourism — Mallur","Google Maps routing"]},
{n:89,name:"Medaram Jatara Grounds",dest:"Sammakka–Saralamma Gadde, Medaram (Mulugu)",lat:18.253,lon:79.242,zoom:9,
oneWay:190,total:390,ride:"~7.5 hrs riding + grounds",dur:"1 night / 2 days",durKey:"1n",
roads:"Warangal–Eturnagaram Hwy + Medaram link; highway then forest 2-lane",
terrain:"Paved road + forest",diff:"Moderate",cat:["scenic","long","heritage"],
district:"Mulugu",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Oct–Feb; Maha Jatara (biennial) — verify dates, extreme crowds",
warn:"Jatara season = massive crowds + diversions (verify); off-season = quiet forest halt.",
tolls:"State tolls (verify)",
desc:"Asia's great tribal congregation grounds: Medaram's gadde plus Jampanna Vagu.",
attract:"Sammakka–Saralamma gadde (verify); Jampanna Vagu; forest drive.",
foodB:"Day 1: Warangal tiffins.",
foodL:"Medaram/Eturnagaram meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Warangal (~148 km) MANDATORY","148 km"],["Medaram top-up (verify)","~60 km further"]],
support:"Dense to Warangal; forest tail sparse. Hospitals: Eturnagaram/Warangal; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Warangal","Breakfast + fuel","148","3h","30"],["Medaram","Gadde + vagu","60","1h20","120"]],
back:[["Medaram → Warangal","Early start; fuel","60","1h20","20"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:1300,toll:150,park:200,entry:50},
safety:"Jatara traffic plan — police diversions; forest daylight only.",
src:["Telangana Tourism — Medaram","Google Maps routing"]},
{n:90,name:"Kondagattu Hill Temple",dest:"Anjaneya hill temple, Kondagattu (Jagtial)",lat:17.50,lon:78.97,zoom:10,
oneWay:200,total:405,ride:"~8 hrs riding + hill",dur:"1 night / 2 days",durKey:"1n",
roads:"Karimnagar Hwy (NH563) + Kondagattu ghat link; highway then hill Rd",
terrain:"Good highway + hill ghat",diff:"Moderate",cat:["temples","hills","long"],
district:"Jagtial",
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Mar",
warn:"Famous Hanuman kshetra — weekend pilgrim rush; ghat parking discipline.",
tolls:"State tolls (verify)",
desc:"Fort-hill of devotion: Kondagattu's Anjaneya with 40-ft Gopuram views.",
attract:"Kondagattu hill temple; fort-wall remnants (verify); viewpoint bays.",
foodB:"Day 1: Karimnagar tiffins.",
foodL:"Kondagattu base/Karimnagar meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"]],
support:"Highway dense; hill spur basic. Hospitals: Karimnagar/Jagtial; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Karimnagar","Breakfast + fuel","165","3h20","30"],["Kondagattu hill","Climb + darshan","35","50 min","120"]],
back:[["Kondagattu → Karimnagar","Tea + fuel","35","50 min","20"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1300,toll:150,park:150,entry:50},
safety:"Ghat + crowds — arrive early; steps — water discipline.",
src:["Telangana Tourism — Kondagattu","Google Maps routing"]},
{n:91,name:"Jagityal Fort Town",dest:"New Gad (Jagityal) Fort + town, Jagtial",lat:18.79,lon:78.91,zoom:10,
oneWay:210,total:425,ride:"~8 hrs riding + fort",dur:"1 night / 2 days",durKey:"1n",
roads:"Karimnagar Hwy + Jagtial link; long highway + town lanes",
terrain:"Good highway + old-town lanes",diff:"Moderate",cat:["forts","heritage","long","food"],
district:"Jagtial",
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Mar",
warn:"Old-town lanes slow; fort timings — verify; long day — fatigue plan.",
tolls:"State tolls (verify)",
desc:"Nizam-era garrison town: Jagityal's star-shaped New Gad fort plus market food.",
attract:"New Gad Fort walls + gateways (verify access); old-town markets; Jagtial food.",
foodB:"Day 1: Karimnagar tiffins.",
foodL:"Jagtial town meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"],["Jagtial top-up","~45 km further"]],
support:"Highway dense; town basic. Hospitals: Jagtial area hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Karimnagar","Breakfast + fuel","165","3h20","30"],["Jagtial Fort","Fort + market","45","1h","120"]],
back:[["Jagtial → Karimnagar","Tea + fuel","45","1h","20"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1300,toll:150,park:150,entry:100},
safety:"Fort walls — authorised areas; market lanes — walking pace.",
src:["Telangana Tourism — Jagtial","Google Maps routing"]},
{n:92,name:"Elgandal Fort Ride",dest:"Elgandal Fort + hill, Karimnagar",lat:18.42,lon:79.05,zoom:10,
oneWay:165,total:335,ride:"~6.8 hrs riding + fort",dur:"1 night / 2 days",durKey:"1n",
roads:"Karimnagar Hwy (NH563); fast highway + fort hill link",
terrain:"Good highway + hill on foot",diff:"Moderate",cat:["forts","heritage","long","scenic"],
district:"Karimnagar",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Oct–Mar",
warn:"Qutb Shahi hill fort — climb discipline; Brindavan tank nearby (verify).",
tolls:"State tolls (verify)",
desc:"Karimnagar's own hill fort: Elgandal's ramparts over the Manair plains.",
attract:"Elgandal ramparts + dargah point (verify); hill viewpoint; Karimnagar food.",
foodB:"Day 1: Karimnagar tiffins (verify) — ₹150–300.",
foodL:"Karimnagar city meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"]],
support:"Highway dense. Hospitals: Karimnagar; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Karimnagar","Breakfast + MANDATORY fuel","165","3h20","30"],["Elgandal Fort","Climb (1.5 hrs)","8","15 min","90"]],
back:[["Elgandal → Karimnagar","Tea","8","15 min","15"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1200,toll:150,park:150,entry:50},
safety:"Hill rocks — solid footwear; fort after dark avoided.",
src:["Telangana Tourism — Elgandal","Google Maps routing"]},
{n:93,name:"Odela Mallikarjuna Temple",dest:"Mallikarjuna Temple, Odela (Peddapalli)",lat:18.47,lon:79.62,zoom:10,
oneWay:210,total:425,ride:"~8 hrs riding + temple",dur:"1 night / 2 days",durKey:"1n",
roads:"Karimnagar–Ramagundam Hwy + Odela link; highway then rural paved",
terrain:"Paved road",diff:"Moderate",cat:["temples","long"],
district:"Peddapalli",
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Mar",
warn:"Coal-belt truck traffic near Ramagundam corridor; rural fuel discipline.",
tolls:"State tolls (verify)",
desc:"Peddapalli's temple town: Odela's Mallikarjuna with Godavari-belt countryside.",
attract:"Odela temple complex; temple tank; coal-belt highway contrasts.",
foodB:"Day 1: Karimnagar tiffins.",
foodL:"Odela/Sultanabad meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"],["Odela top-up (verify)","~45 km further"]],
support:"Highway dense; Odela spur basic. Hospitals: Peddapalli/Karimnagar; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Karimnagar","Breakfast + fuel","165","3h20","30"],["Odela","Temple (1.5 hrs)","45","1h","90"]],
back:[["Odela → Karimnagar","Tea + fuel","45","1h","20"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1300,toll:150,park:150,entry:50},
safety:"Mining-corridor trucks — daylight, headlights on, no tailgating.",
src:["Telangana Tourism — Odela","Google Maps routing"]},
{n:94,name:"Sircilla Handloom + Lake Day",dest:"Handloom town + Pedda Cheruvu, Sircilla (Rajanna Sircilla)",lat:18.38,lon:78.81,zoom:10,
oneWay:140,total:285,ride:"~5.8 hrs riding + looms",dur:"Full day",durKey:"full",
roads:"Karimnagar Hwy (NH563) + Sircilla link; highway then town lanes",
terrain:"Good highway + town lanes",diff:"Easy",cat:["easy","scenic","food"],
district:"Rajanna Sircilla",
depart:"05:00",back:"20:00",season:"Oct–Mar",
warn:"Powerloom-town traffic; lake bund evenings popular — parking discipline.",
tolls:"State tolls (verify)",
desc:"Textile-town day: Sircilla's looms and Pedda Cheruvu sunset.",
attract:"Handloom outlets + loom visits (verify); Pedda Cheruvu bund; town food.",
foodB:"Siddipet-side tiffins (verify) — ₹100–250.",
foodL:"Sircilla town meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Siddipet (~100 km) top-up","100 km"]],
support:"Highway dense. Hospitals: Sircilla area hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Siddipet","Breakfast + fuel","100","2h","25"],["Sircilla","Looms + lake","40","55 min","120"]],
back:[["Sircilla → Siddipet","Tea + fuel","40","55 min","20"],["Siddipet → Saroornagar","Cruise","100","2h","—"]],
budget:{food:750,toll:100,park:100,entry:0},
safety:"Town lanes — slow; lake bund after dark avoided.",
src:["Telangana Tourism — Sircilla","Google Maps routing"]},
{n:95,name:"Mid Manair Dam Ride",dest:"Mid Manair Dam + reservoir, Rajanna Sircilla",lat:18.35,lon:78.98,zoom:10,
oneWay:148,total:300,ride:"~6 hrs riding + dam",dur:"Full day",durKey:"full",
roads:"Karimnagar Hwy + Mid Manair link; highway then dam Rd",
terrain:"Good highway + dam bund",diff:"Easy",cat:["easy","lakes","scenic"],
district:"Rajanna Sircilla",
depart:"05:00",back:"20:00",season:"Aug–Feb (water); dam zones — designated points",
warn:"Dam restricted zones — viewpoints only; bund discipline.",
tolls:"State tolls (verify)",
desc:"Balancing-reservoir run: Mid Manair's long bund between Sircilla and Karimnagar.",
attract:"Mid Manair bund + viewpoints (verify); reservoir bays; Karimnagar food.",
foodB:"Siddipet tiffins (verify) — ₹100–250.",
foodL:"Sircilla/Karimnagar meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Siddipet (~100 km) top-up","100 km"],["Sircilla top-up","~48 km further"]],
support:"Highway dense. Hospitals: Sircilla/Karimnagar; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Siddipet","Breakfast + fuel","100","2h","25"],["Mid Manair","Bund + bays","48","1h05","90"]],
back:[["Mid Manair → Siddipet","Tea + fuel","48","1h05","20"],["Siddipet → Saroornagar","Cruise","100","2h","—"]],
budget:{food:750,toll:100,park:150,entry:0},
safety:"Dam water — no wading; bund shoulders soft.",
src:["Irrigation Dept — Mid Manair notices","Google Maps routing"]},
{n:96,name:"Komuravelli Mallanna Hill",dest:"Mallikarjuna (Mallanna) hill temple, Komuravelli (Siddipet)",lat:17.93,lon:78.96,zoom:10,
oneWay:110,total:225,ride:"~4.7 hrs riding + hill",dur:"Full day",durKey:"full",
roads:"Medchal–Siddipet Hwy + Komuravelli hill link; highway then hill Rd",
terrain:"Paved road + hill steps",diff:"Moderate",cat:["temples","hills","scenic"],
district:"Siddipet",
depart:"05:30",season:"Dec–Feb (Bonalu/Mallanna jatara season — verify crowds)",
warn:"Jatara-season crowds (verify); hill steps; monkeys.",
tolls:"State tolls (verify)",
desc:"The Mallanna hill: Komuravelli's famous shrine with a brisk ghat climb.",
attract:"Komuravelli hill temple; viewpoint; Siddipet food halt.",
foodB:"Siddipet-side tiffins (verify) — ₹100–250.",
foodL:"Komuravelli base/Siddipet meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Siddipet (~100 km) top-up","100 km"]],
support:"Highway dense; hill spur basic. Hospitals: Siddipet; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Siddipet","Breakfast + fuel","100","2h","25"],["Komuravelli hill","Climb + darshan","10","20 min","90"]],
back:[["Komuravelli → Siddipet","Tea","10","20 min","15"],["Siddipet → Saroornagar","Cruise","100","2h","—"]],
budget:{food:700,toll:100,park:100,entry:50},
safety:"Hill steps — water discipline; festival days — early arrival.",
src:["Telangana Tourism — Komuravelli","Google Maps routing"]},
{n:97,name:"Edupayala River Temple",dest:"Vana Durga Temple on Manjeera, Edupayala (Medak)",lat:17.92,lon:78.10,zoom:10,
oneWay:110,total:225,ride:"~4.7 hrs riding + river",dur:"Full day",durKey:"full",
roads:"Mumbai Hwy (NH65) + Edupayala riverside link; highway then rural paved",
terrain:"Good highway + riverbank",diff:"Easy",cat:["easy","temples","scenic"],
district:"Medak",
depart:"05:30",season:"Oct–Feb (river full); monsoon causeway — verify",
warn:"Manjeera causeway water levels — verify before crossing; riverbank slippery.",
tolls:"Possible NH toll (verify)",
desc:"Forest goddess on the river: Edupayala's Vana Durga where Manjeera splits around the shrine.",
attract:"Edupayala temple island (verify); Manjeera viewpoints; Papannapet countryside.",
foodB:"Narsapur-side tiffins (verify) — ₹100–250.",
foodL:"Edupayala/Papannapet meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Narsapur (~85 km) top-up","85 km"]],
support:"NH65 dense; riverside spur basic. Hospitals: Medak/Narsapur; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Narsapur","Breakfast + fuel","85","1h45","25"],["Edupayala","Temple + river","25","35 min","90"]],
back:[["Edupayala → Narsapur","Tea + fuel check","25","35 min","15"],["Narsapur → Saroornagar","Cruise","85","1h45","—"]],
budget:{food:700,toll:100,park:100,entry:50},
safety:"Causeway + river — water-level check absolute; no wading.",
src:["Telangana Tourism — Edupayala","Google Maps routing"]},
{n:98,name:"Kulcharam Temple Town",dest:"Kashi Vishweshwara + temples, Kulcharam (Medak)",lat:17.90,lon:78.15,zoom:10,
oneWay:100,total:205,ride:"~4.3 hrs riding + temples",dur:"Full day",durKey:"full",
roads:"Mumbai Hwy + Kulcharam link; highway then town lanes",
terrain:"Good highway + town lanes",diff:"Easy",cat:["easy","temples","heritage"],
district:"Medak",
depart:"06:00",season:"Oct–Mar",
warn:"Old-town lanes slow; temple-town festival days (verify).",
tolls:"Possible NH toll (verify)",
desc:"Temple-town morning: Kulcharam's old Shiva shrines plus Medak-side countryside.",
attract:"Kulcharam temple street; old-town architecture; countryside halts.",
foodB:"Narsapur tiffins (verify) — ₹100–250.",
foodL:"Kulcharam/Medak meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Narsapur (~85 km) top-up","85 km"]],
support:"NH65 dense. Hospitals: Medak; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Narsapur","Breakfast + fuel","85","1h45","25"],["Kulcharam","Temples (1 hr)","15","25 min","60"]],
back:[["Kulcharam → Narsapur","Tea","15","25 min","15"],["Narsapur → Saroornagar","Cruise","85","1h45","—"]],
budget:{food:650,toll:100,park:100,entry:0},
safety:"Town lanes — walking pace near shrines.",
src:["Telangana Tourism — Kulcharam","Google Maps routing"]},
{n:99,name:"Jharasangam Basaveshwara Ride",dest:"Basaveshwara Temple, Jharasangam (Sangareddy)",lat:17.72,lon:77.65,zoom:10,
oneWay:120,total:245,ride:"~5 hrs riding + temple",dur:"Full day",durKey:"full",
roads:"Mumbai Hwy (NH65) + Jharasangam link; highway then rural paved",
terrain:"Good highway + rural paved",diff:"Moderate",cat:["temples","scenic","food"],
district:"Sangareddy",
depart:"05:30",season:"Oct–Mar",
warn:"Rural last-mile boards; Zaheerabad-side truck traffic.",
tolls:"Possible NH toll (verify)",
desc:"Lingayat heritage ride: Jharasangam's Basaveshwara plus border-town food.",
attract:"Jharasangam temple complex; rural Deccan halts; Zaheerabad food.",
foodB:"Sadasivpet tiffins (verify) — ₹100–250.",
foodL:"Jharasangam/Zaheerabad meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Sadasivpet (~80 km) top-up","80 km"]],
support:"NH65 dense. Hospitals: Zaheerabad; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Sadasivpet","Breakfast + fuel","80","1h40","25"],["Jharasangam","Temple (1 hr)","40","55 min","60"]],
back:[["Jharasangam → Sadasivpet","Tea + fuel","40","55 min","15"],["Sadasivpet → Saroornagar","Cruise","80","1h40","—"]],
budget:{food:700,toll:100,park:100,entry:0},
safety:"Rural roads — livestock; night riding avoided.",
src:["Telangana Tourism — Jharasangam","Google Maps routing"]},
{n:100,name:"Narayankhed Fort Town",dest:"Old fort + town, Narayankhed (Sangareddy)",lat:18.05,lon:77.77,zoom:10,
oneWay:140,total:285,ride:"~5.8 hrs riding + fort",dur:"Full day",durKey:"full",
roads:"Mumbai Hwy + Narayankhed link via Zaheerabad; highway then rural paved",
terrain:"Good highway + town lanes",diff:"Moderate",cat:["forts","heritage","food"],
district:"Sangareddy",
depart:"05:00",back:"20:00",season:"Oct–Mar",
warn:"Border-town lanes; fort remnants — authorised areas; long day fatigue.",
tolls:"Possible NH toll (verify)",
desc:"North-west frontier town: Narayankhed's old fort walls and Deccan markets.",
attract:"Narayankhed fort remnants (verify); old-town markets; Zaheerabad food.",
foodB:"Zaheerabad tiffins (verify) — ₹150–300.",
foodL:"Narayankhed town meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Zaheerabad (~125 km) MANDATORY","125 km"]],
support:"NH65 dense to Zaheerabad; town spur basic. Hospitals: Zaheerabad; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Zaheerabad","Breakfast + MANDATORY fuel","125","2h40","30"],["Narayankhed","Fort + market","15","25 min","90"]],
back:[["Narayankhed → Zaheerabad","Tea + fuel","15","25 min","15"],["Zaheerabad → Saroornagar","Cruise","125","2h40","—"]],
budget:{food:750,toll:100,park:100,entry:50},
safety:"Old walls — keep distance; market lanes — walking pace.",
src:["Telangana Tourism — Narayankhed","Google Maps routing"]}
];


