/* Trips 18–34: mid ring — heritage, lakes, early long rides */
window.TRIPS2 = [
{n:18,name:"Kolanupaka Jain Temple Circuit",dest:"Kolanupaka Jain Temple, Kolanupaka (via Yadadri)",lat:17.59,lon:79.03,zoom:10,
oneWay:82,total:172,ride:"~3.6 hrs riding + temples",dur:"Full day",durKey:"full",
roads:"NH65 + Yadadri–Kolanupaka rural Rd; good highway then paved 2-lane",
terrain:"Paved road",diff:"Easy",cat:["heritage","easy","scenic"],
depart:"05:00",back:"16:00",season:"Oct–Mar",
warn:"800-year-old temple: silence/footwear rules; rural diversions — follow boards, not shortcuts.",
tolls:"Possible NH toll (verify)",
desc:"Twin-heritage day: Yadadri darshan + the serene 2,000-year-old Kolanupaka Jain complex.",
attract:"Kolanupaka (Kulpakji) Jain Temple + museum; Yadadri viewpoint.",
foodB:"Choutuppal/Yadadri tiffins — ₹100–250.",
foodL:"Yadadri/Kolanupaka town meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Choutuppal (~45 km)","45 km"],["Yadadri (~72 km)","27 km further"]],
support:"Corridor dense to Yadadri; Kolanupaka spur basic — plan accordingly. Hospitals: Yadadri hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Choutuppal","Breakfast","45","55 min","25"],["Yadadri (optional halt)","Viewpoint/regroup","27","40 min","20"],["Yadadri → Kolanupaka","Rural cruise","10","20 min","10"],["Kolanupaka Temple","Darshan + museum","1","5 min","75"]],
back:[["Kolanupaka → Yadadri → Choutuppal","Lunch + fuel","37","60 min","40"],["Choutuppal → Saroornagar","Cruise","45","55 min","—"]],
budget:{food:650,toll:50,park:100,entry:50},
safety:"Jain complex: no leather inside shrines (custom); park only in lots.",
src:["Telangana Tourism — Kolanupaka","Google Maps routing"]},
{n:19,name:"Rachakonda Fort Expedition",dest:"Rachakonda Fort, Ranga Reddy / Yadadri border",lat:17.24,lon:78.97,zoom:10,
oneWay:68,total:145,ride:"~3.4 hrs riding + fort walk",dur:"Full day",durKey:"full",
roads:"Vijayawada Hwy → Choutuppal → Rachakonda Rd; highway then rural paved + final gravel/rock approach",
terrain:"Paved road + gravel near fort; fort on foot",diff:"Moderate",cat:["adventure","heritage"],
depart:"05:00",back:"16:00",season:"Oct–Mar (trek); avoid wet rock",
warn:"Remote ruins; final approach rough — Scrambler only to base village, trek on foot; carry water; patchy network.",
tolls:"Possible NH toll (verify)",
desc:"Lost-fort adventure for history nerds: Kakatiya-era ruins in splendid isolation.",
attract:"Rachakonda Fort ruins; village scenery; Choutuppal lake halt.",
foodB:"Choutuppal tiffins — ₹100–250.",
foodL:"Packed/Choutuppal meals — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Choutuppal (~45 km) mandatory top-up","45 km"]],
support:"Choutuppal last reliable cluster. Fort section: 'No verified roadside mechanic found at this section — plan accordingly.' Hospitals: Choutuppal/Bhongir; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Choutuppal","Breakfast + fuel (mandatory)","45","55 min","25"],["Rachakonda base village","Park; trek briefing","23","45 min","15"],["Fort ruins (on foot)","Explore + return to bikes","3","20 min","90"]],
back:[["Base → Choutuppal","Lunch + fuel check","23","45 min","40"],["Choutuppal → Saroornagar","Cruise","45","55 min","—"]],
budget:{food:600,toll:50,park:50,entry:0},
safety:"No off-road heroics on loose rock; trek in shoes, not riding boots on slick stone; group stays together — patchy signal.",
src:["Telangana Tourism — Rachakonda","Google Maps routing"]},
{n:20,name:"Choutuppal Lake & Food Halt",dest:"Choutuppal town + lake, Yadadri Bhuvanagiri",lat:17.253,lon:78.901,zoom:11,
oneWay:48,total:100,ride:"~2.4 hrs riding + halts",dur:"Half day",durKey:"half",
roads:"NH65; good highway",
terrain:"Good highway",diff:"Easy",cat:["easy","food"],
depart:"06:00 / 16:00",back:"11:30 / 20:00",season:"All year",
warn:"Highway u-turns near town; eatery parking on service lanes.",
tolls:"Possible NH toll (verify)",
desc:"The reliable halfway-town ride every Hyderabad biker knows — built for breakfast runs.",
attract:"Choutuppal lake viewpoint; town food strip.",
foodB:"Choutuppal highway tiffins/dhabas (verified clusters, e.g. NH-side restaurants) — ₹100–300.",
foodL:"Meals on return strip.",
fuel:[["Start FULL Saroornagar","0 km"],["Choutuppal outlets","~48 km"]],
support:"NH65 dense. No gap. Hospitals: Choutuppal govt hospital; 1033; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Hayathnagar","Regroup","10","20 min","5"],["Choutuppal","Food + lake","38","45 min","45"]],
back:[["Choutuppal → Hayathnagar → Saroornagar","Return cruise","48","60 min","10"]],
budget:{food:450,toll:50,park:50,entry:0},
safety:"Service-lane discipline at eateries; headcount before rolling.",
src:["Google Maps routing"]},
{n:21,name:"Nagarjuna Sagar — Vijay Vihar",dest:"Nagarjuna Sagar Dam + Ethipothala, Nalgonda",lat:16.575,lon:79.312,zoom:8,
oneWay:155,total:330,ride:"~6.5 hrs riding + sightseeing",dur:"1 night / 2 days",durKey:"1n",
roads:"NH65 (Sagar Rd); good highway, some town bottlenecks (Miryalaguda bypass where signed)",
terrain:"Good highway + paved dam roads",diff:"Moderate",cat:["scenic","long","heritage"],
depart:"05:00 Day 1",back:"19:00 Day 2 (or 18:00 same-day only if experienced pair, not advised)",season:"Oct–Feb (gates/crests + museum); monsoon dam views grand but wet",
warn:"Long day if attempted single-day — prefer overnight; dam security zones; ghat-ish dam approach; monkeys.",
tolls:"NH toll segments (verify bike rule)",
desc:"The great dam pilgrimage: Ethipothala falls, dam viewpoint, museum, and island fort by launch.",
attract:"Nagarjuna Sagar Dam viewpoint; Ethipothala Waterfall; Nagarjunakonda museum/island (boat, time-boxed); Vijay Vihar viewpoint.",
foodB:"Day 1: Choutuppal/Nakrekal tiffins — ₹150–300.",
foodL:"Haritha Vijay Vihar (TSTDC, Nagarjuna Sagar — verified) — ₹300–550 — verify; or dam-town meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Choutuppal (~45 km)","45 km"],["Nakrekal (~110 km) mandatory","65 km further"],["Sagar town top-up before return","~45 km further"]],
support:"NH65 corridor workshops (Choutuppal, Nakrekal, Miryalaguda turn). Dam township basic. Hospitals: Miryalaguda/Nagarjuna Sagar govt hospital; 108/112.",
route:[["Saroornagar start","Fuel, Day-1 briefing","0","—","15"],["Choutuppal","Breakfast + fuel","45","55 min","25"],["Nakrekal","Tea + fuel (mandatory)","65","75 min","15"],["Ethipothala → Sagar viewpoint","Falls + dam photos","45","60 min","60"],["Haritha Vijay Vihar halt","Overnight / rest + museum slot","5","10 min","—"]],
back:[["Sagar → Nakrekal","Morning start 07:00; fuel","110","2 hrs","20"],["Nakrekal → Choutuppal → Saroornagar","Cruise; lunch at Choutuppal","110","2 hrs","40"]],
budget:{food:1400,toll:150,park:200,entry:400},
safety:"No same-day heroics with pillion in summer; dam-zone: obey CISF/police boards; boats only authorised launches.",
src:["TSTDC Haritha Vijay Vihar","Telangana Tourism — Nagarjuna Sagar/Ethipothala","Google Maps routing"]},
{n:22,name:"Gadwal Fort & Jurala Dam (2-Day)",dest:"Jurala Dam (Priyadarshini) + Gadwal Fort, Jogulamba Gadwal",lat:16.328,lon:77.708,zoom:8,
oneWay:200,total:410,ride:"~8.5 hrs riding over 2 days + fort/dam",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 (Bangalore Hwy) via Shadnagar/Jadcherla + Gadwal–Jurala rural Rd; fast highway then paved 2-lane",
terrain:"Good highway + flat rural paved",diff:"Challenging",cat:["long","heritage","scenic"],
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Oct–Feb; Krishna gates view best post-monsoon (from designated points only)",
warn:"Long highway day + Krishna riverside heat; dam restricted zones — designated viewpoints only; Gadwal fort ruins — authorised areas, carry water.",
tolls:"NH tolls (verify)",
desc:"South-Telangana overnighter: Gadwal's hill fort and handloom town plus the Priyadarshini (Jurala) dam across the Krishna.",
attract:"Gadwal Fort ramparts + town handloom outlets; Jurala Dam viewpoint + Krishna riverside; Nettempadu lift (from road, verify).",
foodB:"Day 1: Shadnagar/Jadcherla highway tiffins — ₹150–300.",
foodL:"Gadwal town meals (verify) — ₹250–450; Day 2: Jadcherla meals on return.",
fuel:[["Start FULL Saroornagar","0 km"],["Shadnagar (~55 km)","55 km"],["Jadcherla (~40 km further) MANDATORY full","40 km"],["Gadwal top-up before Jurala leg","~45 km, verify pumps"]],
support:"NH44 corridor dense (Shadnagar–Jadcherla–Gadwal). Jurala spur basic — plan accordingly. Hospitals: Gadwal area hospital; 108/112.",
route:[["Saroornagar start","Fuel + long-ride briefing","0","—","15"],["Shadnagar","Breakfast + fuel","55","1h10","25"],["Jadcherla","MANDATORY fuel + regroup","40","50 min","15"],["Gadwal Fort","Fort walk + town lunch","45","1h10","90"],["Gadwal → Jurala Dam","Rural cruise + dam viewpoint + overnight","25","40 min","—"]],
back:[["Jurala → Gadwal → Jadcherla","Early start; fuel Jadcherla","70","1h40","20"],["Jadcherla → Saroornagar","Cruise via Shadnagar","95","2h","25"]],
budget:{food:1500,toll:250,park:200,entry:200},
safety:"Dam: fenced viewpoints only; highway: headlights on, no halts except bays; fort ruins: watch footing, daylight only.",
src:["Telangana Tourism — Gadwal/Jogulamba Gadwal","Irrigation Dept — Priyadarshini (Jurala) project notices","Google Maps routing"]},
{n:23,name:"Amrabad — Farahabad Viewpoint",dest:"Farahabad / Octopus Viewpoint, Amrabad Tiger Reserve",lat:16.27,lon:78.86,zoom:9,
oneWay:165,total:350,ride:"~7 hrs riding + forest halts",dur:"1 night / 2 days",durKey:"1n",
roads:"NH765 forest highway; paved, winding, patrol-sensitive",
terrain:"Paved ghat + forest",diff:"Challenging",cat:["scenic","adventure","long"],
depart:"05:00 Day 1",back:"18:00 Day 2 (or long full-day for experts)",season:"Oct–Mar",
warn:"Tiger reserve rules: stay on highway, no off-trail riding, no night transit (verify timings), fuel gap as per Gadwal–Jurala trip.",
tolls:"Minimal (verify)",
desc:"Forest-immersion ride without the temple queue: viewpoints, jungle air, and total night-sky darkness at Farahabad.",
attract:"Octopus/Farahabad viewpoint; Mannanur interpretation centre (check); Mallela Theertham gate (time-boxed).",
foodB:"Kalwakurthy tiffins.",
foodL:"Mannanur meals / packed (verify) — forest eateries limited.",
fuel:[["Start FULL","0 km"],["Kalwakurthy (~80 km)","80 km"],["Mannanur (~150 km) MANDATORY","70 km further"]],
support:"Forest stretches have no verified mechanic — plan accordingly. Hospitals: Amrabad PHC/Mannanur + 108.",
route:[["Saroornagar start","Fuel + briefing","0","—","15"],["Kalwakurthy","Breakfast + fuel","80","1h45","25"],["Mannanur","Fuel MANDATORY + water","70","1h30","20"],["Farahabad viewpoint circuit","Viewpoints + photos","20","45 min","60"]],
back:[["Farahabad → Mannanur","Fuel","20","45 min","10"],["Mannanur → Saroornagar","Return","150","3h15","30"]],
budget:{food:1200,toll:100,park:150,entry:200},
safety:"No drones in reserve; no littering; U-turns only at bays; monsoon: falling branches.",
src:["Amrabad Tiger Reserve notices","Google Maps routing"]},
{n:24,name:"Medak Cathedral & Fort",dest:"Medak Cathedral + Medak Fort, Medak",lat:18.046,lon:78.265,zoom:9,
oneWay:150,total:315,ride:"~6 hrs riding + sightseeing",dur:"Full day",durKey:"full",
roads:"NH65 → NH44 → Medak Rd (SH); good highway then 2-lane",
terrain:"Paved road, rolling",diff:"Moderate",cat:["heritage","scenic","long"],
depart:"05:00",back:"19:00",season:"Oct–Mar",
warn:"Fort climb needs time + water; cathedral service timings; town one-ways.",
tolls:"NH segments (verify)",
desc:"Northwest heritage giant: one of India's largest churches + a Kakatiya hill fort in one day.",
attract:"Medak Cathedral (Church of South India); Medak Fort trek-view; town lake.",
foodB:"Sangareddy tiffins en route (verified clusters) — ₹150–300.",
foodL:"Medak town meals (verify) — ₹250–450.",
fuel:[["Start FULL","0 km"],["Sangareddy (~105 km) mandatory","105 km"],["Medak town top-up","~45 km further"]],
support:"Sangareddy + Medak clusters. Gap: Sangareddy–Medak mid sparse — plan accordingly. Hospitals: Medak govt hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Sangareddy","Breakfast + MANDATORY fuel","105","2h15","30"],["Sangareddy → Medak","Rural highway","45","60 min","10"],["Cathedral + Fort","Sightseeing (2.5–3 hrs)","5","15 min","160"]],
back:[["Medak → Sangareddy","Tea + fuel","45","60 min","20"],["Sangareddy → Saroornagar","Cruise","105","2h15","10"]],
budget:{food:800,toll:100,park:150,entry:100},
safety:"Fort rock: grip footwear; descend before 4 PM; cathedral: modest dress + silence.",
src:["Telangana Tourism — Medak","Diocese visitor info (verify)","Google Maps routing"]},
{n:25,name:"Pocharam Dam & Sanctuary Edge",dest:"Pocharam Dam + Wildlife Sanctuary edge, Medak",lat:18.137,lon:78.203,zoom:9,
oneWay:132,total:280,ride:"~5.5 hrs riding + dam halt",dur:"Full day",durKey:"full",
roads:"NH65/NH44 + Medak–Pocharam Rd; highway then rural paved",
terrain:"Paved road + sanctuary-edge gravel (stay on paved)",diff:"Moderate",cat:["scenic","adventure"],
depart:"05:00",back:"18:30",season:"Aug–Feb (dam full; winter birds)",
warn:"Sanctuary: no off-track riding; dam restricted zones; water-release days — obey boards.",
tolls:"NH segments (verify)",
desc:"Quiet-water alternative to the famous dams: bund views, birdlife, and empty approach roads.",
attract:"Pocharam Dam viewpoint; sanctuary-edge birding (from road/authorized points); Medak add-on possible.",
foodB:"Sangareddy tiffins.",
foodL:"Medak/Pocharam-town meals or packed (verify) — options thin near dam.",
fuel:[["Start FULL","0 km"],["Sangareddy (~105 km) mandatory","105 km"],["Pocharam spur top-up if available, else carry plan","~30 km"]],
support:"Sangareddy last dense cluster; dam spur sparse — 'No verified roadside mechanic found at this section — plan accordingly.' Hospitals: Medak hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Sangareddy","Breakfast + fuel","105","2h15","30"],["Pocharam Dam","Bund viewpoint + rest","30","50 min","60"]],
back:[["Dam → Sangareddy","Fuel + tea","30","50 min","20"],["Sangareddy → Saroornagar","Cruise","105","2h15","10"]],
budget:{food:750,toll:100,park:100,entry:50},
safety:"Dam: no swimming; sanctuary: no feeding wildlife; dusk exit — animals on road.",
src:["Irrigation / Forest Dept — Pocharam","Google Maps routing"]},
{n:26,name:"Siddipet — Komati Cheruvu",dest:"Komati Cheruvu + Ranganayaka Temple, Siddipet",lat:18.102,lon:78.852,zoom:9,
oneWay:145,total:300,ride:"~6 hrs riding + lake",dur:"Full day",durKey:"full",
roads:"NH65 → Siddipet Rd (SH/Rajiv Rahadari links); good highway then 4/2-lane",
terrain:"Paved road, good highway mix",diff:"Moderate",cat:["scenic","heritage"],
depart:"05:00",back:"19:00",season:"Oct–Mar",
warn:"Town traffic + new flyover works (verify diversions); lake promenade evening crowds.",
tolls:"Possible segments (verify)",
desc:"Showcase-town ride: redeveloped lakefront, hanging bridge views, and temple stop.",
attract:"Komati Cheruvu lakefront; Ranganayaka (Lakshmi Narayana) Temple; town food.",
foodB:"Toopran/Gajwel tiffins en route (verified clusters) — ₹150–300.",
foodL:"Siddipet town meals (verify) — ₹250–450.",
fuel:[["Start FULL","0 km"],["Toopran (~95 km)","95 km"],["Siddipet top-up","~50 km further"]],
support:"Rajiv Rahadari corridor dense (Kompally–Toopran–Gajwel–Siddipet). No major gap. Hospitals: Siddipet govt hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Toopran","Breakfast + fuel","95","2h","25"],["Toopran → Siddipet","Cruise","50","60 min","10"],["Komati Cheruvu + Temple","Lake + darshan","5","15 min","90"]],
back:[["Siddipet → Toopran","Tea + fuel","50","60 min","20"],["Toopran → Saroornagar","Cruise","95","2h","10"]],
budget:{food:800,toll:100,park:100,entry:50},
safety:"Lakefront: designated parking only; no bund-edge stunts.",
src:["Siddipet district / lakefront notices","Google Maps routing"]},
{n:27,name:"Karimnagar — Lower Manair Dam",dest:"Lower Manair Dam + Ujjwala Park, Karimnagar",lat:18.438,lon:79.128,zoom:9,
oneWay:170,total:355,ride:"~7 hrs riding + dam",dur:"1 night / 2 days",durKey:"1n",
roads:"Rajiv Rahadari (SH1) via Siddipet; fast 2/4-lane highway",
terrain:"Good highway + paved dam roads",diff:"Moderate",cat:["long","scenic"],
depart:"05:00 Day 1",back:"19:00 Day 2 (long full-day possible for experts)",season:"Aug–Feb",
warn:"Highway speeds + median gaps; dam security zones; summer heat on return.",
tolls:"State highway tolls where posted (verify)",
desc:"Manair waters + Karimnagar food: a proper north-Telangana overnighter on the great Rahadari.",
attract:"Lower Manair Dam viewpoint; Ujjwala Park; Karimnagar food strip.",
foodB:"Day 1: Siddipet tiffins.",
foodL:"Karimnagar meals (verify; local special: Karimnagar-style biryani/dosa clusters) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Siddipet (~145 km) mandatory","145 km"],["Karimnagar top-up","~30 km further"]],
support:"Rahadari dense (Siddipet–Karimnagar). No major gap. Hospitals: Karimnagar govt hospital; 108/112.",
route:[["Saroornagar start","Fuel + briefing","0","—","15"],["Siddipet","Breakfast + MANDATORY fuel","145","3h","30"],["Siddipet → Karimnagar","Cruise","30","40 min","10"],["LMD + Ujjwala Park","Dam + park","8","20 min","75"]],
back:[["Karimnagar → Siddipet","Morning fuel + tea","30","40 min","20"],["Siddipet → Saroornagar","Cruise; lunch Siddipet","145","3h","30"]],
budget:{food:1400,toll:100,park:150,entry:150},
safety:"Rahadari: no night overtakes on undivided links; reflective gear after dusk.",
src:["Irrigation Dept — LMD","Google Maps routing"]},
{n:28,name:"Vemulawada Rajarajeshwara Temple",dest:"Rajarajeshwara Temple, Vemulawada (Rajanna Sircilla)",lat:18.468,lon:78.863,zoom:9,
oneWay:185,total:385,ride:"~7.5 hrs riding + darshan",dur:"1 night / 2 days",durKey:"1n",
roads:"Rajiv Rahadari + Vemulawada Rd; highway then temple-town 2-lane",
terrain:"Paved road",diff:"Moderate",cat:["heritage","long"],
depart:"04:30 Day 1",back:"19:30 Day 2",season:"All year; Shivaratri/Maha Shivaratri peak — avoid unless planned",
warn:"Major pilgrim crowds on holy days; queue discipline; town parking formal.",
tolls:"State tolls where posted (verify)",
desc:"Dakshin Kashi ride: ancient Shiva temple, kode mokku custom, and temple-town prasadam.",
attract:"Rajarajeshwara Temple darshan; town tanks; Karimnagar add-on.",
foodB:"Siddipet tiffins.",
foodL:"Vemulawada temple-town meals (verify) — ₹250–450.",
fuel:[["Start FULL","0 km"],["Siddipet (~145 km) mandatory","145 km"],["Vemulawada top-up","~45 km further"]],
support:"Rahadari dense; temple town workshops basic. Hospitals: Vemulawada govt hospital / Sircilla; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Siddipet","Breakfast + fuel","145","3h","30"],["Siddipet → Vemulawada","Temple approach","45","60 min","10"],["Temple","Darshan + rest","2","10 min","120"]],
back:[["Vemulawada → Siddipet","Fuel + tea","45","60 min","20"],["Siddipet → Saroornagar","Cruise","145","3h","30"]],
budget:{food:1400,toll:100,park:150,entry:100},
safety:"Festival days: go overnight + pre-book stay; secure helmets in cloak rooms only where allowed.",
src:["Endowments — Vemulawada","Google Maps routing"]},
{n:29,name:"Basara Saraswati Temple (North Push)",dest:"Gnana Saraswati Temple, Basara (Nirmal)",lat:18.877,lon:77.955,zoom:8,
oneWay:215,total:450,ride:"~9 hrs riding + darshan",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 + Nizamabad–Basara Rd; highway then Godavari-belt 2-lane",
terrain:"Good highway + paved rural",diff:"Challenging",cat:["long","heritage"],
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Mar; Akshara Abhyasam season crowded",
warn:"Very long north push; Godavari bathing ghats — no risky dips; temple-town queues.",
tolls:"NH tolls (verify bike rule)",
desc:"Goddess-of-learning pilgrimage to the Godavari banks — the longest pure-heritage run in this book.",
attract:"Gnana Saraswati Temple; Godavari ghat viewpoint; Vyasa Gufa (verify access).",
foodB:"Day 1: Nizamabad bypass tiffins (verify) — ₹150–300.",
foodL:"Basara temple-town meals (verify) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Nizamabad (~180 km) MANDATORY","180 km"],["Basara (~35 km further) top-up","35 km"]],
support:"NH44 dense to Nizamabad; Basara spur basic — plan accordingly. Hospitals: Nizamabad/Basara PHC; 108/112.",
route:[["Saroornagar start","Fuel + briefing","0","—","15"],["Nizamabad bypass","Breakfast + MANDATORY fuel","180","3h45","30"],["Nizamabad → Basara","Godavari belt cruise","35","50 min","10"],["Basara Temple + ghat","Darshan + rest","2","10 min","120"]],
back:[["Basara → Nizamabad","Fuel + tea","35","50 min","20"],["Nizamabad → Saroornagar","Cruise; lunch Nizamabad","180","3h45","30"]],
budget:{food:1500,toll:200,park:150,entry:100},
safety:"Fatigue management: 2-hour halt rule; no night Godavari-belt riding for first-timers.",
src:["Endowments — Basara","Google Maps routing"]},
{n:30,name:"Nizamabad Fort & Alisagar",dest:"Nizamabad Fort + Alisagar Reservoir, Nizamabad",lat:18.672,lon:78.094,zoom:9,
oneWay:180,total:375,ride:"~7.5 hrs riding + fort",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 (Nagpur Hwy); fast divided highway most of way",
terrain:"Good highway + paved town roads",diff:"Moderate",cat:["long","heritage","scenic"],
depart:"05:00 Day 1",back:"19:00 Day 2",season:"Oct–Mar",
warn:"NH44 speed + truck discipline; fort hill heat; reservoir bund rules.",
tolls:"NH tolls (verify)",
desc:"Highway-cruise overnighter: Quilla fort views + Alisagar gardens, with Nizamabad food.",
attract:"Nizamabad (Quilla) Fort; Alisagar Reservoir + gardens; town archaeology museum (verify).",
foodB:"Day 1: Kamareddy/Balkonda tiffins (verify clusters) — ₹150–300.",
foodL:"Nizamabad town meals (verify) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Kamareddy (~130 km) mandatory","130 km"],["Nizamabad top-up","~50 km further"]],
support:"NH44 dense. No major gap. Hospitals: Nizamabad govt hospital; 1033; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Kamareddy","Breakfast + MANDATORY fuel","130","2h45","30"],["Kamareddy → Nizamabad","Cruise","50","60 min","10"],["Fort + Alisagar","Sightseeing","10","20 min","120"]],
back:[["Nizamabad → Kamareddy","Fuel + tea","50","60 min","20"],["Kamareddy → Saroornagar","Cruise","130","2h45","20"]],
budget:{food:1400,toll:200,park:150,entry:100},
safety:"Fort: carry water; monkeys; finish climb before afternoon heat.",
src:["Telangana Tourism — Nizamabad","Google Maps routing"]},
{n:31,name:"Nirmal — Toys & Fort",dest:"Nirmal Toys centre + Nirmal Fort, Nirmal",lat:19.096,lon:78.343,zoom:8,
oneWay:210,total:440,ride:"~8.5 hrs riding + crafts",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 to Nirmal; fast highway, town approach paved",
terrain:"Good highway",diff:"Moderate",cat:["long","heritage"],
depart:"04:30 Day 1",back:"19:30 Day 2",season:"Oct–Mar",
warn:"Long highway day; craft-centre timings (verify); fort access local guidance.",
tolls:"NH tolls (verify)",
desc:"Craft-town ride: world-famous Nirmal toys + fort, with Kuntala extension option.",
attract:"Nirmal Toys (handicraft outlets); Nirmal Fort viewpoint; riverside halt.",
foodB:"Nizamabad/Kamareddy tiffins.",
foodL:"Nirmal town meals (verify) — ₹250–500.",
fuel:[["Start FULL","0","0 km"],["Kamareddy (~130 km) mandatory","130 km"],["Nirmal top-up (~80 km further)","80 km"]],
support:"NH44 dense. No major gap. Hospitals: Nirmal govt hospital; 1033; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Kamareddy","Breakfast + fuel","130","2h45","30"],["Kamareddy → Nirmal","Cruise","80","1h45","10"],["Nirmal crafts + fort","Explore","5","15 min","120"]],
back:[["Nirmal → Kamareddy","Fuel + tea","80","1h45","20"],["Kamareddy → Saroornagar","Cruise","130","2h45","20"]],
budget:{food:1400,toll:200,park:150,entry:100},
safety:"Handicraft buys: bungee them low and tight; no loose loads at highway speed.",
src:["Telangana Handicrafts — Nirmal","Google Maps routing"]},
{n:32,name:"Warangal — Thousand Pillar Temple",dest:"Thousand Pillar + Bhadrakali + Warangal Fort, Warangal",lat:17.978,lon:79.6,zoom:9,
oneWay:148,total:310,ride:"~6 hrs riding + heritage",dur:"Full day",durKey:"full",
roads:"NH65 (Warangal Hwy); good divided highway",
terrain:"Good highway + paved city",diff:"Moderate",cat:["heritage","long","food"],
depart:"04:30",back:"20:00",season:"Oct–Mar",
warn:"Long full-day — start early; city one-ways; fort/temple parking touts.",
tolls:"NH tolls (verify)",
desc:"Kakatiya capital in a day: three monuments, Warangal biryani, and big-highway rhythm.",
attract:"Thousand Pillar Temple; Bhadrakali Temple + lake; Warangal Fort + Kush Mahal.",
foodB:"Aler/Ghanpur tiffins en route (verify) — ₹150–300.",
foodL:"Warangal meals (verify; famous biryani/dosa clusters) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Aler (~70 km)","70 km"],["Warangal top-up","~78 km further"]],
support:"Warangal Hwy dense (Uppal–Ghatkesar–Aler–Warangal). No major gap. Hospitals: Warangal MGM/area hospitals; 1033; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Aler","Breakfast + fuel","70","1h20","25"],["Aler → Warangal","Cruise","78","1h40","10"],["Heritage triangle","Temples + fort (3 hrs)","10","25 min","180"]],
back:[["Warangal → Aler","Tea + fuel","78","1h40","20"],["Aler → Saroornagar","Cruise; dinner optional","70","1h20","10"]],
budget:{food:900,toll:150,park:150,entry:150},
safety:"City: single-file in old lanes; helmet locks; no monument climbing.",
src:["Telangana Tourism — Warangal","ASI/Endowments listings","Google Maps routing"]},
{n:33,name:"Ramappa Temple (UNESCO)",dest:"Ramappa (Rudreshwara) Temple, Palampet, Mulugu",lat:18.256,lon:79.947,zoom:9,
oneWay:205,total:430,ride:"~8.5 hrs riding + temple",dur:"1 night / 2 days",durKey:"1n",
roads:"NH65 + Warangal–Mulugu Rd; highway then rural 2-lane (final links can be patchy)",
terrain:"Good highway + paved rural, some poor patches",diff:"Challenging",cat:["long","heritage","adventure"],
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Mar",
warn:"UNESCO site discipline (no climbing/touching carvings); last rural links patchy + livestock; prefer overnight — not a relaxed day trip.",
tolls:"NH tolls (verify)",
desc:"The masterpiece ride: Kakatiya engineering marvel with floating-brick lore, Ramappa lake beside it.",
attract:"Ramappa Temple (UNESCO); Ramappa Lake viewpoint; Warangal add-on Day 2.",
foodB:"Day 1: Aler/Warangal tiffins.",
foodL:"Palampet/Warangal meals (verify; thin near temple — carry water/snacks) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Warangal (~148 km) MANDATORY","148 km"],["Palampet top-up (~65 km further)","65 km"]],
support:"Dense to Warangal; Mulugu–Palampet spur sparse — 'No verified roadside mechanic found at this section — plan accordingly.' Hospitals: Warangal/Mulugu; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Warangal","Breakfast + MANDATORY fuel","148","3h","30"],["Warangal → Palampet","Rural cruise","65","1h30","10"],["Ramappa Temple + lake","Darshan + lake (2 hrs)","2","10 min","120"]],
back:[["Palampet → Warangal","Fuel + tea","65","1h30","20"],["Warangal → Saroornagar","Cruise","148","3h","30"]],
budget:{food:1500,toll:200,park:150,entry:150},
safety:"Rural links: 50–60 km/h max; dust + sudden speed-breakers; temple: no drones without permission.",
src:["UNESCO — Kakatiya Rudreshwara","Telangana Tourism — Ramappa","Google Maps routing"]},
{n:34,name:"Laknavaram Lake (Suspension Bridge)",dest:"Laknavaram Lake + suspension bridges, Mulugu",lat:18.148,lon:79.959,zoom:9,
oneWay:195,total:410,ride:"~8 hrs riding + lake",dur:"1 night / 2 days",durKey:"1n",
roads:"NH65 + Warangal–Laknavaram Rd; highway then forest-fringe 2-lane",
terrain:"Paved road + forest fringe",diff:"Challenging",cat:["long","scenic","adventure"],
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Aug–Feb (lake full)",
warn:"Suspension bridges: weight/queue discipline; forest-fringe dusk animals; boating only authorised counters.",
tolls:"NH tolls (verify)",
desc:"Island-hopping by footbridges over green water — best paired with Ramappa as a 2-day double.",
attract:"Laknavaram suspension bridges; island viewpoints; Haritha cottages view (verify booking).",
foodB:"Warangal tiffins.",
foodL:"Haritha Laknavaram (TSTDC, verify) + Govindaraopet meals — ₹300–550.",
fuel:[["Start FULL","0 km"],["Warangal (~148 km) MANDATORY","148 km"],["Laknavaram top-up (~50 km further, verify pump)","50 km"]],
support:"Dense to Warangal; forest-fringe spur sparse — plan accordingly. Hospitals: Warangal/Mulugu; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Warangal","Breakfast + fuel","148","3h","30"],["Warangal → Laknavaram","Forest-fringe cruise","50","1h15","10"],["Laknavaram Lake","Bridges + islands (2 hrs)","2","10 min","120"]],
back:[["Laknavaram → Warangal","Fuel + tea","50","1h15","20"],["Warangal → Saroornagar","Cruise","148","3h","30"]],
budget:{food:1500,toll:200,park:150,entry:300},
safety:"Bridges: single-file, no jumping/overload; lake: life-jackets only on authorised boats.",
src:["TSTDC Haritha — Laknavaram","Telangana Tourism","Google Maps routing"]}
];
