/* Trips 101–150: north / west / remaining Telangana (third ring) */
window.TRIPS5 = [
{n:101,name:"Nizam Sagar Dam Ride",dest:"Nizam Sagar Dam + reservoir, Kamareddy",lat:18.47,lon:77.93,zoom:10,
oneWay:148,total:300,ride:"~6 hrs riding + dam",dur:"Full day",durKey:"full",
roads:"Medchal–Kamareddy Hwy (NH44) + dam link; highway then dam Rd",
terrain:"Good highway + dam bund",diff:"Moderate",cat:["lakes","scenic","food"],
district:"Kamareddy",
depart:"05:00",back:"20:00",season:"Aug–Feb (water); dam zones — designated points",
warn:"Nizam-era masonry dam — viewpoints only; bund discipline; long day fatigue.",
tolls:"NH tolls (verify)",
desc:"Deccan irrigation history: Nizam Sagar's arched masonry across the Manjira.",
attract:"Nizam Sagar dam wall + viewpoints (verify); reservoir bays; Kamareddy food.",
foodB:"Medchal-side tiffins (verify) — ₹100–250.",
foodL:"Kamareddy town meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Medchal (~35 km)","35 km"],["Kamareddy (~115 km further) MANDATORY","115 km"]],
support:"NH44 dense. Hospitals: Kamareddy area hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Medchal","Tea + fuel","35","45 min","15"],["Kamareddy → Nizam Sagar","Dam (1.5 hrs)","115","2h20","90"]],
back:[["Nizam Sagar → Kamareddy","Tea + fuel","15","25 min","20"],["Kamareddy → Saroornagar","Cruise","135","2h40","—"]],
budget:{food:750,toll:150,park:150,entry:50},
safety:"Dam water — no wading; masonry edges — railings only.",
src:["Irrigation Dept — Nizam Sagar notices","Google Maps routing"]},
{n:102,name:"Domakonda Fort Ride",dest:"Domakonda Fort + town, Kamareddy",lat:18.25,lon:77.42,zoom:10,
oneWay:130,total:265,ride:"~5.5 hrs riding + fort",dur:"Full day",durKey:"full",
roads:"Medchal–Kamareddy Hwy + Domakonda link; highway then rural paved",
terrain:"Paved road + fort hill",diff:"Moderate",cat:["forts","heritage","scenic"],
district:"Kamareddy",
depart:"05:00",season:"Oct–Mar",
warn:"Desai fort ruins — authorised areas; rural last-mile boards.",
tolls:"NH tolls (verify)",
desc:"Desai stronghold ride: Domakonda's fort-palace above Kamareddy plains.",
attract:"Domakonda Fort walls + palace remnants (verify); hill viewpoint; town halt.",
foodB:"Kamareddy tiffins (verify) — ₹150–300.",
foodL:"Domakonda/Kamareddy meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Kamareddy (~130 km) MANDATORY","130 km"]],
support:"NH44 dense; fort spur basic. Hospitals: Kamareddy; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Kamareddy","Breakfast + MANDATORY fuel","130","2h40","30"],["Domakonda Fort","Fort (1.5 hrs)","12","20 min","90"]],
back:[["Domakonda → Kamareddy","Tea + fuel","12","20 min","15"],["Kamareddy → Saroornagar","Cruise","130","2h40","—"]],
budget:{food:750,toll:150,park:100,entry:50},
safety:"Ruins — daylight only; old walls — keep distance.",
src:["Telangana Tourism — Domakonda","Google Maps routing"]},
{n:103,name:"Yellareddy Yellamma Temple",dest:"Renuka Yellamma Temple, Yellareddy (Kamareddy)",lat:18.08,lon:77.43,zoom:10,
oneWay:140,total:285,ride:"~5.8 hrs riding + temple",dur:"Full day",durKey:"full",
roads:"Medchal–Kamareddy Hwy + Yellareddy link; highway then town lanes",
terrain:"Good highway + town lanes",diff:"Easy",cat:["easy","temples","food"],
district:"Kamareddy",
depart:"05:00",back:"20:00",season:"Oct–Mar; jatara season crowds (verify)",
warn:"Jatara-season crowds (verify); town lanes slow.",
tolls:"NH tolls (verify)",
desc:"Shakti-peetha day ride: Yellareddy's Renuka temple plus highway dhabas.",
attract:"Yellamma temple complex; temple tank; Kamareddy food halt.",
foodB:"Kamareddy-side tiffins (verify) — ₹100–250.",
foodL:"Yellareddy town meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Kamareddy (~130 km) MANDATORY","130 km"]],
support:"NH44 dense. Hospitals: Kamareddy/Yellareddy; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Kamareddy","Breakfast + fuel","130","2h40","25"],["Yellareddy","Temple (1 hr)","10","20 min","60"]],
back:[["Yellareddy → Kamareddy","Tea + fuel","10","20 min","15"],["Kamareddy → Saroornagar","Cruise","130","2h40","—"]],
budget:{food:750,toll:150,park:100,entry:0},
safety:"Festival days — early arrival; town lanes walking pace.",
src:["Telangana Tourism — Yellareddy","Google Maps routing"]},
{n:104,name:"Dichpally Ramalayam Hill",dest:"Khilla Ramalayam hill temple, Dichpally (Nizamabad)",lat:18.58,lon:78.23,zoom:10,
oneWay:175,total:355,ride:"~7 hrs riding + hill",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 (Nizamabad Hwy) + Dichpally hill link; highway then hill Rd",
terrain:"Good highway + hill climb",diff:"Moderate",cat:["temples","hills","long"],
district:"Nizamabad",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Oct–Mar",
warn:"Black-basalt hill steps — footwear + water; fort-hill (Khilla) lanes.",
tolls:"NH tolls (verify)",
desc:"Khilla Ramalayam: whitewashed Rama temple atop Dichpally's basalt hill.",
attract:"Dichpally hill temple; Khilla viewpoint; Nizamabad food.",
foodB:"Day 1: Kamareddy tiffins.",
foodL:"Dichpally/Nizamabad meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Kamareddy (~130 km) MANDATORY","130 km"],["Nizamabad top-up","~45 km further"]],
support:"NH44 dense. Hospitals: Nizamabad; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Kamareddy","Breakfast + fuel","130","2h40","30"],["Dichpally hill","Climb + temple","45","1h","90"]],
back:[["Dichpally → Nizamabad → Kamareddy","Fuel Kamareddy","90","1h50","20"],["Kamareddy → Saroornagar","Cruise","130","2h40","—"]],
budget:{food:1200,toll:200,park:150,entry:50},
safety:"Basalt steps slippery when wet; hill after dark avoided.",
src:["Telangana Tourism — Dichpally","Google Maps routing"]},
{n:105,name:"Armoor Hill Temple Ride",dest:"Navanatha Siddeshwara hill, Armoor (Nizamabad)",lat:18.79,lon:78.28,zoom:10,
oneWay:190,total:385,ride:"~7.5 hrs riding + hill",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 + Armoor fort-hill link; highway then hill Rd",
terrain:"Good highway + fort hill",diff:"Moderate",cat:["temples","forts","long","scenic"],
district:"Nizamabad",
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Mar",
warn:"Fort-hill climb + old walls — authorised areas; Armoor town lanes.",
tolls:"NH tolls (verify)",
desc:"Fort-hill Shiva: Armoor's Siddeshwara above the town with Nizamabad views.",
attract:"Armoor hill temple + fort remnants (verify); viewpoint; town food.",
foodB:"Day 1: Kamareddy tiffins.",
foodL:"Armoor/Nizamabad meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Kamareddy (~130 km) MANDATORY","130 km"],["Armoor top-up (verify)","~60 km further"]],
support:"NH44 dense; hill spur basic. Hospitals: Nizamabad/Armoor; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Kamareddy","Breakfast + MANDATORY fuel","130","2h40","30"],["Armoor hill","Climb + temple","60","1h15","120"]],
back:[["Armoor → Kamareddy","Tea + fuel","60","1h15","20"],["Kamareddy → Saroornagar","Cruise","130","2h40","—"]],
budget:{food:1300,toll:200,park:150,entry:50},
safety:"Fort hill — daylight only; old walls — keep distance.",
src:["Telangana Tourism — Armoor","Google Maps routing"]},
{n:106,name:"Kadem Dam Expedition",dest:"Kadem (Kaddam) Dam + reservoir, Nirmal",lat:19.10,lon:78.33,zoom:9,
oneWay:250,total:505,ride:"~10 hrs riding over 2 days + dam",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 (Adilabad Hwy) + Kadem link; long highway + dam Rd",
terrain:"Good highway + dam bund",diff:"Challenging",cat:["long","lakes","scenic"],
district:"Nirmal",
depart:"04:00 Day 1",back:"21:00 Day 2",season:"Aug–Feb (water)",
warn:"Very long day + dam zones — designated points; Adilabad-Hwy truck traffic.",
tolls:"NH tolls (verify)",
desc:"North-dam run: Kadem's gates and reservoir with Nirmal-town crafts.",
attract:"Kadem dam wall + viewpoints (verify); reservoir bays; Nirmal toys halt.",
foodB:"Day 1: Nirmal tiffins.",
foodL:"Kadem/Nirmal meals (verify) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Nirmal (~210 km) MANDATORY","210 km"],["Kadem top-up (verify)","~40 km further"]],
support:"NH44 dense to Nirmal; dam spur basic. Hospitals: Nirmal; 108/112.",
route:[["Saroornagar start","Fuel + long-ride briefing","0","—","15"],["Nirmal","Breakfast + MANDATORY fuel","210","4h","30"],["Kadem Dam","Dam (1.5 hrs)","40","55 min","90"]],
back:[["Kadem → Nirmal","Tea + fuel","40","55 min","20"],["Nirmal → Saroornagar","Cruise","210","4h","—"]],
budget:{food:1500,toll:200,park:200,entry:100},
safety:"505-km weekend — fatigue plan; dam water — no wading.",
src:["Irrigation Dept — Kadem notices","Google Maps routing"]},
{n:107,name:"Pochera Waterfall Trek",dest:"Pochera Waterfall, Adilabad",lat:19.32,lon:78.55,zoom:9,
oneWay:280,total:565,ride:"~11 hrs riding over 2–3 days + falls",dur:"2 nights / 3 days",durKey:"2n",
roads:"NH44 + Adilabad–Pochera forest Rd; long highway then forest 2-lane + trek",
terrain:"Highway + forest + rocky trek on foot",diff:"Challenging",cat:["long","waterfalls","adventure"],
district:"Adilabad",
depart:"04:00 Day 1",back:"21:00 Day 3",season:"Aug–Dec (falls alive); summer trickle — skip",
warn:"Remote forest falls — guide (verify), rocks lethal when wet, network patchy; carries: water, food, rain layer.",
tolls:"NH tolls (verify)",
desc:"Far-north cascade: Pochera's basalt tiers after a forest ride and short trek.",
attract:"Pochera tiers + base pool (verify access); forest drive; Adilabad food.",
foodB:"Day 1: Nirmal/Adilabad tiffins.",
foodL:"Pochera/Adilabad meals (verify; carry backup) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Nirmal (~210 km) MANDATORY","210 km"],["Adilabad top-up MANDATORY","~70 km further"]],
support:"Dense to Adilabad; forest tail sparse. Hospitals: Adilabad; 108/112.",
route:[["Saroornagar start","Fuel + remote briefing","0","—","15"],["Nirmal","Breakfast + fuel","210","4h","30"],["Adilabad → Pochera","Forest + trek","70","1h45","150"]],
back:[["Pochera → Adilabad → Nirmal","Fuel Nirmal","140","3h","25"],["Nirmal → Saroornagar","Cruise","210","4h","—"]],
budget:{food:1800,toll:250,park:200,entry:200},
safety:"Falls: fenced viewpoints only; forest daylight only; multi-day fatigue plan.",
src:["Telangana Tourism — Pochera","Google Maps routing"]},
{n:108,name:"Jainath Temple Cluster",dest:"Jainath temple complex, Adilabad",lat:19.55,lon:78.56,zoom:9,
oneWay:290,total:585,ride:"~11 hrs riding over 2–3 days + temples",dur:"2 nights / 3 days",durKey:"2n",
roads:"NH44 + Adilabad–Jainath link; long highway + town lanes",
terrain:"Good highway + old-town lanes",diff:"Moderate",cat:["long","temples","heritage"],
district:"Adilabad",
depart:"04:00 Day 1",back:"21:00 Day 3",season:"Oct–Mar",
warn:"Very long highway days; old-town lanes slow; temple-town festival calendar (verify).",
tolls:"NH tolls (verify)",
desc:"Far-north temple town: Jainath's old Shiva–Vishnu complexes plus Adilabad food.",
attract:"Jainath temple street; old-town architecture; Adilabad markets.",
foodB:"Day 1: Nirmal tiffins.",
foodL:"Jainath/Adilabad meals (verify) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Nirmal (~210 km) MANDATORY","210 km"],["Adilabad MANDATORY top-up","~80 km further"]],
support:"NH44 dense. Hospitals: Adilabad; 108/112.",
route:[["Saroornagar start","Fuel + long-ride briefing","0","—","15"],["Nirmal","Breakfast + fuel","210","4h","30"],["Adilabad → Jainath","Temples (2 hrs)","80","1h40","120"]],
back:[["Jainath → Adilabad → Nirmal","Fuel Nirmal","150","3h","25"],["Nirmal → Saroornagar","Cruise","210","4h","—"]],
budget:{food:1800,toll:250,park:200,entry:100},
safety:"585-km weekend — two-night plan; highway trucks — daylight, no tailgating.",
src:["Telangana Tourism — Jainath","Google Maps routing"]},
{n:109,name:"Utnoor Tribal Heartland",dest:"Utnoor tribal town + forest edge, Adilabad",lat:19.37,lon:78.77,zoom:9,
oneWay:300,total:605,ride:"~12 hrs riding over 2–3 days + culture",dur:"2 nights / 3 days",durKey:"2n",
roads:"NH44 + Utnoor tribal-belt Rd; long highway + forest 2-lane",
terrain:"Highway + forest edge",diff:"Challenging",cat:["long","scenic","adventure"],
district:"Adilabad",
depart:"04:00 Day 1",back:"21:00 Day 3",season:"Oct–Feb",
warn:"Remote tribal belt — cultural sensitivity, permits where signed (verify); network patchy; fuel discipline.",
tolls:"NH tolls (verify)",
desc:"Gond-country ride: Utnoor's tribal museum, weekly bazaar and teak forests.",
attract:"Utnoor tribal museum (verify); bazaar day (verify); forest-edge viewpoints.",
foodB:"Day 1: Nirmal tiffins.",
foodL:"Utnoor/Adilabad meals (verify; carry backup) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Nirmal (~210 km) MANDATORY","210 km"],["Utnoor top-up (verify) MANDATORY","~90 km further"]],
support:"Dense to Nirmal; tribal belt sparse. Hospitals: Utnoor PHC/Adilabad; 108/112.",
route:[["Saroornagar start","Fuel + remote briefing","0","—","15"],["Nirmal","Breakfast + MANDATORY fuel","210","4h","30"],["Utnoor","Museum + bazaar","90","2h","150"]],
back:[["Utnoor → Nirmal","Early start; fuel","90","2h","20"],["Nirmal → Saroornagar","Cruise","210","4h","—"]],
budget:{food:1800,toll:250,park:200,entry:100},
safety:"Cultural respect — ask before photos; forest daylight only; multi-day plan.",
src:["Telangana Tourism — Utnoor","Google Maps routing"]},
{n:110,name:"Jodeghat Memorial Valley",dest:"Komaram Bheem memorial, Jodeghat (Kumuram Bheem Asifabad)",lat:19.28,lon:79.88,zoom:9,
oneWay:300,total:610,ride:"~12 hrs riding over 2–3 days + valley",dur:"2 nights / 3 days",durKey:"2n",
roads:"Nagpur Hwy (NH44/NH63) + Jodeghat valley link; very long highway + forest tail",
terrain:"Highway + forest valley",diff:"Challenging",cat:["long","heritage","scenic"],
district:"Kumuram Bheem Asifabad",
depart:"04:00 Day 1",back:"21:00 Day 3",season:"Oct–Feb; Adivasi Day events (verify)",
warn:"Longest Telangana run — three-day discipline; valley memorial — solemn site rules; forest tail fuel.",
tolls:"NH tolls (verify)",
desc:"Pilgrimage to Jal–Jungle–Zameen: Jodeghat's memorial valley in the Gond hills.",
attract:"Jodeghat memorial + museum (verify); valley viewpoints; tribal hamlets (respect).",
foodB:"Day 1: Nirmal tiffins.",
foodL:"Asifabad/Jodeghat meals (verify; carry backup) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Nirmal (~210 km) MANDATORY","210 km"],["Asifabad top-up MANDATORY","~90 km further"]],
support:"Dense to Nirmal/Asifabad; valley tail sparse. Hospitals: Asifabad; 108/112.",
route:[["Saroornagar start","Fuel + expedition briefing","0","—","15"],["Nirmal","Breakfast + MANDATORY fuel","210","4h","30"],["Asifabad → Jodeghat","Valley + memorial","90","2h","150"]],
back:[["Jodeghat → Asifabad → Nirmal","Fuel Nirmal","180","3h40","25"],["Nirmal → Saroornagar","Cruise","210","4h","—"]],
budget:{food:1800,toll:250,park:200,entry:100},
safety:"610-km expedition — pillion/luggage slow; memorial solemnity; forest daylight.",
src:["Telangana Tourism — Jodeghat","Google Maps routing"]},
{n:111,name:"Kawal Tiger Reserve Edge",dest:"Kawal Tiger Reserve gate (Jannaram), Mancherial",lat:19.10,lon:78.65,zoom:9,
oneWay:260,total:525,ride:"~10.5 hrs riding over 2 days + forest",dur:"2 nights / 3 days",durKey:"2n",
roads:"Karimnagar–Mancherial Hwy + Jannaram forest Rd; long highway + forest 2-lane",
terrain:"Highway + tiger-reserve buffer",diff:"Challenging",cat:["long","wildlife","adventure"],
district:"Mancherial",
depart:"04:00 Day 1",back:"21:00 Day 2",season:"Oct–Feb; safari/entry permits — verify at gate",
warn:"Tiger reserve buffer — permits, guides and timings absolute (verify); no halts except bays; no night forest transit.",
tolls:"State tolls (verify)",
desc:"Big-cat buffer ride: Kawal's teak forests from the Jannaram gate.",
attract:"Kawal gate + interpretation (verify); buffer viewpoints; Kadam river banks (verify).",
foodB:"Day 1: Karimnagar tiffins.",
foodL:"Jannaram/Mancherial meals (verify; carry backup) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"],["Mancherial top-up MANDATORY","~75 km further"]],
support:"Dense to Mancherial; buffer sparse. Hospitals: Mancherial; 108/112.",
route:[["Saroornagar start","Fuel + forest briefing","0","—","15"],["Karimnagar","Breakfast + MANDATORY fuel","165","3h20","30"],["Mancherial → Kawal gate","Buffer + viewpoints","95","2h","150"]],
back:[["Kawal → Mancherial → Karimnagar","Fuel Karimnagar","170","3h30","25"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1700,toll:200,park:200,entry:250},
safety:"Reserve rules absolute — guide, daylight, silence; elephant/sign boards real.",
src:["Telangana Forest Dept — Kawal","Google Maps routing"]},
{n:112,name:"Yellampalli Dam Ride",dest:"Sripada Yellampalli Dam + reservoir, Mancherial",lat:18.75,lon:79.48,zoom:9,
oneWay:230,total:465,ride:"~9 hrs riding over 2 days + dam",dur:"1 night / 2 days",durKey:"1n",
roads:"Karimnagar–Ramagundam Hwy + dam link; long highway + dam Rd",
terrain:"Good highway + dam bund",diff:"Moderate",cat:["long","lakes","scenic"],
district:"Mancherial",
depart:"04:30 Day 1",back:"20:30 Day 2",season:"Aug–Feb",
warn:"Dam zones — designated points; coal-belt trucks on Ramagundam corridor.",
tolls:"State tolls (verify)",
desc:"Godavari barrage run: Yellampalli's gates with Ramagundam riverfront.",
attract:"Yellampalli dam viewpoints (verify); reservoir bays; Ramagundam riverfront.",
foodB:"Day 1: Karimnagar tiffins.",
foodL:"Ramagundam/Mancherial meals (verify) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"],["Ramagundam top-up","~65 km further"]],
support:"Highway dense. Hospitals: Ramagundam/Mancherial; 108/112.",
route:[["Saroornagar start","Fuel + long-ride briefing","0","—","15"],["Karimnagar","Breakfast + MANDATORY fuel","165","3h20","30"],["Ramagundam → Yellampalli","Dam (1.5 hrs)","65","1h20","90"]],
back:[["Yellampalli → Karimnagar","Tea + fuel","130","2h40","20"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1500,toll:200,park:200,entry:100},
safety:"Barrage water — no wading; truck corridor — daylight, headlights on.",
src:["Irrigation Dept — Yellampalli notices","Google Maps routing"]},
{n:113,name:"Kannepally Pushkar Ghat",dest:"Saraswati pushkar ghat, Kannepally (Mancherial)",lat:18.78,lon:79.55,zoom:9,
oneWay:250,total:505,ride:"~10 hrs riding over 2 days + ghat",dur:"1 night / 2 days",durKey:"1n",
roads:"Karimnagar–Mancherial Hwy + Kannepally riverside link; long highway + rural tail",
terrain:"Good highway + river ghats",diff:"Moderate",cat:["long","scenic","temples"],
district:"Mancherial",
depart:"04:00 Day 1",back:"21:00 Day 2",season:"Oct–Feb; pushkaram seasons crowded (verify)",
warn:"Godavari ghats — no swimming; festival crowds (verify calendar).",
tolls:"State tolls (verify)",
desc:"Riverside calm in the coal belt: Kannepally's Saraswati ghat on the Godavari.",
attract:"Kannepally ghat + temple (verify); Godavari sunset; Mancherial halt.",
foodB:"Day 1: Karimnagar tiffins.",
foodL:"Kannepally/Mancherial meals (verify) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"],["Mancherial top-up MANDATORY","~75 km further"]],
support:"Highway dense; ghat tail basic. Hospitals: Mancherial; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Karimnagar","Breakfast + MANDATORY fuel","165","3h20","30"],["Mancherial → Kannepally","Ghat + sunset","85","1h50","120"]],
back:[["Kannepally → Mancherial → Karimnagar","Fuel Karimnagar","160","3h20","25"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1500,toll:200,park:200,entry:50},
safety:"Ghat steps — no wading beyond steps; festival days — early arrival.",
src:["Telangana Tourism — Kannepally","Google Maps routing"]},
{n:114,name:"Chennur Godavari Town",dest:"Godavari riverside town, Chennur (Mancherial)",lat:18.85,lon:79.79,zoom:9,
oneWay:240,total:485,ride:"~9.5 hrs riding over 2 days + river",dur:"1 night / 2 days",durKey:"1n",
roads:"Karimnagar–Chennur Hwy; long highway + town lanes",
terrain:"Good highway + riverside",diff:"Moderate",cat:["long","scenic","food"],
district:"Mancherial",
depart:"04:30 Day 1",back:"20:30 Day 2",season:"Oct–Feb",
warn:"Long highway days; riverside monsoon levels (verify).",
tolls:"State tolls (verify)",
desc:"Godavari-town overnighter: Chennur's ghats, markets and river breeze.",
attract:"Chennur ghats + old town (verify); riverside sunset; Mancherial food.",
foodB:"Day 1: Karimnagar tiffins.",
foodL:"Chennur town meals (verify) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"],["Chennur top-up (verify)","~75 km further"]],
support:"Highway dense. Hospitals: Chennur PHC/Mancherial; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Karimnagar","Breakfast + MANDATORY fuel","165","3h20","30"],["Chennur","Ghats + town","75","1h35","120"]],
back:[["Chennur → Karimnagar","Tea + fuel","75","1h35","20"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1500,toll:200,park:200,entry:50},
safety:"Riverbank after dark avoided; long-day fatigue plan.",
src:["Telangana Tourism — Chennur","Google Maps routing"]},
{n:115,name:"Koilkonda Fort Ride",dest:"Koilkonda Fort hill, Mahabubnagar",lat:16.75,lon:77.78,zoom:10,
oneWay:148,total:300,ride:"~6 hrs riding + fort",dur:"Full day",durKey:"full",
roads:"NH44 (Bangalore Hwy) + Koilkonda link; highway then rural paved + hill",
terrain:"Good highway + fort hill on foot",diff:"Moderate",cat:["forts","heritage","scenic"],
district:"Mahabubnagar",
depart:"05:00",back:"20:00",season:"Oct–Mar",
warn:"Qutb Shahi hill fort — climb + seven gates; summer rock heat.",
tolls:"NH tolls (verify)",
desc:"Seven-gated hill fort: Koilkonda's ramparts with a famed Ibrahim mosque inside.",
attract:"Koilkonda seven gateways + mosque (verify); hill viewpoint; Mahabubnagar food.",
foodB:"Shadnagar-side tiffins (verify) — ₹150–300.",
foodL:"Koilkonda/Mahabubnagar meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Shadnagar (~55 km)","55 km"],["Mahabubnagar (~95 km further) MANDATORY","95 km"]],
support:"NH44 dense. Hospitals: Mahabubnagar; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Shadnagar","Tea + fuel","55","1h10","20"],["Mahabubnagar → Koilkonda","Fort (2 hrs)","95","2h","120"]],
back:[["Koilkonda → Mahabubnagar","Tea + fuel","15","25 min","20"],["Mahabubnagar → Saroornagar","Cruise via Shadnagar","135","2h40","—"]],
budget:{food:800,toll:150,park:150,entry:50},
safety:"Hill fort — solid footwear, daylight only; seven gates = long climb, carry water.",
src:["Telangana Tourism — Koilkonda","Google Maps routing"]},
{n:116,name:"Manyamkonda Hill Temple",dest:"Venkateswara hill temple, Manyamkonda (Mahabubnagar)",lat:17.63,lon:77.99,zoom:10,
oneWay:160,total:325,ride:"~6.5 hrs riding + hill",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 + Manyamkonda hill link; highway then hill Rd",
terrain:"Good highway + hill steps",diff:"Moderate",cat:["temples","hills","long"],
district:"Mahabubnagar",
depart:"05:00 Day 1",back:"19:00 Day 2",season:"Oct–Mar; jatara season (verify)",
warn:"Hill steps + festival crowds (verify); monkeys.",
tolls:"NH tolls (verify)",
desc:"Deccan Tirupati of the south: Manyamkonda's Venkateswara hill.",
attract:"Manyamkonda hill temple; viewpoint; Mahabubnagar halt.",
foodB:"Day 1: Shadnagar tiffins.",
foodL:"Manyamkonda/Mahabubnagar meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Shadnagar (~55 km)","55 km"],["Mahabubnagar MANDATORY","~105 km further"]],
support:"NH44 dense; hill spur basic. Hospitals: Mahabubnagar; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Shadnagar","Tea + fuel","55","1h10","20"],["Mahabubnagar → Manyamkonda","Hill + temple","105","2h10","120"]],
back:[["Manyamkonda → Mahabubnagar","Tea + fuel","20","30 min","20"],["Mahabubnagar → Saroornagar","Cruise","140","2h50","—"]],
budget:{food:1200,toll:150,park:150,entry:50},
safety:"Hill steps — water discipline; festival days — early arrival.",
src:["Telangana Tourism — Manyamkonda","Google Maps routing"]},
{n:117,name:"Narayanpet Handloom Town",dest:"Handloom town + old walls, Narayanpet",lat:16.746,lon:77.495,zoom:10,
oneWay:165,total:335,ride:"~6.8 hrs riding + town",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 + Narayanpet link via Mahabubnagar; highway then town lanes",
terrain:"Good highway + old-town lanes",diff:"Easy",cat:["easy","heritage","long","food"],
district:"Narayanpet",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Oct–Mar",
warn:"Old-town lanes slow; GI-tag saree outlets — buy at weaver co-ops (verify).",
tolls:"NH tolls (verify)",
desc:"Saree-town ride: Narayanpet's looms, old walls and Krishna-belt food.",
attract:"Handloom co-op outlets (verify); old town walls; Narayanpet food.",
foodB:"Day 1: Mahabubnagar tiffins.",
foodL:"Narayanpet town meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Mahabubnagar (~140 km) MANDATORY","140 km"]],
support:"NH44 dense; town spur basic. Hospitals: Narayanpet area hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Mahabubnagar","Breakfast + MANDATORY fuel","140","2h50","30"],["Narayanpet","Looms + walls","25","40 min","120"]],
back:[["Narayanpet → Mahabubnagar","Tea + fuel","25","40 min","20"],["Mahabubnagar → Saroornagar","Cruise","140","2h50","—"]],
budget:{food:1200,toll:150,park:150,entry:0},
safety:"Market lanes — walking pace; cash for co-ops.",
src:["Telangana Tourism — Narayanpet","Google Maps routing"]},
{n:118,name:"Alampur Navabrahma Trail",dest:"Navabrahma temple group, Alampur (Jogulamba Gadwal)",lat:15.88,lon:78.13,zoom:10,
oneWay:210,total:425,ride:"~8 hrs riding + temples",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 + Alampur Tungabhadra-side link; highway then riverside paved",
terrain:"Good highway + temple town",diff:"Moderate",cat:["temples","heritage","long","scenic"],
district:"Jogulamba Gadwal",
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Mar",
warn:"Chalukya stonework — monument discipline; Tungabhadra bank — no swimming.",
tolls:"NH tolls (verify)",
desc:"Chalukya cradle: nine Brahma temples plus Sangameshwara lifted stone-by-stone.",
attract:"Navabrahma group (verify access); Sangameshwara temple; Tungabhadra bank.",
foodB:"Day 1: Jadcherla/Mahabubnagar tiffins — ₹150–300.",
foodL:"Alampur town meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Mahabubnagar (~140 km) MANDATORY","140 km"],["Alampur top-up (verify)","~70 km further"]],
support:"NH44 dense; temple-town spur basic. Hospitals: Alampur PHC/Gadwal; 108/112.",
route:[["Saroornagar start","Fuel + long-ride briefing","0","—","15"],["Mahabubnagar","Breakfast + MANDATORY fuel","140","2h50","30"],["Alampur","Temples (2.5 hrs)","70","1h30","150"]],
back:[["Alampur → Mahabubnagar","Tea + fuel","70","1h30","20"],["Mahabubnagar → Saroornagar","Cruise","140","2h50","—"]],
budget:{food:1400,toll:200,park:150,entry:100},
safety:"Ancient complexes — stay on paths; riverbank after dark avoided.",
src:["Telangana Tourism — Alampur","Google Maps routing"]},
{n:119,name:"Beechupally Krishna Temple",dest:"Anjaneya Temple on Krishna, Beechupally (Jogulamba Gadwal)",lat:17.00,lon:77.85,zoom:10,
oneWay:190,total:385,ride:"~7.5 hrs riding + river",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 + Beechupally riverside link; highway then rural paved",
terrain:"Good highway + river ghats",diff:"Easy",cat:["easy","temples","scenic","long"],
district:"Jogulamba Gadwal",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Oct–Feb",
warn:"Krishna ghats — slippery steps, no swimming; bridge viewpoint bays only.",
tolls:"NH tolls (verify)",
desc:"Island-shrine ride: Beechupally's Hanuman between Krishna channels.",
attract:"Beechupally temple island (verify); Krishna bridge viewpoint; Itikyala halt.",
foodB:"Day 1: Jadcherla tiffins.",
foodL:"Beechupally/Itikyala meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Jadcherla (~95 km) MANDATORY","95 km"],["Itikyala top-up (verify)","~95 km further"]],
support:"NH44 dense; riverside spur basic. Hospitals: Gadwal; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Jadcherla","Breakfast + MANDATORY fuel","95","2h","30"],["Beechupally","Temple + river","95","2h","120"]],
back:[["Beechupally → Jadcherla","Tea + fuel","95","2h","20"],["Jadcherla → Saroornagar","Cruise","95","2h","—"]],
budget:{food:1300,toll:200,park:150,entry:50},
safety:"Island access — water levels (verify); bridge — no halts except bays.",
src:["Telangana Tourism — Beechupally","Google Maps routing"]},
{n:120,name:"Umamaheshwaram Hill Temple",dest:"Umamaheshwaram hill temple, Nagarkurnool",lat:17.38,lon:78.55,zoom:10,
oneWay:148,total:300,ride:"~6 hrs riding + hill",dur:"Full day",durKey:"full",
roads:"Srisailam Hwy (NH765) + Umamaheshwaram forest link; highway then forest hill Rd",
terrain:"Highway + forest hill steps",diff:"Moderate",cat:["temples","hills","scenic"],
district:"Nagarkurnool",
depart:"05:00",back:"20:00",season:"Oct–Mar; Shivaratri crowds (verify)",
warn:"Nallamala forest edge — checkpost rules (verify); hill steps; monkeys.",
tolls:"State tolls (verify)",
desc:"Quiet Nallamala Shiva hill: Umamaheshwaram's cave-like sanctum and Papanaasanam spring.",
attract:"Umamaheshwaram temple; Papanaasanam spring (verify); forest viewpoints.",
foodB:"Kalwakurthy tiffins (verify) — ₹150–300.",
foodL:"Umamaheshwaram base/Achampet meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Kalwakurthy (~80 km) MANDATORY","80 km"]],
support:"Highway dense to Kalwakurthy; forest spur basic. Hospitals: Achampet/Kalwakurthy; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Kalwakurthy","Breakfast + MANDATORY fuel","80","1h45","25"],["Umamaheshwaram","Hill + temple","68","1h30","120"]],
back:[["Umamaheshwaram → Kalwakurthy","Tea + fuel","68","1h30","20"],["Kalwakurthy → Saroornagar","Cruise","80","1h45","—"]],
budget:{food:800,toll:100,park:150,entry:50},
safety:"Forest edge — daylight only; spring rocks slippery.",
src:["Telangana Tourism — Umamaheshwaram","Google Maps routing"]},
{n:121,name:"Mallela Theertham Falls",dest:"Mallela Theertham Waterfall, Nallamala (Nagarkurnool)",lat:17.22,lon:78.58,zoom:10,
oneWay:170,total:345,ride:"~7 hrs riding + falls trek",dur:"1 night / 2 days",durKey:"1n",
roads:"Srisailam Hwy + Mallela forest link; highway then forest Rd + trek",
terrain:"Highway + forest + rocky trek",diff:"Challenging",cat:["waterfalls","adventure","long"],
district:"Nagarkurnool",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Aug–Dec (falls alive); summer dry — skip",
warn:"Nallamala checkpost rules (verify); ~350 steps down to falls; rocks lethal when wet; carries: water, food.",
tolls:"State tolls (verify)",
desc:"Nallamala's staircase falls: Mallela Theertham after a forest ride and step descent.",
attract:"Mallela tiers + plunge pool (verify access); forest drive; Farahabad-side extension.",
foodB:"Day 1: Kalwakurthy tiffins.",
foodL:"Mallela/Achampet meals (verify; carry backup) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Kalwakurthy (~80 km) MANDATORY","80 km"],["Mannanur top-up (verify)","~70 km further"]],
support:"Highway dense; forest tail sparse. Hospitals: Achampet/Mannanur; 108/112.",
route:[["Saroornagar start","Fuel + forest briefing","0","—","15"],["Kalwakurthy","Breakfast + MANDATORY fuel","80","1h45","25"],["Mannanur → Mallela","Falls + trek","90","2h","150"]],
back:[["Mallela → Mannanur → Kalwakurthy","Fuel Kalwakurthy","90","2h","20"],["Kalwakurthy → Saroornagar","Cruise","80","1h45","—"]],
budget:{food:1300,toll:150,park:200,entry:100},
safety:"Steps + falls: fenced points only; forest daylight only; leeches in monsoon.",
src:["Telangana Forest Dept — Mallela Theertham","Google Maps routing"]},
{n:122,name:"Somasila Krishna Reservoir",dest:"Somasila reservoir + temples, Nagarkurnool",lat:17.07,lon:78.33,zoom:10,
oneWay:180,total:365,ride:"~7.3 hrs riding + reservoir",dur:"1 night / 2 days",durKey:"1n",
roads:"Srisailam Hwy + Kollapur–Somasila link; highway then rural paved",
terrain:"Highway + reservoir bund",diff:"Moderate",cat:["lakes","scenic","long","temples"],
district:"Nagarkurnool",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Aug–Feb",
warn:"Reservoir backwaters — bund discipline; Kollapur-side rural fuel.",
tolls:"State tolls (verify)",
desc:"Krishna backwater calm: Somasila's bund, temples and Kollapur countryside.",
attract:"Somasila bund + viewpoints (verify); riverside temples; Kollapur halt.",
foodB:"Day 1: Kalwakurthy tiffins.",
foodL:"Somasila/Kollapur meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Kalwakurthy (~80 km) MANDATORY","80 km"],["Kollapur top-up (verify)","~100 km further"]],
support:"Highway dense; reservoir spur basic. Hospitals: Kollapur/Achampet; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Kalwakurthy","Breakfast + MANDATORY fuel","80","1h45","25"],["Kollapur → Somasila","Bund + temples","100","2h10","120"]],
back:[["Somasila → Kollapur → Kalwakurthy","Fuel Kalwakurthy","100","2h10","20"],["Kalwakurthy → Saroornagar","Cruise","80","1h45","—"]],
budget:{food:1300,toll:150,park:200,entry:50},
safety:"Backwaters — no wading; bund shoulders soft.",
src:["Telangana Tourism — Somasila","Google Maps routing"]},
{n:123,name:"Pangal Fort Ride",dest:"Pangal Fort + town, Wanaparthy",lat:17.27,lon:78.06,zoom:10,
oneWay:160,total:325,ride:"~6.5 hrs riding + fort",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 + Pangal link via Wanaparthy; highway then rural paved",
terrain:"Good highway + town lanes",diff:"Moderate",cat:["forts","heritage","long"],
district:"Wanaparthy",
depart:"05:00 Day 1",back:"19:00 Day 2",season:"Oct–Mar",
warn:"Old fort-town lanes; ruins — authorised areas; long day fatigue.",
tolls:"NH tolls (verify)",
desc:"Wanaparthy Samsthanam history: Pangal's fort walls and market streets.",
attract:"Pangal fort walls + gateways (verify); old-town markets; Wanaparthy halt.",
foodB:"Day 1: Jadcherla tiffins.",
foodL:"Pangal/Wanaparthy meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Jadcherla (~95 km) MANDATORY","95 km"],["Wanaparthy top-up","~65 km further"]],
support:"NH44 dense; town spur basic. Hospitals: Wanaparthy; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Jadcherla","Breakfast + MANDATORY fuel","95","2h","30"],["Wanaparthy → Pangal","Fort + market","65","1h20","120"]],
back:[["Pangal → Wanaparthy → Jadcherla","Fuel Jadcherla","65","1h20","20"],["Jadcherla → Saroornagar","Cruise","95","2h","—"]],
budget:{food:1200,toll:150,park:150,entry:50},
safety:"Old walls — keep distance; market lanes walking pace.",
src:["Telangana Tourism — Pangal","Google Maps routing"]},
{n:124,name:"Durgam Cheruvu Spin",dest:"Durgam Cheruvu lakefront + cable bridge, Hyderabad",lat:17.437,lon:78.386,zoom:12,
oneWay:22,total:46,ride:"~1.4 hrs riding + lakefront",dur:"Half day",durKey:"half",
roads:"City arterials (Saroornagar–Mehdipatnam–Jubilee Hills–Madhavpur); paved urban",
terrain:"Paved city road + lakefront promenade",diff:"Easy",cat:["easy","lakes","scenic"],
district:"Hyderabad",
depart:"06:30 / 16:30",season:"Oct–Feb evenings",
warn:"Cable-bridge corridor traffic; lakefront parking bays only.",
tolls:"None",
desc:"Secret-lake city ride: Durgam Cheruvu's bund, cable bridge and rock walk.",
attract:"Durgam bund + cable-bridge viewpoint (verify); rock walk (verify); HITEC food.",
foodB:"Jubilee Hills tiffins (verify) — ₹150–300.",
foodL:"HITEC/Madhapur outlets (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Jubilee Hills corridor pumps if required","~16 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Jubilee Hills","Regroup","16","30 min","10"],["Durgam Cheruvu","Bund + bridge","6","15 min","60"]],
back:[["Durgam → Jubilee Hills","Cruise","6","15 min","10"],["Jubilee Hills → Saroornagar","Home","16","30 min","—"]],
budget:{food:450,toll:0,park:100,entry:0},
safety:"Lake rocks — authorised paths; night corridor — headlights on.",
src:["Telangana Tourism — Durgam Cheruvu","Google Maps routing"]},
{n:125,name:"Paigah Tombs Walk",dest:"Paigah Tombs, Santoshnagar (Hyderabad)",lat:17.372,lon:78.469,zoom:12,
oneWay:12,total:26,ride:"~45 min riding + tombs",dur:"Half day",durKey:"half",
roads:"City arterials via Malakpet–Santoshnagar; paved urban lanes",
terrain:"Paved city road; tombs on foot",diff:"Easy",cat:["easy","heritage"],
district:"Hyderabad",
depart:"09:00",season:"Oct–Mar",
warn:"Narrow old-city lanes; tomb complex timings — verify; quiet hours respected.",
tolls:"None",
desc:"Marble inlay marvel: Paigah nobles' tombs with lattice screens.",
attract:"Paigah tomb pavilions (verify access); jali screens; old-city lanes.",
foodB:"Malakpet tiffins (verify) — ₹100–250.",
foodL:"Old-city meals extension (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["No top-up needed","—"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Malakpet","Regroup","4","12 min","10"],["Paigah Tombs","Tombs (1 hr)","8","18 min","60"]],
back:[["Tombs → Malakpet","Cruise","8","18 min","10"],["Malakpet → Saroornagar","Home","4","12 min","—"]],
budget:{food:450,toll:0,park:150,entry:50},
safety:"Lanes — walking pace; monument silence discipline.",
src:["Telangana Tourism — Paigah Tombs","Google Maps routing"]},
{n:126,name:"State Museum Morning",dest:"Telangana State Archaeology Museum, Public Gardens (Hyderabad)",lat:17.398,lon:78.47,zoom:12,
oneWay:16,total:34,ride:"~1 hr riding + museum",dur:"Half day",durKey:"half",
roads:"City arterials (Saroornagar–Narayanguda–Public Gardens); paved urban",
terrain:"Paved city road",diff:"Easy",cat:["easy","heritage"],
district:"Hyderabad",
depart:"09:30",season:"Year-round (indoor)",
warn:"Museum holidays — verify; Public Gardens parking discipline.",
tolls:"None",
desc:"Egyptian mummy to Buddhist friezes: the state museum inside Public Gardens.",
attract:"Egyptian + Buddhist galleries (verify); Public Gardens lawns; antiques block.",
foodB:"Narayanguda tiffins (verify) — ₹100–250.",
foodL:"Gardens canteen / return-base meals (verify) — ₹200–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Narayanguda corridor pumps if required","~10 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Narayanguda","Regroup","10","20 min","10"],["State Museum","Galleries (2 hrs)","6","15 min","120"]],
back:[["Museum → Narayanguda","Cruise","6","15 min","10"],["Narayanguda → Saroornagar","Home","10","20 min","—"]],
budget:{food:500,toll:0,park:150,entry:100},
safety:"Museum rules — bags/cameras per counter instructions.",
src:["Telangana State Museum notices","Google Maps routing"]},
{n:127,name:"Fox Sagar Sunrise",dest:"Fox Sagar Lake (Jeedimetla), Medchal-Malkajgiri",lat:17.53,lon:78.47,zoom:12,
oneWay:28,total:58,ride:"~1.7 hrs riding + lake",dur:"Half day",durKey:"half",
roads:"City arterials (Saroornagar–Uppal–Moula Ali–Jeedimetla); paved urban",
terrain:"Paved city road + lake bund",diff:"Easy",cat:["easy","lakes","scenic"],
district:"Medchal-Malkajgiri",
depart:"05:45",season:"Jun–Feb (water + birds)",
warn:"Industrial-corridor trucks (Jeedimetla); bund parking bays only.",
tolls:"None",
desc:"North-city lake morning: Fox Sagar's bund, palms and winter birds.",
attract:"Fox Sagar bund + birding corners (verify); sunrise bays; Kompally food.",
foodB:"Moula Ali/Kompally tiffins (verify) — ₹100–250.",
foodL:"Return-base meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Uppal corridor pumps if required","~12 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Uppal","Regroup","12","25 min","10"],["Fox Sagar","Bund + birds","16","30 min","60"]],
back:[["Fox Sagar → Uppal","Cruise","16","30 min","10"],["Uppal → Saroornagar","Home","12","25 min","—"]],
budget:{food:400,toll:0,park:100,entry:0},
safety:"Industrial traffic — daylight, no halts except bays; bund soft edges.",
src:["Telangana Tourism — Fox Sagar","Google Maps routing"]},
{n:128,name:"Mir Alam Tank Loop",dest:"Mir Alam Tank bund, Hyderabad",lat:17.34,lon:78.46,zoom:12,
oneWay:12,total:26,ride:"~45 min riding + bund",dur:"Half day",durKey:"half",
roads:"City arterials via Chandrayangutta–Bahadurpura; paved urban",
terrain:"Paved city road + historic bund",diff:"Easy",cat:["easy","lakes","heritage","scenic"],
district:"Hyderabad",
depart:"06:00",season:"Jun–Feb",
warn:"Old bund road — slow; zoo traffic on weekends; no racing on bund.",
tolls:"None",
desc:"1804 masonry bund ride: Mir Alam Tank next to the zoo gates.",
attract:"Mir Alam bund (1804 masonry, verify); zoo-gate extension; old-city views.",
foodB:"Chandrayangutta tiffins (verify) — ₹100–250.",
foodL:"Return-base meals.",
fuel:[["Start FULL Saroornagar","0 km"],["No top-up needed","—"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Bahadurpura","Regroup","8","18 min","10"],["Mir Alam Tank","Bund cruise","4","12 min","45"]],
back:[["Tank → Bahadurpura","Cruise","4","12 min","10"],["Bahadurpura → Saroornagar","Home","8","18 min","—"]],
budget:{food:400,toll:0,park:100,entry:0},
safety:"Heritage bund — slow cruise; weekend zoo traffic.",
src:["Telangana Tourism — Mir Alam Tank","Google Maps routing"]},
{n:129,name:"Kapra Lake Morning",dest:"Kapra Lake + Mini Tank Bund, Medchal-Malkajgiri",lat:17.49,lon:78.57,zoom:12,
oneWay:25,total:52,ride:"~1.5 hrs riding + lake",dur:"Half day",durKey:"half",
roads:"City arterials (Saroornagar–Uppal–ECIL–Kapra); paved urban",
terrain:"Paved city road + lake promenade",diff:"Easy",cat:["easy","lakes","scenic"],
district:"Medchal-Malkajgiri",
depart:"06:00",season:"Jun–Feb",
warn:"ECIL-X-roads traffic; promenade parking bays only.",
tolls:"None",
desc:"Mini-Tank-Bund morning: Kapra's statue promenade and island views.",
attract:"Kapra mini tank bund (verify); island viewpoint; Sainikpuri food.",
foodB:"ECIL/Sainikpuri tiffins (verify) — ₹100–250.",
foodL:"Return-base meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Uppal corridor pumps if required","~12 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Uppal","Regroup","12","25 min","10"],["Kapra Lake","Promenade (1 hr)","13","25 min","60"]],
back:[["Kapra → Uppal","Cruise","13","25 min","10"],["Uppal → Saroornagar","Home","12","25 min","—"]],
budget:{food:400,toll:0,park:100,entry:0},
safety:"Promenade tiles slick in monsoon; ECIL traffic discipline.",
src:["Telangana Tourism — Kapra Lake","Google Maps routing"]},
{n:130,name:"Kothur Highway Food Run",dest:"Kothur highway food halt, Rangareddy (NH44)",lat:17.15,lon:78.35,zoom:11,
oneWay:50,total:104,ride:"~2.5 hrs riding + dhabas",dur:"Half day",durKey:"half",
roads:"NH44 (Bangalore Hwy) via Shadnagar–Kothur; fast highway",
terrain:"Good divided highway",diff:"Easy",cat:["easy","food","scenic"],
district:"Rangareddy",
depart:"06:30",season:"Oct–Mar mornings",
warn:"Highway-speed discipline; dhaba parking — service-lane entry only.",
tolls:"NH tolls (verify)",
desc:"Pure food run: NH44 dhabas at Kothur and back before lunch traffic.",
attract:"Kothur dhaba row (verify); highway cruise; Shadnagar tea halt.",
foodB:"Kothur dhabas (verify) — ₹200–400.",
foodL:"Return-base meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Shadnagar top-up on return (~55 km)","55 km"]],
support:"NH44 dense. Hospitals: Shadnagar; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Shadnagar","Tea + regroup","55","1h10","15"],["Kothur dhabas","Food halt","10","15 min","60"]],
back:[["Kothur → Shadnagar","Fuel Shadnagar","10","15 min","15"],["Shadnagar → Saroornagar","Home","55","1h10","—"]],
budget:{food:600,toll:100,park:50,entry:0},
safety:"Highway food run — no U-turns; service lanes only.",
src:["Google Maps routing"]},
{n:131,name:"Kusumanchi Temple Town",dest:"Ganapeshwaralayam + temples, Kusumanchi (Khammam)",lat:17.22,lon:79.88,zoom:10,
oneWay:185,total:375,ride:"~7.3 hrs riding + temples",dur:"1 night / 2 days",durKey:"1n",
roads:"Vijayawada Hwy + Kusumanchi link; highway then town lanes",
terrain:"Good highway + town lanes",diff:"Easy",cat:["easy","temples","long","heritage"],
district:"Khammam",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Oct–Mar",
warn:"Old temple-town lanes; Kakatiya stonework discipline.",
tolls:"NH tolls (verify)",
desc:"Temple-town overnighter: Kusumanchi's Ganapeshwaralayam plus Palair-side lake.",
attract:"Ganapeshwaralayam complex (verify); old-town shrines; Palair extension.",
foodB:"Day 1: Suryapet tiffins.",
foodL:"Kusumanchi/Khammam meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Suryapet (~135 km) MANDATORY","135 km"],["Kusumanchi top-up (verify)","~50 km further"]],
support:"NH65 dense; town spur basic. Hospitals: Khammam; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Suryapet","Breakfast + MANDATORY fuel","135","2h40","30"],["Kusumanchi","Temples (2 hrs)","50","1h10","120"]],
back:[["Kusumanchi → Suryapet","Tea + fuel","50","1h10","20"],["Suryapet → Saroornagar","Cruise","135","2h40","—"]],
budget:{food:1300,toll:200,park:150,entry:50},
safety:"Town lanes — walking pace near shrines.",
src:["Telangana Tourism — Kusumanchi","Google Maps routing"]},
{n:132,name:"Manuguru Godavari Banks",dest:"Godavari riverside, Manuguru (Bhadradri Kothagudem)",lat:17.95,lon:79.75,zoom:9,
oneWay:270,total:545,ride:"~11 hrs riding over 2–3 days + river",dur:"2 nights / 3 days",durKey:"2n",
roads:"Warangal–Khammam–Manuguru Hwy; very long highway + town lanes",
terrain:"Highway + coal-town lanes + riverbank",diff:"Moderate",cat:["long","scenic","food"],
district:"Bhadradri Kothagudem",
depart:"04:00 Day 1",back:"21:00 Day 3",season:"Oct–Feb",
warn:"Coal-belt truck traffic; riverbank — no swimming; three-day fatigue plan.",
tolls:"NH tolls (verify)",
desc:"Far-east river ride: Manuguru's Godavari banks beyond the coal fields.",
attract:"Manuguru riverside viewpoints (verify); town markets; Kothagudem halt.",
foodB:"Day 1: Warangal tiffins.",
foodL:"Manuguru/Kothagudem meals (verify) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Warangal (~148 km) MANDATORY","148 km"],["Kothagudem top-up MANDATORY","~100 km further"]],
support:"Dense to Kothagudem; riverside tail basic. Hospitals: Kothagudem/Manuguru; 108/112.",
route:[["Saroornagar start","Fuel + expedition briefing","0","—","15"],["Warangal","Breakfast + MANDATORY fuel","148","3h","30"],["Kothagudem → Manuguru","Riverside","122","2h30","150"]],
back:[["Manuguru → Kothagudem → Warangal","Fuel Warangal","170","3h30","25"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:1800,toll:250,park:200,entry:50},
safety:"Truck corridor — daylight, no tailgating; riverbank after dark avoided.",
src:["Telangana Tourism — Manuguru","Google Maps routing"]},
{n:133,name:"Dornakal Church Heritage",dest:"CSI Epiphany Cathedral, Dornakal (Mahabubabad)",lat:17.43,lon:79.99,zoom:10,
oneWay:160,total:325,ride:"~6.5 hrs riding + heritage",dur:"1 night / 2 days",durKey:"1n",
roads:"Warangal Hwy + Dornakal link; highway then town lanes",
terrain:"Good highway + town lanes",diff:"Easy",cat:["easy","heritage","long"],
district:"Mahabubabad",
depart:"05:00 Day 1",back:"19:00 Day 2",season:"Oct–Mar; Christmas season services (verify)",
warn:"1914 cathedral — service timings + silence discipline (verify); town lanes.",
tolls:"NH tolls (verify)",
desc:"Deccan church heritage: Dornakal's Epiphany Cathedral plus Mahabubabad food.",
attract:"Epiphany Cathedral (verify access); railway-town heritage; Mahabubabad halt.",
foodB:"Day 1: Warangal tiffins.",
foodL:"Dornakal/Mahabubabad meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Warangal (~148 km) MANDATORY","148 km"]],
support:"Highway dense. Hospitals: Mahabubabad; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Warangal","Breakfast + fuel","148","3h","30"],["Dornakal","Cathedral (1 hr)","25","35 min","60"]],
back:[["Dornakal → Warangal","Tea + fuel","25","35 min","20"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:1200,toll:150,park:150,entry:0},
safety:"Worship hours respected; town lanes slow.",
src:["Telangana Tourism — Dornakal","Google Maps routing"]},
{n:134,name:"Manthani Temple Circuit",dest:"Gautameshwar + temples, Manthani (Peddapalli)",lat:18.65,lon:79.66,zoom:9,
oneWay:220,total:445,ride:"~8.8 hrs riding + temples",dur:"1 night / 2 days",durKey:"1n",
roads:"Karimnagar–Manthani Hwy; long highway + temple-town lanes",
terrain:"Good highway + old-town lanes",diff:"Moderate",cat:["temples","heritage","long"],
district:"Peddapalli",
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Oct–Mar",
warn:"Vedic-town lanes slow; Gautameshwar ghat steps (verify); long day fatigue.",
tolls:"State tolls (verify)",
desc:"Mantrapuri ride: Manthani's Gautameshwar and thousand-pillar-era shrines.",
attract:"Gautameshwar complex (verify); temple-town street; Godavari-bank extension.",
foodB:"Day 1: Karimnagar tiffins.",
foodL:"Manthani town meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"],["Manthani top-up (verify)","~55 km further"]],
support:"Highway dense; temple-town spur basic. Hospitals: Manthani PHC/Karimnagar; 108/112.",
route:[["Saroornagar start","Fuel + long-ride briefing","0","—","15"],["Karimnagar","Breakfast + MANDATORY fuel","165","3h20","30"],["Manthani","Temples (2 hrs)","55","1h15","120"]],
back:[["Manthani → Karimnagar","Tea + fuel","55","1h15","20"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1400,toll:150,park:150,entry:50},
safety:"Old-town lanes — walking pace; ghat steps after dark avoided.",
src:["Telangana Tourism — Manthani","Google Maps routing"]},
{n:135,name:"Cheriyal Art Village",dest:"Nakashi scroll-art village, Cheriyal (Siddipet)",lat:17.87,lon:78.77,zoom:10,
oneWay:95,total:195,ride:"~4 hrs riding + art",dur:"Full day",durKey:"full",
roads:"Medchal–Siddipet Hwy + Cheriyal link; highway then village lanes",
terrain:"Good highway + village lanes",diff:"Easy",cat:["easy","scenic","heritage"],
district:"Siddipet",
depart:"06:00",season:"Oct–Mar",
warn:"Artist-house visits — ask before photos; carry cash for scroll outlets.",
tolls:"State tolls (verify)",
desc:"Scroll-painting village: Cheriyal's Nakashi artists and GI-tagged craft.",
attract:"Artist-house visits (verify); Nakashi outlets; village lake bund.",
foodB:"Siddipet tiffins (verify) — ₹100–250.",
foodL:"Cheriyal/Siddipet meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Siddipet (~95 km) top-up","95 km"]],
support:"Highway dense. Hospitals: Siddipet/Jangaon; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Siddipet","Tea + fuel","100","2h","20"],["Cheriyal","Art houses (1.5 hrs)","12","20 min","90"]],
back:[["Cheriyal → Siddipet","Fuel","12","20 min","15"],["Siddipet → Saroornagar","Cruise","100","2h","—"]],
budget:{food:650,toll:100,park:100,entry:0},
safety:"Village lanes — livestock; artisan homes — respect privacy.",
src:["Telangana Tourism — Cheriyal","Google Maps routing"]},
{n:136,name:"Bodhan Heritage Town",dest:"Old town + Ekachakram legend sites, Bodhan (Nizamabad)",lat:18.66,lon:78.55,zoom:10,
oneWay:185,total:375,ride:"~7.3 hrs riding + town",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 + Bodhan link; highway then old-town lanes",
terrain:"Good highway + town lanes",diff:"Easy",cat:["easy","heritage","long","food"],
district:"Nizamabad",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Oct–Mar",
warn:"Old-town lanes slow; Nizam sugar-factory corridor trucks (verify).",
tolls:"NH tolls (verify)",
desc:"Mahabharata-lore town: Bodhan's Ekachakram legend plus Nizam-era streets.",
attract:"Old-town heritage lanes (verify); temple/mosque streetscape; Bodhan food.",
foodB:"Day 1: Kamareddy tiffins.",
foodL:"Bodhan town meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Kamareddy (~130 km) MANDATORY","130 km"],["Bodhan top-up (verify)","~55 km further"]],
support:"NH44 dense. Hospitals: Bodhan area hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Kamareddy","Breakfast + MANDATORY fuel","130","2h40","30"],["Bodhan","Old town (2 hrs)","55","1h10","120"]],
back:[["Bodhan → Kamareddy","Tea + fuel","55","1h10","20"],["Kamareddy → Saroornagar","Cruise","130","2h40","—"]],
budget:{food:1300,toll:200,park:150,entry:50},
safety:"Factory-corridor trucks — daylight; old lanes walking pace.",
src:["Telangana Tourism — Bodhan","Google Maps routing"]},
{n:137,name:"Kerameri Ghats Drive",dest:"Kerameri Ghat road + watchtower, Kumuram Bheem Asifabad",lat:19.35,lon:79.10,zoom:9,
oneWay:290,total:585,ride:"~11.5 hrs riding over 2–3 days + ghats",dur:"2 nights / 3 days",durKey:"2n",
roads:"Nagpur Hwy + Utnoor–Asifabad–Kerameri tribal Rd; very long highway + single-lane ghat",
terrain:"Highway + 6-km ghat (S/U bends)",diff:"Challenging",cat:["long","hills","scenic","adventure"],
district:"Kumuram Bheem Asifabad",
depart:"04:00 Day 1",back:"21:00 Day 3",season:"Nov–Dec (autumn colours); monsoon lantana + slick (caution)",
warn:"Single-lane ghat with S/U bends + lantana blind spots — slowest vehicle wins; tribal heartland respect; network patchy.",
tolls:"NH tolls (verify)",
desc:"Telangana's prettiest ghat road: 6 km of bends, autumn colours and a watchtower over Asifabad hills.",
attract:"Kerameri ghat bends; watchtower viewpoint (verify); Busimetta–Keslaguda stretch.",
foodB:"Day 1: Nirmal tiffins.",
foodL:"Asifabad/Kerameri meals (verify; carry backup) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Nirmal (~210 km) MANDATORY","210 km"],["Asifabad top-up MANDATORY","~80 km further"]],
support:"Dense to Asifabad; ghat belt sparse. Hospitals: Asifabad; 108/112.",
route:[["Saroornagar start","Fuel + ghat briefing","0","—","15"],["Nirmal","Breakfast + MANDATORY fuel","210","4h","30"],["Asifabad → Kerameri Ghats","Ghat + tower","80","1h50","150"]],
back:[["Kerameri → Asifabad → Nirmal","Fuel Nirmal","170","3h30","25"],["Nirmal → Saroornagar","Cruise","210","4h","—"]],
budget:{food:1800,toll:250,park:200,entry:100},
safety:"Ghat: never stop on bends; scenery distracts — pillion watches road; daylight only.",
src:["Asifabad District (telangana.gov.in) — Kerameri Ghats","Google Maps routing"]},
{n:138,name:"Makthal Temple + Fort",dest:"Pardhasaradhi Temple + fort, Makthal (Narayanpet)",lat:17.50,lon:77.51,zoom:10,
oneWay:148,total:300,ride:"~6 hrs riding + town",dur:"Full day",durKey:"full",
roads:"NH44 + Makthal link via Mahabubnagar; highway then town lanes",
terrain:"Good highway + old-town lanes",diff:"Easy",cat:["easy","temples","heritage"],
district:"Narayanpet",
depart:"05:00",back:"20:00",season:"Oct–Mar",
warn:"Old-town lanes; fort remnants — authorised areas.",
tolls:"NH tolls (verify)",
desc:"Twin-attraction town: Makthal's Pardhasaradhi temple plus old fort walls.",
attract:"Makthal temple complex; fort remnants (verify); town markets.",
foodB:"Mahabubnagar tiffins (verify) — ₹150–300.",
foodL:"Makthal town meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Mahabubnagar (~140 km) MANDATORY","140 km"]],
support:"NH44 dense; town spur basic. Hospitals: Makthal PHC/Narayanpet; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Mahabubnagar","Breakfast + MANDATORY fuel","140","2h50","25"],["Makthal","Temple + fort","25","40 min","90"]],
back:[["Makthal → Mahabubnagar","Tea + fuel","25","40 min","15"],["Mahabubnagar → Saroornagar","Cruise","140","2h50","—"]],
budget:{food:800,toll:150,park:100,entry:50},
safety:"Town lanes — walking pace near shrines.",
src:["Telangana Tourism — Makthal","Google Maps routing"]},
{n:139,name:"Janpahad Dargah Hill",dest:"Janpahad Saidulu Dargah hill + fort walls, Suryapet",lat:17.05,lon:79.35,zoom:10,
oneWay:148,total:300,ride:"~6 hrs riding + hill",dur:"Full day",durKey:"full",
roads:"Vijayawada Hwy + Janpahad hill link; highway then hill Rd",
terrain:"Good highway + hill climb",diff:"Moderate",cat:["heritage","hills","scenic"],
district:"Suryapet",
depart:"05:00",back:"20:00",season:"Oct–Mar; Urs season crowds (verify)",
warn:"Hilltop dargah — silence + shrine discipline (verify); hill road parking.",
tolls:"NH tolls (verify)",
desc:"Hill of harmony: Janpahad's dargah and old fort walls over Suryapet plains.",
attract:"Janpahad hill dargah (verify); fort-wall remnants; viewpoint.",
foodB:"Suryapet tiffins (verify) — ₹150–300.",
foodL:"Janpahad/Suryapet meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Suryapet (~135 km) MANDATORY","135 km"]],
support:"NH65 dense. Hospitals: Suryapet; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Suryapet","Breakfast + MANDATORY fuel","135","2h40","25"],["Janpahad hill","Shrine + walls","15","30 min","90"]],
back:[["Janpahad → Suryapet","Tea + fuel","15","30 min","15"],["Suryapet → Saroornagar","Cruise","135","2h40","—"]],
budget:{food:800,toll:150,park:100,entry:0},
safety:"Shrine discipline; hill after dark avoided.",
src:["Telangana Tourism — Janpahad","Google Maps routing"]},
{n:140,name:"Shaikpet Sarai & Mosque",dest:"Shaikpet Sarai + mosque, Tolichowki (Hyderabad)",lat:17.40,lon:78.41,zoom:12,
oneWay:18,total:38,ride:"~1.2 hrs riding + heritage",dur:"Half day",durKey:"half",
roads:"City arterials via Mehdipatnam–Tolichowki; paved urban",
terrain:"Paved city road",diff:"Easy",cat:["easy","heritage"],
district:"Hyderabad",
depart:"07:00",season:"Oct–Mar",
warn:"Tolichowki traffic; sarai timings — verify; quiet lanes around mosque.",
tolls:"None",
desc:"Caravanserai of the Qutb Shahis: Shaikpet's sarai arches and old mosque.",
attract:"Shaikpet Sarai arches (verify); mosque streetscape; Tolichowki food.",
foodB:"Tolichowki tiffins (verify) — ₹100–250.",
foodL:"Return-base meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Mehdipatnam corridor pumps if required","~10 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Mehdipatnam","Regroup","10","25 min","10"],["Shaikpet Sarai","Sarai + mosque","8","18 min","60"]],
back:[["Sarai → Mehdipatnam","Cruise","8","18 min","10"],["Mehdipatnam → Saroornagar","Home","10","25 min","—"]],
budget:{food:400,toll:0,park:100,entry:0},
safety:"Congested lanes — walking pace; prayer-hour silence.",
src:["Telangana Tourism — Shaikpet","Google Maps routing"]},
{n:141,name:"Narsingi Lake Evening",dest:"Peacock/Muskhi Lake, Narsingi (Rangareddy)",lat:17.387,lon:78.355,zoom:12,
oneWay:22,total:46,ride:"~1.4 hrs riding + lake",dur:"Half day",durKey:"half",
roads:"City arterials (Saroornagar–Mehdipatnam–Narsingi); paved urban",
terrain:"Paved city road + lake bund",diff:"Easy",cat:["easy","lakes","scenic"],
district:"Rangareddy",
depart:"16:30",season:"Jun–Feb",
warn:"ORR service-lane discipline; lake bund parking bays only.",
tolls:"None",
desc:"Peacock-lake evening: Narsingi's bund, palms and Kokapet-side skyline.",
attract:"Narsingi lake bund (verify); birding corners; sunset bays.",
foodB:"Mehdipatnam tiffins (verify) — ₹150–300.",
foodL:"Narsingi/Kokapet outlets (verify) — ₹200–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Mehdipatnam corridor pumps if required","~12 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Mehdipatnam","Regroup","12","25 min","10"],["Narsingi Lake","Bund + sunset","10","20 min","60"]],
back:[["Lake → Mehdipatnam","Cruise","10","20 min","10"],["Mehdipatnam → Saroornagar","Home","12","25 min","—"]],
budget:{food:450,toll:0,park:100,entry:0},
safety:"Bund soft edges; ORR corridor — service lanes only.",
src:["Telangana Tourism — Narsingi","Google Maps routing"]},
{n:142,name:"Safilguda Lake Ride",dest:"Safilguda Mini Tank Bund, Medchal-Malkajgiri",lat:17.46,lon:78.53,zoom:12,
oneWay:25,total:52,ride:"~1.5 hrs riding + lake",dur:"Half day",durKey:"half",
roads:"City arterials (Saroornagar–Uppal–Malkajgiri–Safilguda); paved urban",
terrain:"Paved city road + lake promenade",diff:"Easy",cat:["easy","lakes","scenic"],
district:"Medchal-Malkajgiri",
depart:"06:00",season:"Jun–Feb",
warn:"Malkajgiri traffic; promenade bays only.",
tolls:"None",
desc:"North-east lake morning: Safilguda's mini tank bund and island.",
attract:"Safilguda promenade (verify); island viewpoint; Malkajgiri food.",
foodB:"Malkajgiri tiffins (verify) — ₹100–250.",
foodL:"Return-base meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Uppal corridor pumps if required","~12 km"]],
support:"Dense city corridor. Hospitals: area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Uppal","Regroup","12","25 min","10"],["Safilguda","Promenade (1 hr)","13","25 min","60"]],
back:[["Safilguda → Uppal","Cruise","13","25 min","10"],["Uppal → Saroornagar","Home","12","25 min","—"]],
budget:{food:400,toll:0,park:100,entry:0},
safety:"Promenade discipline; weekend crowds — early arrival.",
src:["Telangana Tourism — Safilguda","Google Maps routing"]},
{n:143,name:"Kazipet Dargah & Town",dest:"Afzal Biabani Dargah + railway town, Kazipet (Hanamkonda)",lat:17.97,lon:79.51,zoom:10,
oneWay:148,total:300,ride:"~6 hrs riding + town",dur:"Full day",durKey:"full",
roads:"Warangal Hwy (NH163); fast divided highway + town lanes",
terrain:"Good highway + railway-town lanes",diff:"Easy",cat:["easy","heritage","food"],
district:"Hanamkonda",
depart:"05:00",back:"20:00",season:"Oct–Mar; Urs crowds (verify)",
warn:"Railway-town traffic; dargah silence discipline (verify); long day fatigue.",
tolls:"NH tolls (verify)",
desc:"Railway-junction culture: Kazipet's dargah plus Warangal food.",
attract:"Kazipet dargah (verify); railway heritage streetscape; Warangal food halt.",
foodB:"Warangal tiffins — ₹150–300.",
foodL:"Kazipet/Warangal meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Warangal (~148 km) MANDATORY top-up","148 km"]],
support:"NH163 dense. Hospitals: Warangal/MGM; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Warangal","Breakfast + MANDATORY fuel","148","3h","25"],["Kazipet","Dargah + town","8","15 min","60"]],
back:[["Kazipet → Warangal","Tea","8","15 min","15"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:800,toll:150,park:150,entry:0},
safety:"Shrine hours respected; 300-km day — planned halts.",
src:["Telangana Tourism — Kazipet","Google Maps routing"]},
{n:144,name:"Mahadevpur Riverside Camp",dest:"Godavari riverside, Mahadevpur (Jayashankar Bhupalpally)",lat:17.80,lon:79.98,zoom:9,
oneWay:245,total:495,ride:"~9.8 hrs riding over 2 days + river",dur:"1 night / 2 days",durKey:"1n",
roads:"Warangal–Parkal–Mahadevpur Hwy; long highway + riverside tail",
terrain:"Good highway + riverbank",diff:"Moderate",cat:["long","scenic","temples"],
district:"Jayashankar Bhupalpally",
depart:"04:30 Day 1",back:"20:30 Day 2",season:"Oct–Feb",
warn:"Remote riverside tail — fuel + water discipline; ghats — no swimming.",
tolls:"State tolls (verify)",
desc:"Quiet Godavari bend: Mahadevpur's ghats beyond the Kaleshwaram crowds.",
attract:"Mahadevpur ghats + temples (verify); riverside sunrise; Parkal halt.",
foodB:"Day 1: Warangal tiffins.",
foodL:"Mahadevpur/Parkal meals (verify; carry backup) — ₹250–500.",
fuel:[["Start FULL","0 km"],["Warangal (~148 km) MANDATORY","148 km"],["Parkal top-up (verify) MANDATORY","~60 km further"]],
support:"Dense to Parkal; riverside tail sparse. Hospitals: Parkal/Mahadevpur PHC; 108/112.",
route:[["Saroornagar start","Fuel + remote briefing","0","—","15"],["Warangal","Breakfast + MANDATORY fuel","148","3h","30"],["Parkal → Mahadevpur","Riverside","97","2h05","120"]],
back:[["Mahadevpur → Parkal → Warangal","Fuel Warangal","157","3h20","25"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:1500,toll:200,park:200,entry:50},
safety:"Riverside after dark avoided; remote tail — daylight only.",
src:["Telangana Tourism — Mahadevpur","Google Maps routing"]},
{n:145,name:"Kandi Vishwanatha Ride",dest:"Kashi Vishwanatha Temple, Kandi (Sangareddy)",lat:17.60,lon:78.08,zoom:11,
oneWay:90,total:185,ride:"~3.8 hrs riding + temple",dur:"Full day",durKey:"full",
roads:"Mumbai Hwy (NH65) + Kandi link; highway then rural paved",
terrain:"Good highway + temple town",diff:"Easy",cat:["easy","temples","heritage"],
district:"Sangareddy",
depart:"06:00",season:"Oct–Mar",
warn:"IIT-Hyderabad corridor traffic near Kandi; temple-town lanes.",
tolls:"Possible NH toll (verify)",
desc:"Quick west-side temple morning: Kandi's Kashi Vishwanatha plus Patancheru food.",
attract:"Kandi temple complex; temple tank; Patancheru halt.",
foodB:"Patancheru tiffins (verify) — ₹100–250.",
foodL:"Kandi/Patancheru meals (verify) — ₹250–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Patancheru (~50 km) top-up","50 km"]],
support:"NH65 dense. Hospitals: Patancheru/Sangareddy; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Patancheru","Breakfast + fuel","50","1h10","25"],["Kandi","Temple (1 hr)","40","55 min","60"]],
back:[["Kandi → Patancheru","Tea","40","55 min","15"],["Patancheru → Saroornagar","Cruise","50","1h10","—"]],
budget:{food:650,toll:100,park:100,entry:0},
safety:"Corridor trucks — daylight; temple lanes slow.",
src:["Telangana Tourism — Kandi","Google Maps routing"]},
{n:146,name:"Sriram Sagar (Pochampad) Dam",dest:"Sriram Sagar Dam (Pochampad), Nizamabad",lat:18.967,lon:78.343,zoom:9,
oneWay:200,total:405,ride:"~8 hrs riding + dam",dur:"1 night / 2 days",durKey:"1n",
roads:"NH44 (Nizamabad Hwy) + Pochampad link; long highway + dam Rd",
terrain:"Good highway + dam bund",diff:"Moderate",cat:["long","lakes","scenic"],
district:"Nizamabad",
depart:"04:30 Day 1",back:"20:00 Day 2",season:"Aug–Feb (gates + 42 floodgates view, designated points)",
warn:"Telangana's lifeline dam — restricted zones, viewpoints only; long day fatigue.",
tolls:"NH tolls (verify)",
desc:"Godavari's great barrage: Sriram Sagar's 42 floodgates plus Nizamabad food.",
attract:"Sriram Sagar dam wall + viewpoints (verify); reservoir bays; Nizamabad halt.",
foodB:"Day 1: Kamareddy tiffins.",
foodL:"Pochampad/Nizamabad meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Kamareddy (~130 km) MANDATORY","130 km"],["Pochampad top-up (verify)","~70 km further"]],
support:"NH44 dense. Hospitals: Nizamabad; 108/112.",
route:[["Saroornagar start","Fuel + long-ride briefing","0","—","15"],["Kamareddy","Breakfast + MANDATORY fuel","130","2h40","30"],["Pochampad Dam","Dam (1.5 hrs)","70","1h25","90"]],
back:[["Pochampad → Kamareddy","Tea + fuel","70","1h25","20"],["Kamareddy → Saroornagar","Cruise","130","2h40","—"]],
budget:{food:1400,toll:200,park:200,entry:100},
safety:"Barrage water — no wading; dam viewpoints railings only.",
src:["Irrigation Dept — Sriram Sagar notices","Google Maps routing"]},
{n:147,name:"Udaya Samudram Lake",dest:"Udaya Samudram historic lake, Nalgonda",lat:17.06,lon:79.25,zoom:10,
oneWay:110,total:225,ride:"~4.7 hrs riding + lake",dur:"Full day",durKey:"full",
roads:"Nagarjuna Sagar Rd (NH65) + lake link; highway then bund Rd",
terrain:"Good highway + historic bund",diff:"Easy",cat:["easy","lakes","heritage","scenic"],
district:"Nalgonda",
depart:"05:30",season:"Aug–Feb",
warn:"Heritage bund — slow cruise; no racing on bund.",
tolls:"Possible NH toll (verify)",
desc:"Kakatiya water wisdom: Udaya Samudram's old bund near Nalgonda town.",
attract:"Udaya Samudram bund (verify); lake parks; Nalgonda food.",
foodB:"Nalgonda tiffins (verify) — ₹150–300.",
foodL:"Nalgonda town meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Nalgonda (~100 km) top-up","100 km"]],
support:"NH65 dense. Hospitals: Nalgonda; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Nalgonda","Breakfast + fuel","100","2h","25"],["Udaya Samudram","Bund + parks","10","20 min","75"]],
back:[["Lake → Nalgonda","Tea + fuel","10","20 min","15"],["Nalgonda → Saroornagar","Cruise","100","2h","—"]],
budget:{food:700,toll:100,park:100,entry:0},
safety:"Bund soft shoulders; weekend park crowds.",
src:["Telangana Tourism — Udaya Samudram","Google Maps routing"]},
{n:148,name:"Pembarthi Craft Village",dest:"Brass craft village, Pembarthi (Jangaon)",lat:17.72,lon:79.28,zoom:10,
oneWay:125,total:255,ride:"~5.2 hrs riding + craft",dur:"Full day",durKey:"full",
roads:"Warangal Hwy (NH163) + Pembarthi link; highway then village lanes",
terrain:"Good highway + village lanes",diff:"Easy",cat:["easy","heritage","scenic"],
district:"Jangaon",
depart:"05:30",season:"Oct–Mar",
warn:"Artisan-house visits — ask before photos; cash for craft outlets.",
tolls:"Possible NH toll (verify)",
desc:"Metal-craft village: Pembarthi's brass nakshi plus Jangaon food.",
attract:"Brass artisan houses (verify); craft outlets; village lanes.",
foodB:"Jangaon tiffins (verify) — ₹100–250.",
foodL:"Pembarthi/Jangaon meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Jangaon (~100 km) top-up","100 km"]],
support:"NH163 dense. Hospitals: Jangaon; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Jangaon","Breakfast + fuel","100","2h","25"],["Pembarthi","Craft houses (1.5 hrs)","25","35 min","90"]],
back:[["Pembarthi → Jangaon","Tea + fuel","25","35 min","15"],["Jangaon → Saroornagar","Cruise","100","2h","—"]],
budget:{food:700,toll:100,park:100,entry:0},
safety:"Village lanes — livestock; artisan homes — respect privacy.",
src:["Telangana Tourism — Pembarthi","Google Maps routing"]},
{n:149,name:"Padmakshi Hill Temple",dest:"Padmakshi Temple hill, Hanamkonda",lat:17.99,lon:79.57,zoom:10,
oneWay:148,total:300,ride:"~6 hrs riding + hill",dur:"Full day",durKey:"full",
roads:"Warangal Hwy (NH163); fast divided highway + hill link",
terrain:"Good highway + hill steps",diff:"Moderate",cat:["temples","hills","scenic"],
district:"Hanamkonda",
depart:"05:00",back:"20:00",season:"Oct–Mar; Bathukamma season crowds (verify)",
warn:"Jain–Hindu hill complex — shrine discipline; rock steps.",
tolls:"NH tolls (verify)",
desc:"City-hill climb: Padmakshi's Jain–Hindu shrines above Hanamkonda.",
attract:"Padmakshi hill complex (verify); city viewpoint; Warangal food.",
foodB:"Warangal tiffins — ₹150–300.",
foodL:"Hanamkonda/Warangal meals (verify) — ₹250–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Warangal (~148 km) MANDATORY top-up","148 km"]],
support:"NH163 dense. Hospitals: Warangal/MGM; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Warangal","Breakfast + MANDATORY fuel","148","3h","25"],["Padmakshi hill","Climb + shrines","8","15 min","75"]],
back:[["Padmakshi → Warangal","Tea","8","15 min","15"],["Warangal → Saroornagar","Cruise","148","3h","—"]],
budget:{food:800,toll:150,park:150,entry:50},
safety:"Rock steps — solid footwear; festival days — early arrival.",
src:["Telangana Tourism — Padmakshi","Google Maps routing"]},
{n:150,name:"Kotilingala Buddhist Site",dest:"Kotilingala Satavahana–Buddhist excavations, Jagtial",lat:18.43,lon:79.20,zoom:10,
oneWay:180,total:365,ride:"~7.3 hrs riding + site",dur:"1 night / 2 days",durKey:"1n",
roads:"Karimnagar Hwy + Kotilingala Godavari-side link; highway then rural paved",
terrain:"Good highway + riverbank site",diff:"Moderate",cat:["heritage","long","scenic"],
district:"Jagtial",
depart:"05:00 Day 1",back:"19:30 Day 2",season:"Oct–Mar",
warn:"Riverbank excavation — stay on paths; site museum timings (verify).",
tolls:"State tolls (verify)",
desc:"Satavahana river port: Kotilingala's stupas and wharf on the Godavari.",
attract:"Kotilingala stupa + wharf ruins (verify); Godavari bank; Karimnagar halt.",
foodB:"Day 1: Karimnagar tiffins.",
foodL:"Kotilingala/Karimnagar meals (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Karimnagar (~165 km) MANDATORY","165 km"]],
support:"Highway dense; site spur basic. Hospitals: Karimnagar/Jagtial; 108/112.",
route:[["Saroornagar start","Fuel","0","—","15"],["Karimnagar","Breakfast + MANDATORY fuel","165","3h20","30"],["Kotilingala","Site + bank","15","30 min","120"]],
back:[["Kotilingala → Karimnagar","Tea + fuel","15","30 min","20"],["Karimnagar → Saroornagar","Cruise","165","3h20","—"]],
budget:{food:1300,toll:150,park:150,entry:100},
safety:"Riverbank — no wading; excavation — no climbing mounds.",
src:["Telangana Archaeology — Kotilingala","Google Maps routing"]}
];


