/* Trips 1–17: Hyderabad / nearby + first ring (short rides) */
window.TRIPS1 = [
{n:1,name:"Osman Sagar Sunrise Loop",dest:"Osman Sagar (Gandipet Lake), Gandipet",lat:17.377,lon:78.298,zoom:12,
oneWay:28,total:60,ride:"1.5–2 hrs riding + stops",dur:"Half day",durKey:"half",
roads:"City arterials (Kothapet–LB Nagar–Inner Ring Rd) + Gandipet Rd spur; paved, mostly 2-lane near lake",
terrain:"Paved road, gentle undulation",diff:"Easy",cat:["easy","scenic","food"],
depart:"05:30–06:00",back:"10:30–11:30",season:"Jun–Feb (post-monsoon full lake); avoid May midday heat",
warn:"Weekend bund crowds + parked cars; some inner lanes unlit — no night riding; monkeys near viewpoints.",
tolls:"None",
desc:"Classic first ride: short, forgiving, big sunrise payoff over the water. Ideal shakedown for a new Scrambler.",
attract:"Gandipet bund sunrise point; lake viewpoint; Kokapet lakefront extension (optional +8 km).",
foodB:"Subbayya Gari Hotel, Kothapet (start) — Andhra tiffins/meals — ₹150–300 — from ~6:30 AM (verify on Maps).",
foodL:"Lakefront tiffin stalls + Kokapet food trucks (weekends) — snacks ₹100–250 — verify hygiene; or return to Kothapet for meals.",
fuel:[["Start FULL at Saroornagar (NH65 / Kothapet–Dilsukhnagar COCO + HP/BPCL/IOCL corridor)","0 km"],["Optional top-up Gandipet X Rd outlets (HP/BPCL)","~20 km from start"]],
support:"Dense puncture/tyre + workshop corridor LB Nagar–Gandipet. No remote gap. Hospitals: area hospitals Kothapet/LB Nagar; emergency 108/112.",
route:[["Saroornagar start — Kothapet Water Tank junction area","Common landmark start; fuel, odo reset, group lineup","0","—","10"],["LB Nagar X Roads","Traffic funnel; regroup after signal cluster","4","12 min","5"],["Inner Ring Rd → Gandipet X Rd","Tea/coffee + restroom halt at roadside clusters","10","20 min","15"],["Gandipet bund / viewpoint","Sunrise + photos; walk the bund","12","25 min","30"],["Kokapet lakefront (optional)","Breakfast trucks + second photo stop","6","12 min","25"]],
back:[["Kokapet → Gandipet X Rd","Regroup; fuel check","8","15 min","5"],["Gandipet X Rd → LB Nagar","Tea halt if needed","16","30 min","10"],["LB Nagar → Saroornagar","Home; expected before 11:30 AM","4","12 min","—"]],
budget:{food:400,toll:0,park:100,entry:0},
safety:"Bund parking on soft shoulders — use centre stand/solid footing; watch for reversing cars at viewpoints.",
src:["Telangana Tourism — Gandipet/Osman Sagar","Google Maps routing (Saroornagar–Gandipet)"]},
{n:2,name:"Himayat Sagar Evening Spin",dest:"Himayat Sagar Lake, Hyderabad",lat:17.312,lon:78.347,zoom:12,
oneWay:20,total:44,ride:"~1.2 hrs riding + stops",dur:"Half day",durKey:"half",
roads:"Nagarjuna Sagar Rd (NH65 spur) + Himayat Sagar Rd; paved, good highway start then 2-lane",
terrain:"Paved road, flat",diff:"Easy",cat:["easy","scenic"],
depart:"16:00 (evening) / 06:00 (morning)",back:"19:30 / 10:00",season:"Jul–Feb; monsoon gates view best (from designated points only)",
warn:"Do not approach sluices/bund restricted zones; evening truck traffic on NH65 service lanes.",
tolls:"None",
desc:"Shortest real ride in the book — perfect for a weekday-evening spin or pillion shakedown.",
attract:"Himayat Sagar bund view, sunset point, lakeside walkway stretches.",
foodB:"Meals/tiffins clusters at Kothapet–Saroornagar start (e.g. Subbayya Gari Hotel) — ₹150–300.",
foodL:"Evening snacks at lakeside stalls (verify) or return to Saroornagar dhabas.",
fuel:[["Start FULL at Saroornagar corridor","0 km"],["No en-route fuel needed; optional Himayat Sagar Rd outlets","~14 km"]],
support:"Fully urban; puncture shops along NH65 service road. No gap. Hospitals: LB Nagar/Saroornagar area; 108/112.",
route:[["Saroornagar start — Kothapet Water Tank area","Fuel + briefing","0","—","10"],["Nagarjuna Sagar Rd junction","Join NH65 spur; staggered formation","6","15 min","5"],["Himayat Sagar Rd turn","Photo + water halt","8","15 min","10"],["Himayat Sagar bund viewpoint","Sunset/photos","6","12 min","35"]],
back:[["Bund → NH65","Regroup, lights check if dusk","6","12 min","5"],["NH65 → Saroornagar","Dinner optional at Kothapet","14","25 min","—"]],
budget:{food:350,toll:0,park:50,entry:0},
safety:"Dusk visibility — reflective layer on; keep headlights on; no bund-edge parking.",
src:["Telangana Tourism — Himayat Sagar","Google Maps routing"]},
{n:3,name:"Chilkur Balaji Temple Ride",dest:"Chilkur Balaji (Visa Balaji) Temple, Chilkur",lat:17.354,lon:78.297,zoom:12,
oneWay:30,total:64,ride:"~2 hrs riding + darshan",dur:"Half day",durKey:"half",
roads:"Gandipet Rd via Narsingi/CB IT corridor; paved, moderate traffic",
terrain:"Paved road",diff:"Easy",cat:["easy","heritage","food"],
depart:"05:30–06:00",back:"11:30–12:00",season:"All year; Sat/Sun crowded — go early",
warn:"Temple parking chaos on weekends; no-phone discipline inside; monkeys; footwear stand queues.",
tolls:"None",
desc:"Visa Balaji blessing ride — combine with Osman Sagar viewpoint on return. Devotional + scenic combo.",
attract:"Chilkur Balaji darshan (11 pradakshinas custom); Mrugavani National Park gate (safari check) nearby; Osman Sagar detour.",
foodB:"Tiffin clusters at Narsingi/Gandipet X Rd (multiple verified outlets) — ₹100–250 — verify hours.",
foodL:"Return via Kokapet/Gandipet stalls or Kothapet meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Top-up optional Narsingi/Gandipet outlets","~22 km"]],
support:"Urban corridor; workshops at Narsingi/Manikonda. No gap. Hospitals: Narsingi/Gandipet private + area hospitals; 108/112.",
route:[["Saroornagar start","Fuel + odo","0","—","10"],["LB Nagar → Narsingi","Breakfast halt","18","35 min","20"],["Narsingi → Chilkur Rd","Temple approach; park in designated lots","10","20 min","—"],["Chilkur Balaji Temple","Darshan (1–1.5 hrs weekend)","2","10 min","75"]],
back:[["Chilkur → Gandipet viewpoint (optional)","Photos + rest","8","15 min","20"],["Gandipet → Saroornagar","Home by noon","26","50 min","—"]],
budget:{food:400,toll:0,park:100,entry:0},
safety:"Temple zone pedestrians; ride at walking pace inside lanes; secure helmets (carry lock).",
src:["Chilkur Balaji Devasthanam notices","Google Maps routing","Telangana Tourism — Mrugavani"]},
{n:4,name:"Kokapet Lakefront Food Run",dest:"Kokapet Lakefront / Neopolis Rd, Kokapet",lat:17.39,lon:78.332,zoom:12,
oneWay:30,total:64,ride:"~2 hrs riding + food halts",dur:"Half day",durKey:"half",
roads:"ORR + Kokapet / Neopolis roads; good highway + paved lakefront",
terrain:"Paved road, good highway",diff:"Easy",cat:["easy","food","scenic"],
depart:"06:00 / 16:30",back:"11:00 / 20:30",season:"All year; evenings liveliest",
warn:"ORR speed discipline (limits enforced); lakefront night crowds + limited parking.",
tolls:"ORR toll if you use ORR segments (2-wheeler: ORR access rules apply — use service/frontage where required; carry change/FASTag as applicable).",
desc:"Easy food-first ride: lake views + the Kokapet truck/park food scene. Great for new group members.",
attract:"Kokapet lake promenade, Gandipet viewpoint add-on, Financial District skyline photos.",
foodB:"Kokapet food-truck park + lakefront cafés (multiple verified listings) — ₹150–400 — evenings best; verify on Maps.",
foodL:"Same strip; or Golden Dragon / area restaurants (verify).",
fuel:[["Start FULL Saroornagar","0 km"],["Narsingi/Kokapet outlets if needed","~24 km"]],
support:"Urban; Manikonda/Kokapet workshops. No gap. Hospitals: Narsingi/Gachibowli corridor; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["ORR / Narsingi corridor","Tea halt","20","35 min","15"],["Kokapet lakefront","Food + photos","10","20 min","60"]],
back:[["Lakefront → Narsingi","Regroup","10","20 min","5"],["Narsingi → Saroornagar","Home","20","35 min","—"]],
budget:{food:600,toll:100,park:100,entry:0},
safety:"Two-wheeler ORR rules vary by notification — if unsure, stay on service/frontage roads; never stop on main carriageway.",
src:["Google Maps routing","HMDA/ORR user guidance (verify current 2-wheeler rules)"]},
{n:5,name:"Shamirpet Lake & Deer Park",dest:"Shamirpet Lake + Deer Park, Shamirpet",lat:17.586,lon:78.576,zoom:11,
oneWay:48,total:100,ride:"~2.5 hrs riding + stops",dur:"Half day",durKey:"half",
roads:"NH65 → ECIL → Medchal/Shamirpet Rd (SH1); good highway then 2-lane lakeside",
terrain:"Paved road, flat with lakeside breeze",diff:"Easy",cat:["easy","scenic","heritage"],
depart:"05:30",back:"12:00",season:"Jul–Feb; winter birding pleasant",
warn:"Deer Park entry/queue; lake bund narrow in patches; weekend picnic traffic.",
tolls:"None (avoid tolled ORR; use NH/SH)",
desc:"North-side classic: big lake, deer park, and the reliable Haritha stop. Beginner-friendly distance.",
attract:"Shamirpet Lake viewpoint; Deer Park (Telangana Forest); lakeside sunrise.",
foodB:"Haritha Deer Park Restaurant (TSTDC, Shamirpet) — verified chain outlet — meals/snacks ₹200–450 — verify hours on TSTDC/Maps.",
foodL:"Same Haritha; or Medchal highway dhabas on return.",
fuel:[["Start FULL Saroornagar","0 km"],["ECIL/Medchal outlets (multiple HP/BPCL/IOCL)","~30 km"]],
support:"ECIL–Medchal–Shamirpet corridor has puncture/workshop clusters. Short gap near lake bund — plan accordingly. Hospitals: ECIL/Medchal area hospitals; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Uppal → ECIL X Roads","Regroup after city traffic","16","30 min","10"],["ECIL → Shamirpet","Tea + restroom","22","35 min","15"],["Shamirpet Lake + Deer Park","Lake + park (1–1.5 hrs)","10","20 min","80"]],
back:[["Deer Park → ECIL","Lunch option Medchal dhabas","32","50 min","30"],["ECIL → Saroornagar","Home via Uppal","16","30 min","—"]],
budget:{food:500,toll:0,park:100,entry:200},
safety:"Deer Park: follow forest rules; no honking inside eco-zone; helmets secured.",
src:["TSTDC Haritha — Shamirpet","Telangana Forest — Deer Park","Google Maps routing"]},
{n:6,name:"Moinabad Farm & Dhaba Loop",dest:"Moinabad village loop (Chilkur–Moinabad–Shamshabad circuit)",lat:17.324,lon:78.276,zoom:11,
oneWay:45,total:95,ride:"~2.5 hrs riding + food",dur:"Half day",durKey:"half",
roads:"Gandipet–Moinabad SH; paved rural 2-lane, some patches",
terrain:"Paved road, occasional poor road patches",diff:"Easy",cat:["easy","food","scenic"],
depart:"06:00 / 16:00",back:"11:30 / 20:00",season:"Jul–Mar (green fields post-monsoon)",
warn:"Village speed-breakers + livestock; unlit SH at night — return before dark.",
tolls:"None",
desc:"Laid-back rural loop through farm country with dhaba halts. Low stress, high chai.",
attract:"Green fields, village lakes, farm stays viewable from road; Shamshabad lake add-on.",
foodB:"Highway dhabas on Moinabad Rd (multiple verified clusters) — ₹150–350 — verify on Maps.",
foodL:"Dhaba meals (dal/sabzi/roti) or return to city.",
fuel:[["Start FULL Saroornagar","0 km"],["Shamshabad/Moinabad outlets","~30 km"]],
support:"Shamshabad + Moinabad town puncture clusters. Gap: fields between villages — 'No verified roadside mechanic found at this section — plan accordingly.' Hospitals: Shamshabad area; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Shamshabad Rd","Tea halt","22","35 min","15"],["Moinabad village loop","Slow rural circuit + photos","18","35 min","40"],["Return spur","Dhaba lunch/tea","5","10 min","30"]],
back:[["Moinabad → Shamshabad","Regroup","23","40 min","5"],["Shamshabad → Saroornagar","Home","22","35 min","—"]],
budget:{food:500,toll:0,park:50,entry:0},
safety:"Gravel at field exits; give way to tractors; no off-road detours without checking surface.",
src:["Google Maps routing (Moinabad loop)"]},
{n:7,name:"Chevella Anantha Padmanabha Temple",dest:"Anantha Padmanabha Swamy Temple, Chevella",lat:17.306,lon:78.141,zoom:11,
oneWay:62,total:130,ride:"~3 hrs riding + darshan",dur:"Full day",durKey:"full",
roads:"Chevella Rd (SH4/SH6 corridor) via Moinabad; paved 2-lane, mixed patches",
terrain:"Paved road, some poor road sections",diff:"Easy",cat:["easy","heritage","scenic"],
depart:"05:30",back:"14:00",season:"Jul–Mar",
warn:"Narrow town approach; temple timing windows; afternoon heat on return.",
tolls:"None",
desc:"Heritage half-plus ride to a historic temple town — calm roads, big banyan shade, easy pace.",
attract:"Anantha Padmanabha Temple darshan; Chevella market walk; Moinabad green stretch.",
foodB:"Moinabad dhabas en route — ₹150–300.",
foodL:"Chevella town meals clusters (verify) or packed return to Moinabad dhabas.",
fuel:[["Start FULL Saroornagar","0 km"],["Moinabad (~35 km) outlets","35 km"],["Chevella town outlets","~27 km further"]],
support:"Moinabad + Chevella puncture/workshop clusters. Gap: Moinabad–Chevella mid-section sparse — plan accordingly. Hospitals: Chevella govt hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Moinabad","Breakfast + restroom","35","55 min","25"],["Moinabad → Chevella","Temple approach","27","45 min","—"],["Chevella Temple","Darshan + rest","2","10 min","60"]],
back:[["Chevella → Moinabad","Tea + fuel check","27","45 min","15"],["Moinabad → Saroornagar","Home","35","55 min","—"]],
budget:{food:550,toll:0,park:100,entry:50},
safety:"Town lanes: pedestrians + parked autos; keep formation single-file.",
src:["Endowments Dept — temple listings","Google Maps routing"]},
{n:8,name:"Vikarabad — Kotpally Reservoir",dest:"Kotpally Reservoir, Vikarabad",lat:17.54,lon:77.896,zoom:10,
oneWay:95,total:200,ride:"~4.5 hrs riding + stops",dur:"Full day",durKey:"full",
roads:"Mumbai Hwy (NH65) to Vikarabad Rd; good highway then scenic 2-lane",
terrain:"Paved road, rolling",diff:"Moderate",cat:["scenic","adventure"],
depart:"05:00",back:"18:00",season:"Aug–Feb (reservoir full, green)",
warn:"Vikarabad town traffic; reservoir bund no-parking zones; evening highway trucks.",
tolls:"Possible NH65 tolls for 4-wheelers; bikes often exempt — carry change; verify current rule.",
desc:"Step-up distance: highway cruise + reservoir calm. Gateway to Ananthagiri without the ghats.",
attract:"Kotpally Reservoir viewpoint; Vikarabad town; optional Ananthagiri extension (+18 km).",
foodB:"Vikarabad town tiffins (multiple verified) — ₹150–300 — verify hours.",
foodL:"Vikarabad meals / Haritha (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Shankarpally (~55 km) outlets","55 km"],["Vikarabad town outlets","~40 km further"]],
support:"NH65 corridor + Shankarpally + Vikarabad workshops. Gap: reservoir bund road sparse — plan accordingly. Hospitals: Vikarabad govt/area hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["ORR/NH65 — Shankarpally","Breakfast + fuel","55","75 min","25"],["Shankarpally → Vikarabad","Cruise","30","45 min","10"],["Vikarabad → Kotpally","Reservoir viewpoint","10","20 min","45"]],
back:[["Kotpally → Vikarabad","Lunch + fuel","10","20 min","40"],["Vikarabad → Shankarpally → Saroornagar","Return cruise; tea at Shankarpally","85","2 hrs","15"]],
budget:{food:700,toll:0,park:100,entry:0},
safety:"Bund: no riding on restricted embankments; soft shoulders — park on hard standing.",
src:["Telangana Tourism — Vikarabad/Kotpally","Google Maps routing"]},
{n:9,name:"Ananthagiri Hills",dest:"Ananthagiri Hills, Vikarabad",lat:17.317,lon:77.864,zoom:10,
oneWay:82,total:175,ride:"~4 hrs riding + viewpoints",dur:"Full day",durKey:"full",
roads:"NH65 + Vikarabad–Ananthagiri ghat road; good highway then winding paved ghat",
terrain:"Paved road, ghat curves",diff:"Moderate",cat:["scenic","adventure"],
depart:"05:00",back:"17:30",season:"Jul–Feb (monsoon green; winter crisp)",
warn:"Ghat curves + weekend tourist cars; monkey zones; mist in monsoon mornings; no night ghat.",
tolls:"Possible NH65 toll segments (verify bike rule)",
desc:"Hyderabad's favourite hill escape: coffee-plantation air, viewpoints, and the Scrambler's happiest curves.",
attract:"Ananthagiri viewpoint; Anantha Padmanabha Temple (Ananthagiri); coffee gardens; Kotpally add-on.",
foodB:"Vikarabad town tiffins en route — ₹150–300.",
foodL:"Haritha Hill Resort / Ananthagiri (TSTDC, verify) + Vikarabad meals — ₹300–500.",
fuel:[["Start FULL Saroornagar","0 km"],["Shankarpally outlets","~55 km"],["Vikarabad outlets","~25 km further"]],
support:"Shankarpally + Vikarabad clusters; ghat top sparse — 'No verified roadside mechanic found at this section — plan accordingly.' Hospitals: Vikarabad hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Shankarpally","Breakfast + fuel top-up","55","75 min","25"],["Vikarabad","Regroup; water","22","35 min","10"],["Ananthagiri ascent + viewpoints","Ghat ride + photos","12","30 min","60"]],
back:[["Hills → Vikarabad","Lunch + fuel","12","30 min","45"],["Vikarabad → Saroornagar","Cruise home","80","2 hrs","15"]],
budget:{food:750,toll:0,park:100,entry:100},
safety:"Ghat: own lane, no corner-cutting; engine braking downhill; pillion brief before descent.",
src:["TSTDC Haritha — Ananthagiri","Telangana Tourism — Ananthagiri Hills","Google Maps routing"]},
{n:10,name:"Tandur Fort & Countryside",dest:"Tandur Fort / town, Tandur",lat:17.235,lon:77.584,zoom:10,
oneWay:115,total:240,ride:"~5 hrs riding + stops",dur:"Full day",durKey:"full",
roads:"NH65 + Tandur Rd (SH); good highway then rural 2-lane",
terrain:"Paved road, some poor patches near town",diff:"Moderate",cat:["heritage","adventure"],
depart:"05:00",back:"18:30",season:"Oct–Mar",
warn:"Long rural tail with sparse fuel; town fort access may need local guidance; heat.",
tolls:"Possible NH segments (verify)",
desc:"Offbeat heritage push past Vikarabad into Tandur country — dal, stone, and wide skies.",
attract:"Tandur Fort remains; town temples; countryside photo stops.",
foodB:"Vikarabad tiffins — ₹150–300.",
foodL:"Tandur town meals (verify clusters) — ₹200–400.",
fuel:[["Start FULL","0 km"],["Vikarabad (~80 km)","80 km"],["Tandur town","~35 km further — mandatory top-up before return"]],
support:"Vikarabad + Tandur clusters. Gap: Vikarabad–Tandur mid-section sparse — plan accordingly. Hospitals: Tandur govt hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Vikarabad","Breakfast + fuel","80","2 hrs","30"],["Vikarabad → Tandur","Rural cruise","35","55 min","10"],["Tandur Fort/town","Explore + rest","5","15 min","60"]],
back:[["Tandur → Vikarabad","Fuel + tea","35","55 min","20"],["Vikarabad → Saroornagar","Cruise","80","2 hrs","10"]],
budget:{food:750,toll:50,park:100,entry:0},
safety:"Carry water + sun protection; confirm fort access locally; no unlit rural riding after dark.",
src:["District Tandur listings","Google Maps routing"]},
{n:11,name:"Shadnagar Heritage & Food Halt",dest:"Shadnagar / Farooqnagar, NH44",lat:17.071,lon:78.203,zoom:11,
oneWay:62,total:130,ride:"~3 hrs riding + halts",dur:"Half day",durKey:"half",
roads:"NH44 (Bangalore Hwy); good highway, fast corridor",
terrain:"Good highway",diff:"Easy",cat:["easy","food"],
depart:"06:00 / 16:00",back:"12:00 / 20:00",season:"All year",
warn:"NH44 high-speed traffic; crosswinds; service-lane merges.",
tolls:"NH44 toll plazas (verify bike rule; carry change)",
desc:"Highway-cruise training ride with famous Shadnagar food halts. Simple, fast, satisfying.",
attract:"NH44 cruise; Shadnagar town; roadside food + sunset return.",
foodB:"Shadnagar highway restaurants/dhabas (multiple verified, e.g. highway food courts) — ₹150–400 — verify.",
foodL:"Return dhabas or city.",
fuel:[["Start FULL Saroornagar","0 km"],["Shamshabad (~25 km) + Shadnagar outlets","25/62 km"]],
support:"NH44 corridor dense (Shamshabad–Shadnagar). No gap. Hospitals: Shamshabad/Shadnagar hospitals; 1033 on NH; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Shamshabad","Tea + formation check","25","35 min","10"],["Shamshabad → Shadnagar","Highway cruise","37","45 min","10"],["Shadnagar halt","Food + rest","2","10 min","40"]],
back:[["Shadnagar → Shamshabad","Cruise","37","45 min","10"],["Shamshabad → Saroornagar","Home","25","35 min","—"]],
budget:{food:600,toll:50,park:50,entry:0},
safety:"Highway: staggered, 3-sec gap; no shoulder riding; trucks — pass decisively, never linger alongside.",
src:["NHAI — NH44 corridor","Google Maps routing"]},
{n:12,name:"Maheshwaram Temple & Lake",dest:"Maheshwaram Temple + lake, Maheshwaram",lat:17.131,lon:78.429,zoom:11,
oneWay:34,total:72,ride:"~1.8 hrs riding + darshan",dur:"Half day",durKey:"half",
roads:"Sagar Rd → Maheshwaram Rd; paved, semi-rural",
terrain:"Paved road",diff:"Easy",cat:["easy","heritage"],
depart:"06:00",back:"11:30",season:"All year; winter mornings best",
warn:"Narrow village approach near temple; festival-day crowds.",
tolls:"None",
desc:"Quiet devotional short ride — Shiva temple + lake calm, minimal traffic.",
attract:"Maheshwaram Shiva Temple; lake viewpoint.",
foodB:"Start-area tiffins + Maheshwaram small eateries (verify) — ₹100–250.",
foodL:"Return to Saroornagar meals.",
fuel:[["Start FULL Saroornagar","0 km"],["No en-route fuel needed"]],
support:"Urban start + Maheshwaram town basic puncture options. No major gap. Hospitals: Tukkuguda/Maheshwaram PHC + city; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Tukkuguda","Tea halt","18","30 min","10"],["Maheshwaram Temple + lake","Darshan + lakeside rest","16","30 min","60"]],
back:[["Maheshwaram → Tukkuguda → Saroornagar","Direct return","34","55 min","—"]],
budget:{food:350,toll:0,park:50,entry:0},
safety:"Village children/livestock near temple lanes — walking pace.",
src:["Endowments listings","Google Maps routing"]},
{n:13,name:"Ramoji Gate & Abdullapurmet Loop",dest:"Ramoji Film City main gate area, Abdullapurmet",lat:17.254,lon:78.681,zoom:11,
oneWay:35,total:75,ride:"~2 hrs riding + stops",dur:"Half day",durKey:"half",
roads:"Vijayawada Hwy (NH65); good highway",
terrain:"Good highway + paved",diff:"Easy",cat:["easy","food","scenic"],
depart:"06:00 / 16:00",back:"11:00 / 19:30",season:"All year",
warn:"NH65 fast traffic; Film City entry needs pre-booking — gate photos only unless ticketed; no roadside stopping on highway.",
tolls:"Possible NH toll (verify)",
desc:"East-side highway loop: feel the big road, photograph the famous gate, chai at Abdullapurmet.",
attract:"Ramoji gate arch; countryside; highway + gate.",
foodB:"Abdullapurmet highway eateries (verified clusters) — ₹150–350.",
foodL:"Return city meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Abdullapurmet outlets","~28 km"]],
support:"NH65 dense corridor. No gap. Hospitals: LB Nagar/Hayathnagar; 1033; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Hayathnagar","Regroup","10","20 min","5"],["Abdullapurmet → Ramoji gate","Cruise + gate photos","25","35 min","30"]],
back:[["Gate → Hayathnagar","Tea","25","35 min","15"],["Hayathnagar → Saroornagar","Home","10","20 min","—"]],
budget:{food:450,toll:50,park:50,entry:0},
safety:"Never park on highway shoulder for photos — use lay-byes/service lanes only.",
src:["Ramoji Film City official (entry info)","Google Maps routing"]},
{n:14,name:"Keesaragutta Temple Hill",dest:"Keesaragutta Ramalingeswara Temple, Keesara",lat:17.504,lon:78.677,zoom:11,
oneWay:42,total:90,ride:"~2.2 hrs riding + darshan",dur:"Half day",durKey:"half",
roads:"NH65/Uppal → Keesara Rd; good highway then hill approach (paved, steps on foot)",
terrain:"Paved road, short hill climb",diff:"Easy",cat:["easy","heritage","scenic"],
depart:"05:30",back:"12:00",season:"All year; Shivaratri very crowded",
warn:"Hill parking + monkey menace; footwear care; festival crowds.",
tolls:"None",
desc:"Rocky-hill Shiva temple with valley views — a rewarding short climb for the Scrambler's torque.",
attract:"Keesaragutta temple; hill viewpoint; Keesara Gutta rock formations.",
foodB:"Uppal/ECIL tiffins en route (verified clusters) — ₹100–250.",
foodL:"Return city meals.",
fuel:[["Start FULL Saroornagar","0 km"],["Uppal/Keesara outlets","~20 km"]],
support:"Urban corridor to Keesara; hilltop sparse — plan accordingly. Hospitals: Uppal/ECIL; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Uppal","Breakfast","14","25 min","20"],["Keesara → hilltop","Climb + park in lots","28","45 min","10"],["Temple","Darshan + viewpoint","1","10 min","60"]],
back:[["Hill → Uppal","Tea","29","45 min","10"],["Uppal → Saroornagar","Home","14","25 min","—"]],
budget:{food:400,toll:0,park:100,entry:0},
safety:"Hill road: first-gear hairpins with pillion; use engine braking down.",
src:["Endowments — Keesaragutta","Google Maps routing"]},
{n:15,name:"Medchal Highway Dhaba Run",dest:"Medchal (Katta Maisamma corridor), Medchal",lat:17.63,lon:78.481,zoom:11,
oneWay:55,total:115,ride:"~2.8 hrs riding + food",dur:"Half day",durKey:"half",
roads:"NH44 north (Nagpur Hwy); good highway",
terrain:"Good highway",diff:"Easy",cat:["easy","food"],
depart:"06:00 / 17:00",back:"12:00 / 21:00",season:"All year",
warn:"NH44 night truck density; dhaba parking on service lanes only.",
tolls:"Possible NH toll (verify)",
desc:"North-highway food mission: dhabas, Maisamma darshan option, and open-road cruise.",
attract:"Katta Maisamma Temple (optional); Medchal town; highway food strip.",
foodB:"Medchal highway dhabas (multiple verified) — ₹150–400 — verify on Maps.",
foodL:"Dhaba meals or return city.",
fuel:[["Start FULL Saroornagar","0 km"],["Kompally/Medchal outlets","~45 km"]],
support:"NH44 dense. No gap. Hospitals: Kompally/Medchal; 1033; 108/112.",
route:[["Saroornagar start","Fuel; ORR/NH link","0","—","10"],["Kompally","Tea + regroup","45","60 min","15"],["Medchal strip","Food + optional temple","10","15 min","45"]],
back:[["Medchal → Kompally → Saroornagar","Return cruise","55","75 min","10"]],
budget:{food:550,toll:50,park:50,entry:0},
safety:"Dhaba exits: rejoin highway via service lane; full shoulder check.",
src:["Google Maps routing","NHAI NH44"]},
{n:16,name:"Bhongir Fort Trek Ride",dest:"Bhongir (Bhuvanagiri) Fort, Yadadri Bhuvanagiri",lat:17.516,lon:78.886,zoom:11,
oneWay:52,total:110,ride:"~2.6 hrs riding + trek",dur:"Full day",durKey:"full",
roads:"Vijayawada Hwy (NH65) → Bhongir; good highway, town approach paved",
terrain:"Paved road; trek on foot (rocky, steep)",diff:"Moderate",cat:["adventure","heritage","scenic"],
depart:"05:00",back:"15:00",season:"Oct–Mar (trek); monsoon slippery — grip care",
warn:"Fort trek needs 2–3 hrs + water; rock steps slippery when wet; town parking touts.",
tolls:"Possible NH toll (verify)",
desc:"Ride + trek combo: highway cruise, then a real fort climb with 360° Deccan views.",
attract:"Bhongir Fort trek; town temples; lake viewpoint.",
foodB:"Bhongir town tiffins (verified clusters) — ₹100–250.",
foodL:"Bhongir meals (verify) — ₹200–400.",
fuel:[["Start FULL Saroornagar","0 km"],["Choutuppal/Bhongir outlets (~45/52 km)","45 km"]],
support:"NH65 corridor + Bhongir town workshops. Fort hilltop: no mechanic — plan accordingly. Hospitals: Bhongir govt hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Choutuppal","Breakfast + fuel check","45","55 min","25"],["Bhongir town → fort base","Park in lots; trek briefing","9","20 min","10"],["Bhongir Fort trek","Climb + fort + descend (on foot)","2","15 min","150"]],
back:[["Fort base → Choutuppal","Lunch + tea","9","20 min","40"],["Choutuppal → Saroornagar","Cruise home","45","55 min","—"]],
budget:{food:600,toll:50,park:100,entry:100},
safety:"Trek: shoes with grip, 2L water, no riding gear on rock — change/lock gear; start descent by 1 PM.",
src:["Telangana Tourism — Bhongir Fort","Google Maps routing"]},
{n:17,name:"Yadadri Lakshmi Narasimha Temple",dest:"Yadadri (Yadagirigutta) Temple, Yadadri Bhuvanagiri",lat:17.589,lon:79.054,zoom:10,
oneWay:72,total:150,ride:"~3.2 hrs riding + darshan",dur:"Full day",durKey:"full",
roads:"NH65 to Yadadri; good highway, temple hill approach paved",
terrain:"Paved road, good highway",diff:"Easy",cat:["heritage","easy"],
depart:"04:30–05:00",back:"15:00",season:"All year; Brahmotsavam crowded",
warn:"Reconstructed temple: strict queue/security; parking formalities; weekend rush — pre-check darshan slots.",
tolls:"Possible NH toll (verify)",
desc:"Premier devotional full-dayer on fresh highway — rebuilt temple complex, orderly queues, prasadam.",
attract:"Sri Lakshmi Narasimha Swamy Temple; temple-town gopuram views; Bhongir add-on possible.",
foodB:"Choutuppal tiffins en route (verified clusters) — ₹100–250.",
foodL:"Temple-town meals / Haritha (verify) — ₹250–450.",
fuel:[["Start FULL Saroornagar","0 km"],["Choutuppal (~45 km) outlets","45 km"],["Yadadri town outlets","~27 km further"]],
support:"NH65 corridor dense to Yadadri. No major gap. Hospitals: Yadadri govt/area hospital; 108/112.",
route:[["Saroornagar start","Fuel","0","—","10"],["Choutuppal","Breakfast + fuel","45","55 min","25"],["Choutuppal → Yadadri","Cruise","27","40 min","10"],["Yadadri Temple","Darshan (1.5–2.5 hrs)","3","10 min","120"]],
back:[["Yadadri → Choutuppal","Lunch/tea + fuel","27","40 min","40"],["Choutuppal → Saroornagar","Cruise","45","55 min","—"]],
budget:{food:650,toll:50,park:100,entry:100},
safety:"Temple security: minimal luggage; helmet locks; no drone photography.",
src:["Yadadri Temple official / Endowments","Google Maps routing"]}
];
